### ISSUE TITLE
Simplifying specific repro protocol variable names

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1007]
Currently, the reproduction programs used by heifers and cows have specific variables associated with each program, which makes it hard to manage. For example, we have some variables that are tied to the TAI method like `tai_program_start_day_h`, or to the SynchED method like `synched_*_h`.

These variables should be safely removed because the HeiferII and Cow classes can access these repro program properties directly from `AnimalBase.config` or via static/class methods.

**Comment by Isgotkowitz** [comment]
@ltp revisit this issue and update it to reflect current changes needed.

**Comment by PooyaHekmati** [comment]
TODO: Follow up with author to check if this is still the case.

**Comment by Isgotkowitz** [comment]
This issue will be taken care of in #1997.
