### ISSUE TITLE
Verify wiki for example report output filter

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1011]
## Current Behavior
Due to changes to variables added to Output Manager, the report_example.json filter has several erroring filters:

```
      {
        "name": "First Month's Methane Emission from Pen 0",
        "filters": ["Pen\\.calc_total_manure\\.pen_0_daily_methane"],
        "vertical_aggregation": "sum",
        "slice_end": 30
      },
      {
        "name": "Last Month's Methane Emission from Pen 0",
        "filters": ["Pen\\.calc_total_manure\\.pen_0_daily_methane"],
        "vertical_aggregation": "sum",
        "slice_start": -30
      },
      {
        "name": "90 to 30 days ago Methane Emission from Pen 0",
        "filters": ["Pen\\.calc_total_manure\\.pen_0_daily_methane"],
        "vertical_aggregation": "sum",
        "slice_start": -90,
        "slice_end": -30
      }
```

Resulting in this error:
<img width="1408" alt="Screenshot 2023-12-01 at 12 09 41 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/964c014f-5bf5-4a7f-9f48-69be0f654582">

## Possible Solution
A similar issue came up within the graph generator example filter because the `calc_total_manure` method is no longer being called. Not sure if it's a long-term deprecation or a temporary one but if it's helpful to keep the same example data for these report examples, then replacing the filters in the above mentioned block with whatever the updated method that is collecting the pen daily methane would be the suggested fix.

Longer term I'm not sure the best way to keep these example filters clean other than if you see it broken, create an issue to fix it (or just fix it).

**Comment by allisterakun** [comment]
We should not even have this file in the first place; we should have all the information in the wiki and confirm all of them are correct.

**Comment by Isgotkowitz** [comment]
This part of #1184
