### ISSUE TITLE
Consolidate config.py and state.py to simulation engine

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1017]
The classes `Config` and `State` in config.py and state.py seem to be doing things that are in the domain of of responsibilities of the simulation engine. Consolidate them to the simulation engine and delete them from the codebase. Be mindful about the things that are dependent on them. After doing this, consider cleaning up the simulation engine itself as well, and make an issue about refactoring it.

**Comment by allisterakun** [comment]
- [x] Consolidate `Config` and `State` into `SimulationEngine`
- [ ] Change all dependencies
- [ ] Clean up `SimulationEngine`
- [ ] Make an issue for `SimulationEngine` refactor
