### ISSUE TITLE
Refactor the update method in HeiferII class

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1038]
The `update()` method in the HeiferII class (heiferII.py) is quite long and complicated. It should be refactored to make it more testable. Make sure to test for a variety of scenarios like which repro protocol the heifer is currently following, which event day she is due to, etc.

**Comment by ew3361zh** [comment]
Should this issue and #1036 be blocked by the Animal refactor #1680?

**Comment by allisterakun** [comment]
> Should this issue and [#1036](https://github.com/RuminantFarmSystems/MASM/issues/1036) be blocked by the Animal refactor [#1680](https://github.com/RuminantFarmSystems/MASM/issues/1680)?

I believe so!

**Comment by Isgotkowitz** [comment]
This issue is closed as unplanned. The daily update routine for HeiferIIs will be replaced with a more general daily update routine for all animals, and the problematic aspects of HeiferIIs repro methods will be addressed with the reproduction refactor.
