### ISSUE TITLE
Separate Manure Nutrient pools by manure type

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1043]
**Is your feature request related to a problem? Please describe.**
Currently the ManureNutrient class sums manure mass and nutrients across all types of manure in all pens. However, we need to keep the different types of manure separate (i.e. Liquid, Sludge, and Solid). 

**Describe the solution you'd like**
I would like all Manure Module variables/objects that represent a manure or manure nutrient mass to have an attribute that describes the manure type. The options are solid, liquid, or sludge. Here is a proposed diagram of how to determine which flows are liquid and which are solid. [](https://whimsical.com/manure-types-QVJzydxcscA7yotE1JHqRk)

In the ManureNutrient class only aggregate mass and nutrients from manure that has the same manure type. 

**Describe alternatives you've considered**

An alternative is to keep manure separated by pen but this does not resolve the problems that would occur when there is solid liquid separation. 

**Additional context**

The next step will be to add a manure type attribute to the Soil and Crop module request to the manure-field connector.

**Comment by ew3361zh** [comment]
@KFosterReed it looks like there may be a missing link to the proposed diagram of how to determine which flows are liquid and which are solid. Can you share that here?

**Comment by KFosterReed** [comment]
Ooops! Here is the link: [https://whimsical.com/manure-field-connector-option-2-5MMBhR7TbSpJ3p93Ly1Q77](url)

**Comment by ew3361zh** [comment]
@KFosterReed Can you explain the different pools of manure that are currently represented in the model - solid, liquid, sludge, slurry? 

I see some more recent references to sludge but it looks like in issue #1044 that we are considering liquid and slurry to be treated the same (does this mean slurry doesn't need to be tracked separately anywhere?). Should references to Slurry be replaced with Sludge or are there new equations that need to be inserted to calculate Sludge?

Thank you, I haven't spent much time at all in the Manure Module and am trying to get up to speed on the state of things before being able to properly address these issues. I'd be happy to meet if it would be easier than discussing here.

**Comment by KFosterReed** [comment]
> @KFosterReed Can you explain the different pools of manure that are currently represented in the model - solid, liquid, sludge, slurry?
> 
> I see some more recent references to sludge but it looks like in issue #1044 that we are considering liquid and slurry to be treated the same (does this mean slurry doesn't need to be tracked separately anywhere?). Should references to Slurry be replaced with Sludge or are there new equations that need to be inserted to calculate Sludge?
> 
> Thank you, I haven't spent much time at all in the Manure Module and am trying to get up to speed on the state of things before being able to properly address these issues. I'd be happy to meet if it would be easier than discussing here.

Hi @ew3361zh! You are correct, we will not be tracking slurry and liquid manure separately. The only meaningful distinction is the %solids (aka the water content of the manure) and we are already tracking that composition value directly. Sludge is different from slurry and liquid in that it is what accumulates at the bottom of long term manure storage facilities. Sometimes is is re-mixed into the liquid/slurry manure before application, sometimes not. Right now we have a sludge stream being generated during some of the manure treatment options (e.g. slurry storage outdoor, anaerobic lagoon) but our plan is to set those accumulation parameters to 0 so that the sludge generation remains 0. In the future we will add specific management practices to account for this manure pool. 

I hope this helps!

**Comment by ew3361zh** [comment]
@KFosterReed Thank you, that is helpful.
I'm not seeing that a sludge stream is being generated though. Right now it looks like the ManureType class has only LIQUID, SLURRY, and SOLID and that each of these is mapped to a specific ManureTreatmentType. Slurry Storage Outdoor is mapped to SLURRY, Anaerobic Lagoon is mapped to LIQUID. Should these be changed? Or is this not an important change to be addressing because Sludge generation is going to be 0 anyways?

This is the current mapping in manure_manager.py:
ManureTreatmentType.SLURRY_STORAGE_OUTDOOR: ManureType.SLURRY,
            ManureTreatmentType.SLURRY_STORAGE_UNDERFLOOR: ManureType.SLURRY,
            ManureTreatmentType.ANAEROBIC_LAGOON: ManureType.LIQUID,
            ManureTreatmentType.ANAEROBIC_DIGESTION_AND_LAGOON: ManureType.LIQUID,
            ManureTreatmentType.ANAEROBIC_DIGESTION: ManureType.LIQUID,
            ManureTreatmentType.ANAEROBIC_DIGESTION_AND_LAGOON_WITH_SPLIT: ManureType.LIQUID,
            ManureTreatmentType.COMPOST_BEDDED_PACK_BARN: ManureType.SOLID,
            ManureTreatmentType.OPEN_LOTS: ManureType.SOLID,

**Comment by KFosterReed** [comment]
Thanks for sharing the ManureType attributes! This is very helpful to know. A first step would be to change the slurry treatments to have a ManureType of LIQUID instead of SLURRY. 

What is happening for the sludge production is the same thing that is happening for the solids that are removed during solid liquid separation. Essentially they are removed from the mass of manure being tracked in the treatment train and then nothing else happens to them. 

One idea for a 'quick fix' would be to make a new ManureTreatmentType called SEPARATED_SOLIDS_STORAGE. The ManureType for this would be SOLID and currently, it would not do anything - it would not have any emissions or changes to the composition.

Does that seem doable?

**Comment by ew3361zh** [comment]
Sure, that seems doable. 
Do we need a SLUDGE ManureType added in?
And should I remove the SLURRY ManureType?

**Comment by KFosterReed** [comment]
Yes, please remove the SLURRY ManureType. For now, we do not need a SLUDGE manure type. I think we will have one in the future but until we have a specific method for storing and applying sludge we will treat it the same as solid manure.
