### ISSUE TITLE
Heifer2 repro refactor

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1052]
#877 did not fully refactor the reproduction for HeiferII. Only the input data and the corresponding metadata are restructured, but the `HeiferII` class is not updated to reflect the change:
`HeiferII` class is still expecting `'tai_method_h'` and `'synch_ed_method_h'` values (along with other properties) upon initialization (in both `HeiferII.init_values()` and `HeiferII.assign_heiferII_values()` functions, which is being called in `HeiferII.__init()`):
```python
    def init_values(self, args):
        """
        Initialize repro program values
        """
        self.repro_program = args["repro_program"]

        # Estrus variables
        self.estrus_count = 0
        self.estrus_day = 0

        # TAI variables
        self.tai_method_h = args["tai_method_h"]
        self.tai_program_start_day_h = 0

        # synch_ED variables
        self.synch_ed_method_h = args["synch_ed_method_h"]
        self.synch_ed_program_start_day_h = 0
        self.synch_ed_estrus_day = 0
        self.synch_ed_stop_day = 0

        self.conception_rate = 0
        self.ai_day = 0
        self.abortion_day = 0
        self.days_in_preg = 0
        self.preg = False

        self.gestation_length = 0
        self.p_gest_for_calf = 0
        self.calf_birth_weight = 0
        self._hormone_schedule = None
        self._TAI_conception_rate = 0.0

    def assign_heiferII_values(self, args):
        """
        Assign the repro program with given values
        """
        self.repro_program = args["repro_program"]

        # Estrus variables
        self.estrus_count = args["estrus_count"]
        self.estrus_day = args["estrus_day"]

        # TAI variables
        self.tai_method_h = args["tai_method_h"]
        self.tai_program_start_day_h = args["tai_program_start_day_h"]

        # synch_ED variables
        self.synch_ed_method_h = args["synch_ed_method_h"]
        self.synch_ed_program_start_day_h = args["synch_ed_program_start_day_h"]
        self.synch_ed_estrus_day = args["synch_ed_estrus_day"]
        self.synch_ed_stop_day = args["synch_ed_stop_day"]

        self.conception_rate = args["conception_rate"]
        self.ai_day = args["ai_day"]
        self.abortion_day = args["abortion_day"]
        self.days_in_preg = args["days_in_preg"]
        self.gestation_length = args["gestation_length"]
        self.p_gest_for_calf = args["p_gest_for_calf"]
        self.calf_birth_weight = args["calf_birth_weight"]
```

Also, these values still exist in `HeiferII.get_heiferII_values()`. This function is referenced when saving the animal population into `animal_population.json`. This means that all these values are also saved in the animal population JSON input, which would make its way back into the simulation when imported. To fully remove these, the metadata for animal population should also be updated.
```python
    def get_heiferII_values(self):
        """
        Get current information from the heiferII
        """
        values = {
            "id": self.id,
            "breed": self.breed,
            "birth_date": self.birth_date,
            "days_born": self.days_born,
            "birth_weight": self.birth_weight,
            "body_weight": self.body_weight,
            "wean_weight": self.wean_weight,
            "events": str(self.events),
            "repro_program": self.repro_program,
            "tai_method_h": self.tai_method_h,
            "synch_ed_method_h": self.synch_ed_method_h,
            "mature_body_weight": self.mature_body_weight,
            "estrus_count": self.estrus_count,
            "estrus_day": self.estrus_day,
            "tai_program_start_day_h": self.tai_program_start_day,
            "synch_ed_program_start_day_h": self.synch_ed_program_start_day_h,
            "synch_ed_estrus_day": self.synch_ed_estrus_day,
            "synch_ed_stop_day": self.synch_ed_stop_day,
            "conception_rate": self.conception_rate,
            "ai_day": self.ai_day,
            "abortion_day": self.abortion_day,
            "days_in_preg": self.days_in_preg,
            "gestation_length": self.gestation_length,
            "p_gest_for_calf": self.p_gest_for_calf,
            "calf_birth_weight": self.calf_birth_weight,
        }
        return values
```

However, I don't believe that combining the previous `heifer_TAI_protocol` and `heifer_synchED_protocol` into a single `repro_sub_protocol` is a good practice, this would make it impossible for InputManager to properly validate the data:

There's no way for the InputManager to make sure that `repro_sub_protocol` is only restricted to `'5dCG2P'` or `'5dCGP'` but not `'2P'`, `'CP'`, or `'N/A'` when `heifer_repro_method` is set to `'TAI'`.

I tried setting `heifer_repro_method='SynchED'` and `repro_sub_protocol='5dCG2P'`. No warnings or errors were logged. The simulation runs without complaining about anything, and it completes with the incorrect information in the system.

If you leave the `repro_sub_protocol` blank, the InputManager will use the default to auto-fix the value to `'5dCG2P'`, despite what `heifer_repro_method` is.

Doing this would defeat the sole purpose of having an InputManager in the first place. I would suggest sticking with the old structure as of now, until the cross-validation functionality is implemented in InputManager.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by allisterakun** [comment]
https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description

https://en.wikipedia.org/wiki/Database_normalization

**Comment by Isgotkowitz** [comment]
Possible solution (for the repro method and sub-method specification issue):

Previous state:
There are three inputs
1. Repro method (either TAI or synchED)
2. TAI sub-method (5dCG2P or 5dCGP)
3. synchED sub-method (2P, CP, or N/A)

If TAI is selected then only input 2 is utilized, and if synchED is passed then only input 3 is utilized.

Current state:
There are two inputs:
1. Repro method (either TAI or synchED)
2. Repro sub-method (5dCG2P, 5dCGP, 2P, CP, or N/A)

This is not currently possible to correctly validate these inputs with the Input Manager, as described above.

Proposed solution:
Have only a single input, which combines the repro method and submethod:
1. Repro method (options are TAI-5dCG2P, TAI-5dCGP, synchED-2P, synchED-CP, synchED-N/A)

I am not familiar enough with the subject matter and code structure to know how robust an option this would be.

@allisterakun can you please look this through to make sure the information is correct, and if you have any thoughts on the proposed solution please leave them here?

**Comment by allisterakun** [comment]
> Possible solution (for the repro method and sub-method specification issue):
> 
> Previous state: There are three inputs
> 
> 1. Repro method (either TAI or synchED)
> 2. TAI sub-method (5dCG2P or 5dCGP)
> 3. synchED sub-method (2P, CP, or N/A)
> 
> If TAI is selected then only input 2 is utilized, and if synchED is passed then only input 3 is utilized.
> 
> Current state: There are two inputs:
> 
> 1. Repro method (either TAI or synchED)
> 2. Repro sub-method (5dCG2P, 5dCGP, 2P, CP, or N/A)
> 
> This is not currently possible to correctly validate these inputs with the Input Manager, as described above.
> 
> Proposed solution: Have only a single input, which combines the repro method and submethod:
> 
> 1. Repro method (options are TAI-5dCG2P, TAI-5dCGP, synchED-2P, synchED-CP, synchED-N/A)
> 
> I am not familiar enough with the subject matter and code structure to know how robust an option this would be.
> 
> @allisterakun can you please look this through to make sure the information is correct, and if you have any thoughts on the proposed solution please leave them here?

Looks great! Thank you Ed!

**Comment by allisterakun** [comment]
Blocked by IM cross-validation implementation.

**Comment by jadamchick** [comment]
Hi there,
I've just started looking at PR #1477 which led me here. A quick comment related to the discussion on repro protocols in the meeting last night: there are actually **three** repro method options for heifers: ED, TAI, or SynchED. And as Kaitlyn pointed out, ED is far and away the most common. ED does not need a sub-method (I have "N/A" in for most of the pilot herds). 

I'll keep this in mind while reviewing 1477 and also mention it there if it seems relevant.

**Comment by krb78** [comment]
Ok, I'm butting in here, and will probably just make things worse, not better... while I understand the desire to make things restrictive from an input standpoint in order to validate the inputs, the reality of heifer repro programs is they are often some combination of things (far and above ED, but some farms do a combination and others have sort of created their own weird programs as well). 

I like Ed's idea of coding what type of protocol it is into the name except I think we need to update the last one to be "ED-N/A" (see as follows: TAI-5dCG2P, TAI-5dCGP, synchED-2P, synchED-CP, ED-N/A). I think that in our documentation or input we can explain that these are structured REPRO METHOD - SPECIFIC PROTOCOL.

**Comment by allisterakun** [comment]
This will be taken care of in issue #1997
