### ISSUE TITLE
Expand capabilities for adding data to pool

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1060]
**Is your feature request related to a problem? Please describe.**
Currently the methods for adding data to pool are only capable of adding data that can be validated against "full" properties (`"animal_properties"`, `"field_properties"`, etc.).

**Describe the solution you'd like**
A method that allows data to be added to pool that can replace data which is located inside of a more complex data structure in the pool.

**Describe alternatives you've considered**

**Additional context**
There are already two methods for adding data to the Input Manager at run time, `add_dict_variable_to_pool()` and `add_tabular_variable_to_pool()` (in Input Manager). They rely on the hidden methods `_add_variable_to_pool()` and `_metadata_properties_exists()`. It may be possible to expand/refactor these methods to address this feature.

**Comment by allisterakun** [comment]
Explore the need to modify the metadata structure -> create another issue. Maybe there is a dependency that we don't know yet.
