### ISSUE TITLE
Manure Total Ammoniacal N conversions and use of variables are incorrect

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1066]
## Expected Behavior
There are several inconsistencies in the manure nitrogen and ammonia N tracking. These calculations should use values of manure composition provided by the animal module and track the total mass of manure N, manure ammoniacal N, and ammonia N at each step along the way. Manure ammoniacal N is a subset of total manure N and ammonia N emissions are generated from manure ammoniacal N. 

## Current Behavior

1. The `PenManure` class does not divide `animal_manure["total_ammoniacal_nitrogen_concentration"]` by the number of animals in the pen to get the average total ammoniacal concentration before multiplying by the volume to get the mass of total ammoniacal nitrogen to create the `manure_total_ammoniacal_nitrogen` attribute. It also creates a separate `urine_total_ammoniacal_nitrogen` attribute that is used by the `housing_ammonia_emission` function in calculator.py however the `urine_total_ammoniacal_nitrogen` should not be needed or used.
2. Slurry and solid manure densities are incorrect
3. Ammonia emissions are not being adjusted for N content before removal from total ammoniacal N variables and are not being subtracted from total manure N at all
4. The method for estimating ammonia emissions from manure storage/treatment does not use the correct value as an input for the total ammoniacal N. 
- Update to point 4 above: I have confirmed that several of the Manure Treatment methods are using different total ammoniacal nitrogen values as the inputs to estimate ammonia emissions. This has also led me to understand that the different methods are also calculating the accumulated_total_ammoniacal_nitrogen slightly differently. A couple of things to change for consistency: 

- [ ] Each manure treatment method has a `'daily_update_helper` function. Within this function, the following operations should be conducted in this order: 1) `accumulate_daily_output`, 2) all emissions estimates (methane, then ammonia, then nitrous oxide), 3) the accumulated outputs for liquid_manure_total_ammoniacal_nitrogen, liquid_manure_total_solids, storage_methane, storage_ammonia, and storage_nitrous_oxide should be updated. 
- [ ] the inputs to the ammonia emissions estimation methods in all manure treatment methods should be the accumulated_output.liquid_manure_total_ammoniacal_nitrogen values. 

We will need to change the naming conventions somepoint soon because currently all nitrogen outputs from the manure handler are called liquid_manure_nitrogen or liquid_manure_total_ammoniacal_nitrogen leaving no room for non liquid nitrogen but I think we can update that later. I will create a google doc to share that describes the updated calculations for the ammonia emissions inputs and accumulated manure values in more detail. 

## Possible Solution

- [ ] Divide `animal_manure["total_ammoniacal_nitrogen_concentration"]` by `num_animals` [here](https://github.com/RuminantFarmSystems/MASM/blob/814258e2bec0d026d0c3c58b15b1b0daa46ace84/RUFAS/routines/manure/pen_manure/pen_manure.py#L111)
- [ ] Update `housing_ammonia_emission()` so that it uses `manure_total_ammoniacal_nitrogen` instead of  `urine_total_ammoniacal_nitrogen`
- [ ] In the manure_constants.py file update the manure densities to the following: 
    - [ ] LIQUID_MANURE_DENSITY = 1000
    - [ ]  SLURRY_MANURE_DENSITY = 990
    - [ ] SOLID_MANURE_DENSITY = 700
- [ ] More to come for 3&4

## Steps to Reproduce

1.
6.
7.
8.

## Possible Implementation

I have started a draft PR ([1065](https://github.com/RuminantFarmSystems/MASM/pull/1065)) for my debugging and testing purposes

**Comment by KFosterReed** [comment]
@ew3361zh I created a more detailed description of the changes I would like to see for the daily update function for the Manure treatment methods. After learning more about the ammonia emissions estimates for the different treatment types, I am less sure that they should all be using the same input value so I am working to clarify that. In the meantime, hopefully you can get started on the first task? 

Here is the link: [https://docs.google.com/document/d/1jF62faHDByADKJ0oCs_E0vV3kuHJEYlzLWH3PQUFyZU/edit?usp=sharing](url)

Please let me know if you have any questions!

**Comment by tomhuhh** [comment]
Hello @ew3361zh! Would love to hear your thoughts on if this issue can be added to the Fixathon task list? If so, could you please provide an estimated workload (in hours) to have it finished? 

Thanks!

**Comment by ew3361zh** [comment]
Linking [this google doc](https://docs.google.com/document/d/1F-_Uh2nj56hPd7xDbesG8YWXKwWg0Al9jBFRhUNMNh8/edit) here with further discussion and questions on this issue between myself and Kristan. There are a handful of items listed in here that are still to-be-determined as far as how they should be implemented including:
-Do the calculator.py ammonia and methane emission calculation functions that incorporate efficiencies need to be adjusted?
-Does SlurryStorageOutdoor need to have an adjustment incorporated for precipitation similar to what happens with AnaerobicLagoon?
-Review of AnaerobicDigestion to ensure daily output can be added to the accumulated output right away or if further processing should happen first (e.g. the calc_anaerobic_digestion_output() adjustments)?
-For AnaerobicLagoon whether the emissions calculation functions use the same inputs as some of the other methods?
