### ISSUE TITLE
Remove simulate_animals from metadata

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1068]
In PR 878 we removed Animal DB and updated how herd initialization works. After that change, we no longer use `simulate_animals` in the config file; however, it is still present in the input files and in the metadata. Fix this issue by removing the following section from the metadata and corresponding data from input files.
```
"simulate_animals": {
        "type": "bool",
        "description": "Whether or not to simulate animals during the simulation",
        "default": true
      }
```

**Comment by allisterakun** [comment]
After some digging following @Isgotkowitz's comment in PR #1083, I found that `simulate_animals` still serves a purpose in the codebase. I am closing this issue without any changes.
