### ISSUE TITLE
Redundant cows repro section in animal input JSON

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1086]
In PR [#877: Heifer2 repro refactor ](https://github.com/RuminantFarmSystems/MASM/pull/877), the repro configs for cow at `animal.animal_config.farm_level.repro.cow_repro_programs` was refactored to `animal.animal_config.farm_level.repro.cows`. 

However, the old version `animal.animal_config.farm_level.repro.cow_repro_programs` was not removed, so currently both versions co-exist in all metadata and animal input JSON files.

```json
...
  "repro": {
          ...
          "heifers": {
           ...
          },
          "cows": {
            "estrus_detection_rate": 0.6,
            "estrus_conception_rate": 0.6,
            "presynch_protocol": "Double OvSynch",
            "resynch_protocol": "TAIafterPD",
            "repro_sub_protocol": "OvSynch 56",
            "repro_sub_properties": {
              "conception_rate": 0.5,
              "tai_program_start_day": 70
            }
          },
          "cow_repro_programs": {
            "estrus_detection_rate": 0.6,
            "estrus_service_rate": 1,
            "ed_conception_rate": 0.6,
            "cow_presynch_protocol": "Double OvSynch",
            "cow_TAI_protocol": "OvSynch 56",
            "ovsynch56_conception_rate": 0.6,
            "ovsynch48_conception_rate": 0.6,
            "cosynch72_conception_rate": 0.6,
            "cosynch5d_conception_rate": 0.6,
            "cow_resynch_protocol": "TAIafterPD",
            "tai_program_start_day": 72
          }
  },
```
## Expected Behavior

Delete the old version `animal.animal_config.farm_level.repro.cow_repro_programs` from all metadata and animal input JSON files.
## Current Behavior

The old `animal.animal_config.farm_level.repro.cow_repro_programs` and the new `animal.animal_config.farm_level.repro.cows` both exist in all metadata and animal input JSON files at the same time.
## Possible Solution

Remove the old version `animal.animal_config.farm_level.repro.cow_repro_programs` from all metadata and animal input JSON files.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomhuhh** [comment]
I believe @ltp23 has applied a fix to this in this cow repro refactoring branch `repro-refactor-pr2.`

**Comment by allisterakun** [comment]
#1055
