### ISSUE TITLE
Determine if "example_manure_management.json" file is needed.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1090]
The input file "example_manure_management.json" file in the input > data > manure folder may be unnecessary and can be removed. 

I believe I created it when we initially were looking at a different format for the manure management scenarios input files but the model wasn't set up to handle that format and it caused more problems than it solved.

I don't know if we're still looking at setting up the input files in a different way and if this file is useful to anyone to that end (or for any other reason).

Determine if this file is needed for any reason by anyone and if it needs to be in the codebase. If not, remove it.

**Comment by allisterakun** [comment]
Confirm with the Subject Matter Experts about this file.

**Comment by KFosterReed** [comment]
Unless @ltp23 has a reason to keep it, let's delete it

**Comment by ew3361zh** [comment]
Spoke with Loi, he said the file is not needed by him. I will remove it.
