### ISSUE TITLE
`Time` should be single-source of truth for tracking and measuring time in RuFaS

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1099]
There are multiple places in the code where time is kept/tracked/utilized in various forms. This is problematic as it makes the code non-standard and bug prone. All time-related uses should use the `Time` object.

## Expected Behavior

All cases where time needs to be managed or tracked should utilize the `Time` class.

## Current Behavior

Time is tracked and passed around in multiple different forms. For example, instead of passing a `Time` instance to demonstrate what the time is, two ints are used - one representing the ordinal day and the other the calendar year.

## Possible Solution

After refactoring the `Time` class, comb the codebase to look for places where time is being represented in a form that is not a `Time` instance, and change it to use `Time`.

**Comment by allisterakun** [comment]
`Time` will probably need to be a singleton to enforce that different modules are all on the same page.

**Comment by ew3361zh** [comment]
If desired, re-incorporate a simulation progress bar while working on this task.

**Comment by ew3361zh** [comment]
Investigate this issue and create child issues to break this up and solve this issue.

**Comment by ew3361zh** [comment]
Wrote up 2 issues to break this down a little further into more tangible steps: #1522 and #1533. I added some initial estimated T-shirt sizes to those but those can be debated at an upcoming grooming session.
