### ISSUE TITLE
Option to separate manure before anaerobic digestion and anaerobic lagoon

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1103]
**Is your feature request related to a problem? Please describe.**
Currently there is a manure treatment option called anaerobic_digestion_and_lagoon which allows the user to specify that they send manure to anaerobic digestion and then after the digestion is finished, it goes into an anaerobic lagoon. If a manure separator is specified, the separation will occur between the digestor and the lagoon. We need to be able to have an option to have manure separation before the digestion AND after the digestion/before the lagoon

**Describe the solution you'd like**
I would like another input to be added so that the user can specify multiple separators if needed and to have the inputs to the anaerobic_digestion_and_lagoon treatment type to have the option to come directly from the reception pit or from the manure separator. 

**Describe alternatives you've considered**
One alternative is to have the input for the 1st separation to be a boolean input and to have only one fixed option for the type of separation before digestion in the compound treatment case.
**Additional context**

**Comment by KFosterReed** [comment]
Based on our discussion yesterday, we will add another input to the manure_management_scenarios input section called `manure_separator_after_digestion`. 

Also, here is a diagram to illustrate the combination of separators and treatments we want to achieve: 
[https://docs.google.com/presentation/d/1IqfqAzA7maSUrXhNIRGnNgODAlvoMYlRClRcwMh1Sfw/edit?usp=sharing](url)

![Manure separation diagram (1)](https://github.com/RuminantFarmSystems/MASM/assets/41019131/9d129191-c814-415a-ab9f-ae98f6cf5607)

**Comment by ew3361zh** [comment]
For the new option (4), should we assume that it's the same type of separator in each instance or that there could potentially be 2 different separator types (e.g. Rotary Screen for the first and Screw Press for the second)?

**Comment by KFosterReed** [comment]
It could be the same or a different type of separator! (Each farm is a special unique snowflake! Haha :) ) so I think having a separate input for `manure_separator_after_digestion` is the way to go!

**Comment by ew3361zh** [comment]
For the scenarios we have currently, can you tell me which ones (if any) have the separator after digestion? I will need to update those accordingly.

These are the current scenarios for reference:

```
"manure_management_scenarios": [
    {
      "scenario_id": 0,
      "bedding_type": "sawdust",
      "manure_handler": "manual scraping",
      "manure_separator": "none",
      "manure_treatment": "anaerobic lagoon"
    },
    {
      "scenario_id": 1,
      "bedding_type": "sawdust",
      "manure_handler": "manual scraping",
      "manure_separator": "none",
      "manure_treatment": "slurry storage outdoor"
    },
    {
      "scenario_id": 2,
      "bedding_type": "sawdust",
      "manure_handler": "manual scraping",
      "manure_separator": "screw press",
      "manure_treatment": "slurry storage outdoor"
    },
    {
      "scenario_id": 3,
      "bedding_type": "sawdust",
      "manure_handler": "flush system",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },
    {
      "scenario_id": 4,
      "bedding_type": "sand",
      "manure_handler": "flush system",
      "manure_separator": "none",
      "manure_treatment": "anaerobic lagoon"
    },
    {
      "scenario_id": 5,
      "bedding_type": "sawdust",
      "manure_handler": "manual scraping",
      "manure_separator": "none",
      "manure_treatment": "anaerobic digestion and lagoon"
    },
    {
      "scenario_id": 6,
      "bedding_type": "sawdust",
      "manure_handler": "flush system",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic digestion and lagoon"
    },
    {
      "scenario_id": 7,
      "bedding_type": "sawdust",
      "manure_handler": "flush system",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic digestion and lagoon with separator"
    },
    {
      "scenario_id": 8,
      "bedding_type": "CBPB sawdust",
      "manure_handler": "tillage",
      "manure_separator": "none",
      "manure_treatment": "compost bedded pack barn"
    },
    {
      "scenario_id": 9,
      "bedding_type": "none",
      "manure_handler": "harrowing",
      "manure_separator": "none",
      "manure_treatment": "open lots"
    },
    {
      "scenario_id": 10,
      "bedding_type": "none",
      "manure_handler": "flush system",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic digestion and lagoon with two separators"
    }
  ]
```

**Comment by KFosterReed** [comment]
Hi Niko! I think we would like scenario 7 and 10 to have separators after digestion and before the lagoon. Is it possible to use the same treatment name for both of these instead of creating a new treatment? In the diagram above, I tried to communicate this but we were thinking the treatment options would be `anaerobic digestion and lagoon` or `anaerobic digestion and lagoon with separator` where the 'with separator' part would indicate a separator between the digestion and lagoon.

A separator provided by the 'normal' manure separator input would automatically indicate separation before any manure treatment begins, whereas the new separator input ('manure separator after digestion'?) would only be used for the treatment type `anaerobic digestion and lagoon with separator`. Of course, there my be a really good reason to not do it this way so feel free to suggest a different way!

**Comment by ew3361zh** [comment]
Ok, I think this makes sense. But just to be clear: is the idea that scenario 7 would represent `digestion - SLS - lagoon` and then scenario 10 would be `SLS - digestion - SLS - lagoon`? 

I'm will try to figure out if it will work to name them the same treatement (i.e. both `anaerobic digestion and lagoon with separator").

**Comment by KFosterReed** [comment]
> Ok, I think this makes sense. But just to be clear: is the idea that scenario 7 would represent `digestion - SLS - lagoon` and then scenario 10 would be `SLS - digestion - SLS - lagoon`?
> 
> I'm will try to figure out if it will work to name them the same treatement (i.e. both `anaerobic digestion and lagoon with separator").

Yes! That is correct :)
