### ISSUE TITLE
Revisit design of __init__ methods in C&S

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1104]
When classes in the Crop and Soil module are initialized, many of their parameters are declared `Optional`, which means that they are the __init__ routines are set up to handle parameters that are sometimes not present. This design has benefits and drawbacks, and should be revisited to evaluate if it is really the best way to be initializing classes in the context of RuFaS.

## Desired Behavior

Either have classes in C&S fail if they are not provided critical parameters when initialized, or make it clearer that a class is creating its own critical data during initialization because it was not provided the critical data by the caller.

## Current Behavior

Many init routines look something like the following (this example is pulled from `biomass_allocation.py`:
```python
def __init__(self, crop_data: Optional[CropData] = None):
    self.data = crop_data or CropData()  # initialize with defaults, if not given
```
This makes critical information optional, which provides more flexibility in how individual classes can be used (it also makes testing a little more streamlined).

## Possible Solution(s)

- Make critical data non-optional in all constructors.
- Raise warnings to the Output Manager if a caller does not provide critical data to an init method.

## Context (Environment)

There are some problematic init methods that have results from the use of the above design pattern. For example:

In init methods for classes in the `soil/` subpackage, they are structured like the following:
```python
def __init__(self, soil_data: Optional[SoilData], field_size: Optional[float] = None):
    self.data = soil_data or SoilData(field_size=field_size)
```
If `soil_data` is a SoilData instance but `field_size` is None the init routine will run fine, and vice versa. However, if both `soil_data` and `field_size` are None, the init method will crash because an error will be raised when trying to init `SoilData`. This behavior is not obvious and may result in someone having to spend a lot of time trying to figure out why init keeps crashing or why the `data` in this class isn't linked to the `data` in other soil classes (as it is expected to be).

Another example is the `Field` constructor. All of its arguments are declared `Optional` with a default of None, but they have different behavior and requirements which makes it harder to understand how `Field`s should be initialized properly. If `tillage_events` is None that is fine - the Field just sets `self.tillage_events` to an empty list which is perfectly valid. But it would be better to make the default an empty list because this actually what the default is, so the code in init could be simplified and the method signature would clearly indicate how it actually works. The behavior of `tillage_events` sharply contrasts what the behavior of `manure_manager` and `feed_manager` are. Having actual `ManureManager` and `FeedManager` instances passed to `Field`s are essential for them running properly in a full RuFaS simulation, but both are `Optional` arguments with a default of None. In addition, they have different behavior - if the argument for `manure_manager` is None, init raises an error, but if `feed_manager` is None the init method will initialize a new `FeedManager`. The behavior associated with these two arguments should be made consistent.

**Comment by ew3361zh** [comment]
Deeper investigation of the underlying design is needed to decide on this.

**Comment by allisterakun** [comment]
This can be folded into issue #1236

**Comment by allisterakun** [comment]
Closing this issue with completing issue #1236, the follow-up issue is #1816.
