### ISSUE TITLE
Examine why negative manure values are being generated from animal module and raise an exception.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1123]
In MASM > RUFAS > routines > manure > pen_manure > pen_manure.py the `post_init` function for the PenManure class uses the manure_mass passed from the animal module to calculate manure volume. Currently the function zeros out any negative values found in the fields but a better solution would be to raise an exception for any negative value found and to determine why that negative value is occurring (there should never be negative manure generated by the animal module).

Look at the post_init function in the PenManure class and set it up to raise exceptions for any negative values found.

From there I would likely create an issue for each value found to be negative in this situation.

Because we want the simulation to run while this is being figured out, I think it would be best to reset the post_init function's capacity of zeroing out all negative fields found and update this issue with a note to reactivate each of the exceptions once the root cause of the negative values is discovered.

**Comment by tomhuhh** [comment]
This is an existing issue #609 and is addressed in PR #1133. We should be safe to delete this issue.

**Comment by ew3361zh** [comment]
Duplicate issue.
