### ISSUE TITLE
IM.get_data() log

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1126]
## Expected Behavior

Keep a log of all the calls for `InputManager.get_data()`
## Current Behavior

No log
## Possible Solution

Create a pool in IM or OM to keep track of all the calls to get data

**Comment by ew3361zh** [comment]
This is not calling add_log() from OM. This is a separate group of logs maintained in IM. This will help prevent overwhelming OM's logs.
