### ISSUE TITLE
Set a team-standard formatter for use in the RuFaS development workflow

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1130]
**Is your feature request related to a problem? Please describe.**
It is common for different programmers to have different formatting preferences when coding. This can become as issue when working on a team though, because differences in formatting choices can result in non-uniform code. Non-uniform code can cause unnecessary headaches or be a distraction when reading or reviewing code.

**Describe the solution you'd like**
The team agrees on a way to standardize the formatting of RuFaS in a way that uses an automated tool. This tool will need to be easy to use and to adopt into workflows. Ideally, this formatter leaves as little room as possible for variations in coding style, and can be automatically applied to code that is submitted in PRs.

The [Black](https://black.readthedocs.io/en/stable/) formatter is a strong candidate for an autoformatter. It is widely used, and has good integrations with different IDEs as well as GitHub Actions. It is very aggressive, but is configurable enough that it can be made to play nice with Flake8.

**Describe alternatives you've considered**
There are many other autoformatters out there. Other commonly used ones are yapf and autopep8. All have their pros and cons.

An alternative to using an autoformatter would be to define a RuFaS-specific formatting standard and put the burden of formatting code correctly onto the people writing the code. This is, in my opinion, a bad option. It will result in people spending a lot more time fixating on formatting instead of scrutinizing the code and what it needs.

**Additional context**

**Comment by ew3361zh** [comment]
Ideally once we agree on an autoformatter, we will use it once manually on the entire code based and push those changes to github as a clean slate to start from.

It should be incorporated into a github action which runs on every push to GH.

We should also coordinate our flake8 script with the use of this autoformatter.
