### ISSUE TITLE
Add 'None' option for bedding types

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1132]
**Is your feature request related to a problem? Please describe.**
We would like to add an option to not apply bedding to the pens in the Manure Management methods. 

**Describe the solution you'd like**
This would require adding adding a 'None' bedding type in the following places: 

1.  `DefaultBeddingConfigFactory` in bedding_classes.py
2. The metadata pattern options for `"bedding_type"` in the `"manure_management_scenario"` section
3. The metadata pattern options for `"bedding_type"` in the `"bedding_configs"` section
4. The manure management input json files `"bedding_configs"` section

As the name implies the values for all the configs will be 0 :)

**Describe alternatives you've considered**

**Additional context**

**Comment by PooyaHekmati** [comment]
@KFosterReed I see the urgent tag on this issue, is it urgent urgent or can we set it to high priority? Do we have a firm deadline for this?

**Comment by KFosterReed** [comment]
We need this to run the pilot testing scenarios so as soon as possible and ideally by the end of the week
