### ISSUE TITLE
Adding and Deleting Manure Metadata patterns

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1134]
## Expected Behavior
There are some missing patterns and some extra patterns in the manure management metadata. They need to be corrected to align with the options available for simulation

## Possible Solution

1. bedding_type - delete 'Other', add 'CBPB sawdust'
2. manure_handler - delete 'manual skid steer scraping'
3. "manure_separator" - delete 'other'
4. "manure_treatment_methods" - see comments in [this issue](https://github.com/RuminantFarmSystems/MASM/issues/1095)

Note that the patterns need to be changed in the "manure_management_scenarios" sections as well as the config sections. 

## Steps to Reproduce

1.
6.
7.
8.

**Comment by ew3361zh** [comment]
@KFosterReed quick clarification:

1. Is CBPB_sawdust acceptable instead of having the space there (i.e. instead of CBPB sawdust)?

**Comment by KFosterReed** [comment]
Yes!
