### ISSUE TITLE
Add animal-type label to manure handler & manure treatment daily outputs 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1138]
**Is your feature request related to a problem? Please describe.**
Because manure outputs are reported by pen, the user has to assume they know which type of animals are in each pen if they want to aggregate outputs by calves, heifers, etc. The type of animals in each pen, and how many pens there are, can change from farm to farm, and so there isn't a way for a standard report filter for these categories. 

**Describe the solution you'd like**
Add the animal class (calf, growing, close_up, lac_cow) to the name of the output variable along with the pen name. For example, this has already been implemented for the AnimalManager._calc_ration_at_interval outputs (eg: AnimalManager._calc_ration_at_interval.ration_per_animal_for_pen_2_CLOSE_UP.values: 51). This allows filtering by the animal type instead of by the pen number. 

It would be helpful for this to be implemented for all ManureHandler and ManureTreatment daily outputs, so it can be used for sorting emissions from manure during housing and storage. 

**Describe alternatives you've considered**
Filter by pen, and rely on the user to check that the pen numbers in the report filter line up with the farm's set-up. 

**Additional context**

**Comment by PooyaHekmati** [comment]
@jadamchick Can you please comment on the priority of this issue and any potential deadlines?

**Comment by jadamchick** [comment]
Yes! This is needed for our reports for the pilot farms. We specifically need to be able to calculate the footprint of calves and heifers, which requires knowing the manure footprint of each group. So priority = high, potential deadline = soon? beginning of next week? Thank you!
