### ISSUE TITLE
Delete messages printed to standard output when running simulations.

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1161]
The messages printed in the terminal need to be improved in some ways and improved in others when running RuFaS simulations.

## Current behavior
When running RuFaS simulations, the current message(s) printed to standard out look like this:
```sh
$ python main.py -i -c
RuFaS: Ruminant Farm Systems Model 2023
Simulating...
/
Simulation Successful

/
Simulation Successful

/
Simulation Successful

$
```

## Proposed Improvements
1) It's 2024 now, not 2023.
2) After a simulation finishes successfully, it does not immediately go into the next simulation, it writes all the output files first. So repeating the "Simulating..." message when a new simulation actually starts would be helpful.
3) Either get the spinning progress wheel to work or get rid of it.
4) Add the simulation prefix from the `MetadataPaths` into the "Simulating..." message.

**Comment by allisterakun** [comment]
Suggestion: remove all printed messages to stdout, report all messages to OM instead. Possibly adding a function in OM to handle all the status messages.

**Comment by Isgotkowitz** [comment]
Planning meeting: add "Simulating" and "Simulation N% Successful" messages to logs. Add simulation n% successful messages at 10%* intervals. *Just a suggestion, would be a good place to start.

Also add a verbosity for credits, when true the "RuFaS 2024" credit line is printed.

**Comment by ew3361zh** [comment]
Moving to Blocked until Pooya has merged in his PR refactoring ScenarioManager and main.py.
