### ISSUE TITLE
Improve or reomove the fat corrected milk calculation in cow's milking update

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1162]
Currently, the `daily_fat_correct_milk_production` variable in the `milking_update()` method of the Cow class doesn't seem to be used in calculations anywhere. Please double-check and remove it if we don't have plans to implement a more up-to-date equation for it.

**Comment by Isgotkowitz** [comment]
Closed as unplanned. This issue was taken care of by refactoring the MilkProduction logic as part of the Animal Refactor - #1930
