### ISSUE TITLE
Heifer daily_growth is sometimes negative

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1166]
Found in PR #1152 , as some animals were still producing unexpected negative values.

## Expected Behavior
Heifers aren't expected to lose weight.

## Current Behavior
Some values in `get_non_preg_bw_change` result in negative values.  Found in `heiferI.py`

For instance (found using the debugger), when:
 `self.mature_body_weight` is 735.203333, 
 `self.body_weight` is 457.4165980518182, 
 `AnimalBase.config["target_heifer_preg_day"]` is 420, 
and `self.days_born` is 450, 
the equation `(0.55 * 0.96 * self.mature_body_weight - 0.96 * self.body_weight) / abs(AnimalBase.config["target_heifer_preg_day"] - self.days_born)`
 results in -0.5787792534743794

###     Additional note
This method lacks a citation, pseudocode or otherwise. Seems to match [A.1A.C.6] in the Animal Life Cycle pseudocode doc.

## Possible Solution(s)
If it isn't as simple as a missing term or parentheses, additional logic may need to be added. e.g. instead of abs, if the difference is less than or equal to zero, the divisor should be 1. Alternatively, any results that are negative would be capped at 0, or some other minimum growth value.

## final additional note
This may also require similar logic changes in `get_bw_change` in `heiferII.py`

**Comment by KFosterReed** [comment]
Thanks for highlighting this! I think it likely because an animal is coming in heavier than their mature bodyweight. I believe this equation is from the NRC (2001) but we should definitely add it to the pseudocode. I'm a little unsure about the denominator and we should probably change all the magic numbers to constants. For example, I think the 0.96 is to convert bodyweight to 'empty body weight' but I am not sure off the top of my head. Great chance to improve the documentation!

We should revisit old Animal module meeting notes circa Taylor Hansen/Jinghui/Manfei times (2020-2021?)

**Comment by JoeWaddell** [comment]
Investigating this again: to go back to the equation [A.1A.C.6] (which I updated above to be more generalized, matching the code), the 0.96 term is used to convert to shrunk body weight. 
Negative growth rate happens when an animal's body_weight is over 55% of their mature body weight (due to the 0.55 term), and because of the order of operations and the subtraction in first half of  the equation. 

Looking through Fox et al. 1999 and NRC 2001 the choice of 55% comes from equation 6 (fox et al 1999) and the equation in the code (and pseudocode) matches 11-8 (NRC 2001).

Since the literature doesn't account for animals that have gone over their 55% mature body weight, I think we have a few options:
1) Use 0 as a minimum growth rate.
2) Use a magic number as the minimum growth rate (e.g. the lowest rate we see in a typical simulation, though hardcoding this may be problematic if adding other breeds with slower growth).
3) Use the relationship between body weight, mature body weight, and growth (when the results are positive) to come up with some modification to the equation.
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/00bab8e6-c5f1-4e01-ad37-09a982068e46)
