### ISSUE TITLE
Remove the default enum classes in the manure module to make use of the defaults in IM

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1170]
Most of the enum classes in the manure module are extended from the `DefaultEnum` class. The original motivation for that class was to have a default option in the case of a failed name-lookup. Now that the input manager has a way to specify the default values, we should revisit all these enum classes and see if we can integrate those user-defined default values into the manure module.

**Comment by Isgotkowitz** [comment]
@Isgotkowitz mention this issue as something that should be done once no classes are using `DefaultEnum`.

**Comment by Isgotkowitz** [comment]
Unblocked with the completion of #1524.
