### ISSUE TITLE
Add options to pen type metadata patterns

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1172]
See issue 1095 for more detail
## Expected Behavior

We would like the pen_type inputs to align with the appropriate manure management options that are dependent on the pen type. These names should be: freestall, tiestall, open lot, and compost bedded pack barn

## Current Behavior

In the animal data inputs, pen_type has the following options: freestall, tiestall, and drylot. 

## Possible Solution

Update the animal meta data for pen_type to be: 

`"pen_type": {
            "description": "Pen Type select one) -- The type of stalls the pen has",
            "type": "string",
            "pattern": "^{freestall|tiestall|open lot|compost bedded pack barn}$",
            "default": "freestall"
          },`

From what I can tell, the only place where pen_type is used in the code is in `manure_manger_pen.py`

`    barn_area_by_pen_type = {
            "tiestall": tiestall,
            "bedded pack": bedded_pack,
            "freestall": freestall,
        }

        barn_area = barn_area_by_pen_type.get(self.pen_type, default)
`
so the options would need to be updated here to align with the pen_type options in the animal module. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by KFosterReed** [comment]
@ltp23 Has there been any progress on this issue? We need these pen types updated as soon as possible for the pilot testing.

**Comment by ltp23** [comment]
Hi Kristan, I have merged a PR to resolve this issue.

**Comment by KFosterReed** [comment]
Amazing! Thank you Loi :)

**Comment by KFosterReed** [comment]
Closed with PR 1183
