### ISSUE TITLE
undefined name 'Nutrients'

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#118]
In https://github.com/RuminantFarmSystems/MASM/blob/master/RUFAS/routines/animal/new_nrc_ration_not_used/lactating_cow_ration.py#L318-L328, Nutrients is not defined. This is blocking automated pipelines from running.

**Comment by militsasotirova** [comment]
PR #110 removes these files.

**Comment by PooyaHekmati** [comment]
> PR #110 removes these files.

Please follow up with Chris to have his review.
