### ISSUE TITLE
Make Report Generator aggregate column information clearer

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1181]
From @jadamchick:

I've been using the new ability to generate report data selecting variables by regex, and it's great.

One question for you: when I want to report the data without any aggregation, it generates a report column for each variable in the dictionary and the variable name (for example: feed ID) is included in the column header. However, when I want to aggregate (for example, sum over the last year for each variable), it prints the results all in one column with no indication of the variable names.

Here are the filters I'm using (and I've already done it with individual feeds and pens to feel confident that it is selecting + aggregating the way I expect it to):

```
{
      "name": "DMI by feed, daily",
      "filters": [
        "AnimalModuleReporter.report_daily_ration.ration_daily_feed_totals.*"
      ],
      "variables": [".*"],
      "slice_start": -365
    },
    {
      "name": "DMI by feed, sum",
      "filters": [
        "AnimalModuleReporter.report_daily_ration.ration_daily_feed_totals.*"
      ],
      "variables": [".*"],
      "vertical_aggregation": "sum",
      "slice_start": -365
    },
    {
      "name": "Feed emissions by feed, daily",
      "filters": [
        "AnimalModuleReporter.report_daily_feed_emissions.*"
      ],
      "variables": [".*"],
      "slice_start": -365
    },
    {
      "name": "Feed emissions by feed, sum",
      "filters": [
        "AnimalModuleReporter.report_daily_feed_emissions.*"
      ],
      "variables": [".*"],
      "vertical_aggregation": "sum",
      "slice_start": -365
    },
```
And here are what the outputs look like for the two "sum" reports (there are 2 feeds for which we don't have emissions factors, which is why they are different lengths -- and which is part of the value of being able to summarize it like this!):
![image (3)](https://github.com/RuminantFarmSystems/MASM/assets/70217952/d7534c20-6daa-4c98-9d66-17d7e05fae95)

## Potential Solutions (1 of the 3):
Option 3 sounds like it's the most preferable.
1. Print a neighboring column that lists the variable names, one in each row
2. Include all of the variable names in the column header of the aggregated data?
3. Have the aggregated values to each print in their own column, with that feed ID (variable name) included in the column header.

**Comment by KFosterReed** [comment]
@ltp23 Also checking in on how this new report function is coming along?
