### ISSUE TITLE
Create "kg of byproducts fed" report item 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1187]
**Is your feature request related to a problem? Please describe.**
One output that FARM ES would like reported for the pilot farm is "Total kg (DM) of byproducts fed", according to the list of feeds (attached below) considered as byproducts.  It would be great to be able to automate this calculation as part of RuFaS outputs/report generation. 

**Describe the solution you'd like**
Something along the lines of: 
1. Indicated feeds have some label as "byproducts" 
2. Be able to filter and sum total quantity of "byproduct" feeds fed using report generator 

**Describe alternatives you've considered**
Manually identify which feeds are byproducts + do post hoc math to sum the quantity used. 

**Additional context**
Issue #1181 addresses how feed quantity use is reported, aggregated, and labeled. 

This spreadsheet contains all feeds to be designated as byproducts; currently rations are only utilizing feeds listed in the combined NRC and NASEM feed library. 
The regional byproduct blend is not included on this list, but should be added (ID's 302-305). 

[KB_Copy of User_feeds_byproducts_.xlsx](https://github.com/RuminantFarmSystems/MASM/files/14112699/KB_Copy.of.User_feeds_byproducts_.xlsx)

**Comment by KFosterReed** [comment]
Hey Team, I'm not sure who is the best person to take this on but looks like it could be combined with issue 1181? It would require a modification to some of the values in the feed type column of the feed library as well

**Comment by JoeWaddell** [comment]
Great, I'll meet with Loi today to sort it out, and may hop in on the work together session to see what the dev team will need from me to advance #1181.

**Comment by KFosterReed** [comment]
Thanks Joe!

**Comment by jadamchick** [comment]
Hey all, I made a PR with a draft of this last night and tagged Joe to review. I’ll be online later this morning and make sure it’s linked here. Thanks!

Sent from my iPhone

On Feb 6, 2024, at 08:44, Kristan ***@***.***> wrote:

﻿

Thanks Joe!
