### ISSUE TITLE
Estimate requirements for Non-Essential Aminoacids (NEAA)

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1210]
Following suggestion by @Ed731551, `calculate_NASEM_protein_requirements` would be enhanced if we could add requirement equations for non-essential amino acids. Further detail needs to be added here from a nutritionist, but the relevant reference will be the NASEM (2021) book.

**Comment by ew3361zh** [comment]
From Grooming session:
@KFosterReed can you confirm we don't currently have plans to implement this?

**Comment by KFosterReed** [comment]
confirmed! No immediate plans - this falls into the low priority for now :)

**Comment by matthew7838** [comment]
@KFosterReed Do we have short/midterm plan for this issue? or should we close the issue as not planned?

**Comment by KFosterReed** [comment]
I think we can close it for now and re-open when interests and resources align.
