### ISSUE TITLE
Feed#135 in NRC_comp.csv does not match feed #135 in NASEM_Comp_with_TDN.csv

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1228]
## Expected Behavior
Rufas_ID always refers to the same feed with very similar characteristics/composition across various feed libraries. 

## Current Behavior

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jms349/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jms349/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Source | Rufas_ID | Name | DM | CP | link
-- | -- | -- | -- | -- | --
RuFaS Feed Library | 135 | Potato | -- | -- | https://docs.google.com/spreadsheets/d/1vOzuEawcU8oFWB2DVWOUNjFuLUDKOuF1/edit?pli=1#gid=1762147550
NASEM_Comp_with_TDN.csv | 135 | Poultry byproduct meal | 95.521 | 65.624 | on Main
NRC_comp.csv | 135 | -- | 5.4 | 10.5 | on Main
Official NASEM feed library | -- | Potato byproduct | 22.98 | 9.989 | https://3.basecamp.com/3486446/buckets/5296287/uploads/6305795974
Official NASEM feed library | -- | Poultry byproduct meal | 95.521 | 65.624 | https://3.basecamp.com/3486446/buckets/5296287/uploads/6305795974

</body>

</html>

## Possible Solution
Immediate solution -- it appears that the name for feed 135 is incorrect on the RuFaS_Feed_Library google sheet (should be "Poultry byproduct meal") and that the ID for what is listed as feed 135 is incorrect on the NRC_comp.csv library. (Or maybe vice versa? I'm not sure what is the gold standard source for which ID should be which feed). Track down which ID should be attached to which feed, and which is appropriate to be listed in each respective library. 

Longer term -- run a systematic check to see if there are other mismatched feeds between the two libraries (and/or others? user_feeds.csv? if more libraries are in use). 

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
These issues do not cause warnings, errors, etc. but could cause rations to be very different than what is expected! Two pilot farms list feed 135 in their rations files (though I'm unsure right now if that is trying to refer to potato or poultry meal), so getting this sorted out quickly (by end of the week) is critical for those farms' results.
We also will want to confirm that there are no other lurking mismatched ID's before generating pilot farm reports (by the end of next week if possible).

**Comment by JoeWaddell** [comment]
Wrote a quick script to compare all shared numeric values in the two libraries. 

For every feed ID shared between NASEM and NRC, for every column shared between NASEM and NRC, I've put the percent difference (0-1) in the two reported values (relative to the NASEM value, e.g. (NASEM_val - NRC_val) / NASEM_val ). So if the NASEM value in column X was 10, the NRC value was 9, the value reported below would be 0.1

[comp_library_column_analysis.csv](https://github.com/RuminantFarmSystems/MASM/files/14184347/comp_library_column_analysis.csv)

**Comment by KFosterReed** [comment]
I am putting the original mapping between the two libraries here: 
[RuFaS_Feed_Library_Combined_Final.xlsx](https://github.com/RuminantFarmSystems/MASM/files/14186394/RuFaS_Feed_Library_Combined_Final.xlsx)

In the combined feeds list Poultry meal is listed as 137 but when we get to the composition tab it has the RuFaS ID 135 assigned to it.  It looks like the original NASEM ID for poultry feed (115) was used twice in the original mapping . Reviewing this mapping and alignment with current feed library should get us back on track. Long term perhaps archiving the google doc so we are only referencing the feed library that is being used may be a good idea so they don't migrate.

**Comment by jadamchick** [comment]
Thanks @KFosterReed - that is very helpful! 
I think it is safe to make this correction: Rufas ID 137 = Poultry byproduct meal = NASEM ID 115

I will update the NASEM_Comp_with_TDN.csv on both Main and Pilot testing to have "Poultry byproduct meal" labeled with ID 137. We will include this in PR's 1226 (pilot testing) and 1239 (Main) and will link those with this issue. 

Which leaves this question: 
Should NRC feed 105 (DM 5.4, CP 10.5) be the same Rufas ID as NASEM feed 114 (DM 22.98, CP 9.989)? Or should one of them by Rufas 135 ("Potato byproduct meal") and the other be Rufas 136 ("Potato byproduct")? 
(Said another way: right now, the NASEM_Comp_with_TDN.csv doesn't have any Potato feed listed, while there is one in the actual NASEM library (ID 114). Assuming we want that to be included, which RuFaS ID should we assign it?)

**Comment by KFosterReed** [comment]
I think I have sorted the Potato debacle (in my head at least, still needs to be fixed in RuFaS). The NRC and NASEM Library do not exactly have equivalent potato feeds (hence the difference in DM%) but my interpretation is that it is likely due to differences in supply chain but on a DM basis, they are pretty close so I think we should call them equivalent. 
RuFaS ID 135 = NRC Potato By-product meal (DM% ~5%), NRC ID 105 = NASEM Potato By-product (DM% ~22%).

**Comment by jadamchick** [comment]
Sounds good! So I think this is the conclusion: 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


Rufas ID | Feed_name | Description | Type | Units | NRC | NASEM | NRC ID | NASEM ID
-- | -- | -- | -- | -- | -- | -- | -- | --
135 | Potato | Byproduct meal | Conc | Kg | Yes | Yes | 105 | 114
136 | Potato | Byproduct | Conc | Kg | No | No |   |  
137 | Poultry | Byproduct meal | Conc | Kg | No | Yes |   | 115



</div>


</body>

</html>


Who can we call on to add that feed (NASEM 114) from the official NASEM library into NASEM_Comp_with_TDN.csv?  I hoped it would be a simple copy/paste, but I see the columns don't line up and I definitely don't have expertise to ensure everything gets filled in correctly.

**Comment by JoeWaddell** [comment]
> Who can we call on to add that feed (NASEM 114) from the official NASEM library into NASEM_Comp_with_TDN.csv? I hoped it would be a simple copy/paste, but I see the columns don't line up and I definitely don't have expertise to ensure everything gets filled in correctly.

I can handle this: It's just complicated by the fact that the TDN and DE values for the Poultry line came from the NRC equivalent for the same RuFaS ID, meaning that they're for potatoes, not chicken. So we'll need those values if we want to keep feed 137 in the `NASEM_Comp_with_TDN.csv` file, otherwise they're pending Issue #834, which will allow us to use the "full" NASEM library (the file Kristan shared).

**Comment by tomhuhh** [comment]
To summarize it, I think the correct RuFaS ID for potato is 135 and that for poultry meal is 137. As suggested by Joe, we will use the TDN and DE values in the NRC table for RuFaS feed 114 (meat meal) and apply them to poultry meal (137; which does not exist in NRC) in the NASEM_with_TDN table. 

I've updated the feed library in the Google sheet but the files used by the code still needs to be updated. 

Thanks!

**Comment by JoeWaddell** [comment]
Closed via: https://github.com/RuminantFarmSystems/MASM/pull/1239
