### ISSUE TITLE
[re-Animal] [Design] [1/3] Generate visual documentation for Animal module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1229]
This is the first action item for _Analyzing Animal Module and planning on action items_ in the roadmap. Here, the goal is to generate comprehensive documentation that captures the gist of the animal module, yet is easy to follow and understand. We achieve this by creating diagrams. Adding text documentation as supplementary material is ok, but the focus should remain on the visual aspect. 
* Consider creating multiple diagrams if applicable.
* Consider creating different types of diagrams based on the information that needs to be conveyed. Some diagrams are:
** ERD,
** Flow charts,
** class diagrams,
** swim lanes,
** DFD,
** sequence diagrams,
** Gantt Charts,
etc.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by ew3361zh** [comment]
Check with Allister for documentation that may be helpful in this issue.

**Comment by Isgotkowitz** [comment]
@allisterakun @JoeWaddell could you please take a look at the diagrams and README in the folder linked above and see if there is anything that you think is missing or that could be improved?

**Comment by JoeWaddell** [comment]
These look great to me: I imagine this as an iterative process though, so I'm certain a select few will be the most useful, and improved during the process.

**Comment by allisterakun** [comment]
This looks good! Great job Ed!
