### ISSUE TITLE
[re-S&C] [Design] [1/3] Generate visual documentation for Crop & Soil module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1230]
This is the first action item for _Analyzing S&C Module and planning on action items_ in the roadmap. Here, the goal is to generate comprehensive documentation that captures the gist of the soil and crop module, yet is easy to follow and understand. We achieve this by creating diagrams. Adding text documentation as supplementary material is ok, but the focus should remain on the visual aspect. 
* Consider creating multiple diagrams if applicable.
* Consider creating different types of diagrams based on the information that needs to be conveyed. Some diagrams are:
** ERD,
** Flow charts,
** class diagrams,
** swim lanes,
** DFD,
** sequence diagrams,
** Gantt Charts,
etc.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by ew3361zh** [comment]
Check docs/docs_SC for Crop and Soil older visual documentation.

**Comment by Isgotkowitz** [comment]
@allisterakun I think the diagrams look great! The only thing I noticed was that the text was pretty grainy when you zoomed in on it, making a little hard to read through. Maybe reuploading them as PNGs instead of PDF would help them display better?

**Comment by Isgotkowitz** [comment]
@allisterakun checked the diagrams again, they're crystal clear. I think they are good to go!

**Comment by allisterakun** [comment]
Closing this issue with final approvals from @KevinP-B and @PooyaHekmati.
