### ISSUE TITLE
[re-Manure] [Design] [1/3] Generate visual documentation for Manure module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1231]
This is the first action item for _Analyzing Manure Module and planning on action items_ in the roadmap. Here, the goal is to generate comprehensive documentation that captures the gist of the manure module, yet is easy to follow and understand. We achieve this by creating diagrams. Adding text documentation as supplementary material is ok, but the focus should remain on the visual aspect. 
* Consider creating multiple diagrams if applicable.
* Consider creating different types of diagrams based on the information that needs to be conveyed. Some diagrams are:
** ERD,
** Flow charts,
** class diagrams,
** swim lanes,
** DFD,
** sequence diagrams,
** Gantt Charts,
etc.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by ew3361zh** [comment]
Reviewed and approved by Pooya, Elle, and Kristan.
