### ISSUE TITLE
[re-Animal] [Design] [2/3] Gather and document requirements for Animal Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1232]
This is the second action item for _Analyzing Animal Module and planning on action items_ in the roadmap. Here, the goal is to gather and document the requirements for animal module. This includes both functional and non-functional requirements. This step is very important and crucial. We use requirements to define success. The results of this task will be used to dictate how the code should look like and what it should do. Consider consulting with different stakeholders, both SMEs and SWEs.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by ltp23** [comment]
[Link to the animal module requirements doc](https://docs.google.com/document/d/1Kayg7sx2eG4uPNo9EQeTQPEeVL7LxcSJYmXQ1gScglU/edit)

**Comment by ltp23** [comment]
There is enough progress on this issue to close it. Please follow this [document](https://docs.google.com/document/d/1Kayg7sx2eG4uPNo9EQeTQPEeVL7LxcSJYmXQ1gScglU/edit) to get the latest updates.

**Comment by Isgotkowitz** [comment]
Grooming session: we can consider this issue completed.
