### ISSUE TITLE
[re-S&C] [Design] [2/3] Gather and document requirements for Soil and Crop Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1233]
This is the second action item for _Analyzing S&C Module and planning on action items_ in the roadmap. Here, the goal is to gather and document the requirements for soil and crop module. This includes both functional and non-functional requirements. This step is very important and crucial. We use requirements to define success. The results of this task will be used to dictate how the code should look like and what it should do. Consider consulting with different stakeholders, both SMEs and SWEs.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by ew3361zh** [comment]
Have had multiple reviews from @PooyaHekmati @KFosterReed, Tom, @Isgotkowitz, @krb78 and while there are some bigger picture conversations that still need to be resolved by SMEs, I think it's ready to be called complete.
