### ISSUE TITLE
[re-Manure] [Design] [2/3] Gather and document requirements for Manure Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1234]
This is the second action item for _Analyzing Manure Module and planning on action items_ in the roadmap. Here, the goal is to gather and document the requirements for the manure module. This includes both functional and non-functional requirements. This step is very important and crucial. We use requirements to define success. The results of this task will be used to dictate how the code should look like and what it should do. Consider consulting with different stakeholders, both SMEs and SWEs.
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by Isgotkowitz** [comment]
Closing this out because I think there are no major questions that are still open when it comes to requirements for the manure module.

There will likely be a lot of smaller, very specific questions about how to implement certain things, but I think that is acceptable.
