### ISSUE TITLE
[re-Animal] [Design] [3/3] Prescribe fixes and solutions for Animal Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1235]
This is the third and last action item for _Analyzing Animal Module and planning on action items_ in the roadmap. Here, the goal is to come up with action items to improve the animal module. This is done by comparing results of #1229 and #1232 and the code and any other documentation. The emphasis is more on answering _what should be done_ versus _how we do it._
Put the created files in the corresponding folder in https://drive.google.com/drive/folders/1veAqYqIpXUPkOlTb7umz1wat0fd6THGQ?usp=sharing . 
Since there won't be any PRs for this, ask for a review before closing the issue.

**Comment by PooyaHekmati** [comment]
Blocked by #1229  and #1232

**Comment by Isgotkowitz** [comment]
Consider:
- simplifying the structure of the code
- must meet the requirements
- do not be bound by existing code structure (think outside of the box), but try to reuse as much code as possible
- maintain separation of responsibility between modules
- regulate data flow within RuFaS
  - all components at the same level of abstraction must communicate through a component that is a level of abstraction higher
  - levels of abstraction must not be mixed
- improving performance (including memory usage, runtime, etc.)
- unify documentation format
- enforce type consistency
