### ISSUE TITLE
Have `OutputManager` handle `data_origin` key in info map

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1240]
**Is your feature request related to a problem? Please describe.**
Issues #1148 and #1160 both instruct the use of a key `"data_origin"` in the info map to indicate where the value being recorded is updated, created, and/or modified. The information associated with this key should be handled specially when the Output Manager sees it.

**Describe the solution you'd like**
What happens with key specifically when the Output Manager has yet to see it has not been figured out yet.

**Describe alternatives you've considered**

**Additional context**

**Comment by allisterakun** [comment]
Consult various SMEs about the usefulness of representing the `data_origin` in the actual output data (instead of leaving them in the info map). Proceed accordingly.

**Comment by ltp23** [comment]
A follow-up issue (#1416) has been created.
