### ISSUE TITLE
Housing emissions for CBPB and Open Lot pen types

### ISSUE THREAD

**Issue by elle-andreen** [RuminantFarmSystems/RuFaS#1247]
Housing emissions from manure in RuFaS are defined as the gas emissions from manure that occur while manure is still in the pen with the animals, i.e., before manure is removed to manure treatment/storage. It's important to account for these emissions separately because they both represent a considerable portion of total emissions across the manure chain, and they represent a loss of nutrients from the daily manure mass that eventually enters storage. Of note is that the method to calculate housing emissions **depends on the pen type**. The methods for each pen type are as follows (using generic names just to demonstrate overlap between pen types):
- Method 1: Freestall & tiestall 
- Method 2: CBPB
- Method 3: Open Lot

Presently, in manure_handler_classes.py, the ManureHandlerDailyOutput is returning these 3 housing emissions variables:
	
```
	housing_methane_emission
	housing_carbon_dioxide_emission
	housing_ammonia_emission
```
	
These 3 values are calculated using corresponding functions in calculator.py. Presently, it appears the housing emissions (CH4, CO2, NH3) values are being calculated using **methods only applicable to freestall/tiestall** (e.g., applying method 1 to all pen types). Meaning, ManureHandlerDailyOutput is returning incorrectly calculated housing_emissions values for CBPB and Open Lot pens.

## Possible Implementation
1. We could add pen-type based logic similar to what is shown below (from Niko's TAN PR, not yet merged) to housing_methane_emission and housing_carbon_dioxide_emission in manure_handler_classes.py, to prevent incorrect housing emissions outputs of these variables being returned for CBPB and OL pens. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/148499778/8a9086b7-a158-4848-8781-0c3aebea92ed)

For the future, we should also consider if/how housing emissions from CBPB and OL pens should be calculated and named, depending on if CBPB and OL are being used as _both_ the pen type and manure treatment method, or as _only_ the pen type followed by composting or field application.

**Comment by KFosterReed** [comment]
Thanks for making this issue @elle-andreen! I think your proposed solution is perfect. The way I see the CBPB and Openlot 'housing' emissions working is that we continue to handle them in the manure storage/treatment class and in the future add the option to have the treatment/storage of either CBPB or Open lots followed by composting. 

Removing the CO2 and CH4 housing emissions estimates from the open lots and CBPB pen types as proposed above should get us to the first goal until we have composting following those methods.

**Comment by Isgotkowitz** [comment]
@elle-andreen are there equations for calculating GHG emissions for open lot and CBPB pens? If the equations are present, it should be pretty easy to add them into `GasEmissionsCalculator` and pick the right calculation method in `daily_update()` in `BaseManureHandler`.

**Comment by KFosterReed** [comment]
My understanding is that we do not want to estimate housing emissions from the CBPB or open lot pens because the emissions are predicted in the manure treatment methods. I think part of the confusion is that these two management methods are really both a housing choice and a manure management choice so I am not sure they fit into either the ManureHandler or ManureTreatment parts of our manure module exactly but in our "RuFality" we have chosen to put them in the manure treatment

**Comment by Isgotkowitz** [comment]
> My understanding is that we do not want to estimate housing emissions from the CBPB or open lot pens because the emissions are predicted in the manure treatment methods. I think part of the confusion is that these two management methods are really both a housing choice and a manure management choice so I am not sure they fit into either the ManureHandler or ManureTreatment parts of our manure module exactly but in our "RuFality" we have chosen to put them in the manure treatment

Ok, I think I gotcha. So all that is needed to close this issue is to make sure that the housing emissions for open lots and CBPB are always zeroed out?

**Comment by elle-andreen** [comment]
> Ok, I think I gotcha. So all that is needed to close this issue is to make sure that the housing emissions for open lots and CBPB are always zeroed out?

Yes! We will likely come back in the future and modify if/how we report housing emissions from CBPB and Open Lot pens, but for now, those two pen types should not have any housing emissions reported.

**Comment by Isgotkowitz** [comment]
Well alright then, I will have a PR put together very soon. Thank you @elle-andreen and @KFosterReed for helping me understand what is going on here.

**Comment by Isgotkowitz** [comment]
This was more of an XS, modifying it to be that size
