### ISSUE TITLE
Investigate the current state of `InputManager`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1249]
The current state of the Input Manager is making improvements and bug fixes difficult. This issue is for investigating how the Input Manager should be improved so work on it can move more smoothly.

The first two comments detail how the requirements of the IM as detailed in the design doc could be expanded/improved. The third is a feature suggestion that I think would a nice-to-have. And the fourth outlines specific issues in the implementation of IM that need to be addressed.

This issue is blocking #683.

**Comment by Isgotkowitz** [comment]
## Agnostic to Inputs

(Let us define "gnostic" as the opposite of agnostic for the purposes of this discussion.)

The design doc for the IM does not say that the IM must be agnostic to input types in those exact words. However, it has non-functional requirement #10: "IM must allow integration with various input streams (files, DBs, API calls, etc…).", which implies a certain level of agnosticism to input types. I think that a non-functional requirement should be added which states "IM must maintain an internal representation of input data and execute validation in a way that is agnostic to the stream type from which said data came." 

What does this mean in practice? First let's acknowledge that IM has to be gnostic to where input data is coming from. If input data is in a JSON file, we use the `json` library to extract that data from the file. If the data is in a CSV file, we use Pandas to extract the data, and we can extend the same idea to working with data collected from API and database streams. But once we have loaded the data from its source, the way it is managed and validated in IM should be agnostic to the source stream.

Let's work through an example of what the desired behavior is:
Suppose there is some input data, that could be in either a JSON or a CSV file. Suppose it looks like this as JSON data:
```json
{
  "a": [1, 2, 3],
  "b": [4, 5, 6],
  "c": [7, 8, 9]
}
```
And this as CSV (tabular) data:
|a|b|c|
|-|-|-|
|1|4|7|
|2|5|8|
|3|6|9|

Once this example data is loaded into IM, it should look like the following, whether it was loaded from a JSON or CSV file:
```python
>>> print(example_input_data)
{"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]}
```

Is there any significant benefit to doing this? Yes! The same data can come from any of the supported input streams but there would only be one set of properties needed to validate it. This means that there will be less room for error and inconsistency when linking input to properties in the metadata, and when writing properties.

**Comment by Isgotkowitz** [comment]
## Arbitrarily Complex Inputs

Functional Requirement #2 of the IM design doc states that "IM must provide data validation functionality to ensure that the structure of the data is usable and the values of the data are within the pre-defined ranges and follow specified patterns." It is not specified though how complex the structure of the data can be.

I propose that we add to the functional requirements that the IM must be able to fully validate every value within an arbitrarily complex input. This means that if someone can write valid metadata properties for the input, the IM can fully utilize those properties to validate every piece of data in the input that is specified to meet those properties.

### Limiting Input Complexity

It may be the case that allowing for arbitrarily complex inputs is actually inappropriate for the IM. If this is the case, then there must be clear bounds that are set and checked for when validating input data with the metadata properties. If metadata properties are given that violate the complexity limits set, then the IM should reject those properties and assume that 

I would like to emphasize that there should be no in-between fully validating arbitrarily complex inputs and limiting input complexity. If the IM manager is written in such a way that it doesn't fully validate some input data against a valid set of properties, then it would be failing functional requirement #2.

**Comment by Isgotkowitz** [comment]
## Dynamic Keys (Feature)

### Problem Introduction
Imagine a scenario where we would like to simulate something, and that _thing_ could be configured in multiple ways. Let's say we want to have multiple configurations available to the simulation, we want those configurations defined in an input file, and we want to be able to write different sets of configurations in different inputs. Different sets of configurations will differ in the names and number of configurations, but each configuration will follow a rigid structure. Let's work through what this looks like with a JSON example (because that is probably the type of file we would use for such an input).

### Current Solution
A way that we could construct an input to accept configs meeting the requirements as described above could be to accept an array of objects, where each object is a configuration. As an example:
```json
{
  "configs": [
    {
      "name": "a",
      "setting": 1
    },
    {
      "name": "b",
      "setting": 2
    },
    {
      "name": "c",
      "setting": 3
    }
  ]
}
```
And another set of configurations could be:
```json
{
  "configs": [
    {
      "name": "d",
      "setting": 1
    },
    {
      "name": "e",
      "setting": 2
    }
  ]
}
```
This meets all the requirements defined above.

### So what's the issue?
Let us assume that to include multiple definitions of the same configuration is a serious error case. The IM currently does not have the capacity to identify this serious error case (defining the "a" configuration twice):
```json
{
  "configs": [
    {
      "name": "a",
      "setting": 1
    },
    {
      "name": "a",
      "setting": 2
    }
  ]
}
```

### Proposed Solution
Add the logic into the IM so that it can handle a dynamic set of keys. Taking the first example, this is how it could be rewritten:
```json
{
  "configs": {
    "a": {
      "setting": 1
    },
    "b": {
      "setting": 2
    },
    "c": {
      "setting": 3
    }
  }
}
```
and the second set of configurations could be specified as
```json
{
  "configs": {
    "d": {
      "setting": 1
    },
    "e": {
      "setting": 2
    }
  }
}
```
Now we have all the same information as before, but the error case demonstrated above is now impossible thanks to the structure of JSON.

### Alternative Solution
Are there any alternatives? Yes! The most obvious one is cross-validation, which is intended to handle situations exactly like this one - where the validity of one input is dependent upon the value of other inputs. Having the ability to enforce uniqueness with cross validation would be superior in some ways, because multiple fields could be checked for uniqueness. In the example used above, uniqueness was needed for only one field: "name". But what if uniqueness needed to be enforced for "setting" too? There isn't a way to leverage JSON to do that automatically for us.

Another way in which cross-validation would be superior to dynamic keys is that it could (presumably) enforce uniqueness on any data type, not just strings. This is a limitation of JSON, in which only strings can be keys in object literals.

So if cross-validation has so many advantages over dynamic keys, why should there even be a debate about which one to use? Well, it necessarily an either-or, having both available might be good. There may be a lot of situations where dynamic keys are sufficient for enforcing valid inputs, dynamic keys would might be easier to implement and flush out bugs in than cross-validation.

### Additional Considerations
Dynamic sets of keys might be handy in a lot of scenarios, but there may be scenarios where the key sets should be constrained in certain ways. For example, enforcing a Regex pattern on all keys, setting bounds on the number of keys (upper and lower), requiring that certain keys always be present or establishing protected keys that can't be used, etc. may be necessary in some cases.

**Comment by Isgotkowitz** [comment]
## Implementation-Specific Issues
- Code Duplication:
  - Code duplication is an extremely bad practice, and there are several duplicated functionalities in the Input Manager.
  - `_validate_tabular_element()` is essentially a combination of `_validate_dict_element()` and `_array_type_validator()`, with the added functionality of validating array elements. While addressing the above comment labeled "Agnostic to Inputs" and #683, `_validate_tabular_element()` should either be changed to have unique functionality or be removed.
  - Multiple functions have `reduce(lambda d, ...)`. This logic should either be extracted and put in a dedicated function or removed entirely (more on that below).
- Disuniform Method Signatures:
  - Not all methods that may need to work with each other have the same signature, making them incompatible.
  - Several methods that have the same signature are `_validate_input_type_dynamic()` and the four validator methods it calls, but these signatures are different from `_validate_dict_element()` and `_fix_data()`, making it difficult and inconvenient if not impossible to call the latter methods from the former.
  - This plays a big part of why array element validation has been so intractable.
- Unnecessary Complexity:
  - `_validate_dict_element()` is overly complex (which is why it has a `noqa`). It needs to be changed to be less complex.
  - As mentioned above, there are several `reduce(lambda ...)` statements in the code. These expressions are especially difficult to understand, and ideally the code would be rewritten so that they are no longer necessary.
- No Metadata Properties Validation:
  - Even though the properties used to validate and correct inputs are written in JSON, they can be thought of as code - and what do we do with code that we write? We test it!
  - Currently there is no testing of the properties, which means they are just as vulnerable to bugs as any other part of the code base. Situations like minimums being greater than maximums, invalid defaults, and incorrectly structured properties can and have happened.
  - Code to either test property validity or revalidate properties alongside inputs (or both) should be developed.

**Comment by PooyaHekmati** [comment]
>a non-functional requirement should be added which states "IM must maintain an internal representation of input data and execute validation in a way that is agnostic to the stream type from which said data came."

IM cannot be agnostic to the input stream. Different streams are subject to different defects, therefore, needing specialized data cleaning, validation, and verification approaches. However, we can say that IM has to persist and present data to downstream processes such that they are agnostic to the data origin, which is the other way of saying IM has to be SSOT.

**Comment by PooyaHekmati** [comment]
>What does this mean in practice? First let's acknowledge that IM has to be gnostic to where input data is coming from. If input data is in a JSON file, we use the json library to extract that data from the file. If the data is in a CSV file, we use Pandas to extract the data, and we can extend the same idea to working with data collected from API and database streams. But once we have loaded the data from its source, the way it is managed and validated in IM should be agnostic to the source stream.

To me, this paragraph sounds like confusing/mixing verification, validation, and persistence steps.

**Comment by PooyaHekmati** [comment]
Putting a limit to the data complexity falls in functional requirement #2, and doesn't need a new requirement. The main question is how this can be achieved.

> I would like to emphasize that there should be no in-between fully validating arbitrarily complex inputs and limiting input complexity. If the IM manager is written in such a way that it doesn't fully validate some input data against a valid set of properties, then it would be failing functional requirement #2.

How can we fix it?

**Comment by PooyaHekmati** [comment]
> ## Dynamic Keys (Feature)
> ### Problem Introduction
> Imagine a scenario where we would like to simulate something, and that _thing_ could be configured in multiple ways. Let's say we want to have multiple configurations available to the simulation, we want those configurations defined in an input file, and we want to be able to write different sets of configurations in different inputs. Different sets of configurations will differ in the names and number of configurations, but each configuration will follow a rigid structure. Let's work through what this looks like with a JSON example (because that is probably the type of file we would use for such an input).
> 
> ### Current Solution
> A way that we could construct an input to accept configs meeting the requirements as described above could be to accept an array of objects, where each object is a configuration. As an example:
> 
> ```json
> {
>   "configs": [
>     {
>       "name": "a",
>       "setting": 1
>     },
>     {
>       "name": "b",
>       "setting": 2
>     },
>     {
>       "name": "c",
>       "setting": 3
>     }
>   ]
> }
> ```
> 
> And another set of configurations could be:
> 
> ```json
> {
>   "configs": [
>     {
>       "name": "d",
>       "setting": 1
>     },
>     {
>       "name": "e",
>       "setting": 2
>     }
>   ]
> }
> ```
> 
> This meets all the requirements defined above.
> 
> ### So what's the issue?
> Let us assume that to include multiple definitions of the same configuration is a serious error case. The IM currently does not have the capacity to identify this serious error case (defining the "a" configuration twice):
> 
> ```json
> {
>   "configs": [
>     {
>       "name": "a",
>       "setting": 1
>     },
>     {
>       "name": "a",
>       "setting": 2
>     }
>   ]
> }
> ```
> 
> ### Proposed Solution
> Add the logic into the IM so that it can handle a dynamic set of keys. Taking the first example, this is how it could be rewritten:
> 
> ```json
> {
>   "configs": {
>     "a": {
>       "setting": 1
>     },
>     "b": {
>       "setting": 2
>     },
>     "c": {
>       "setting": 3
>     }
>   }
> }
> ```
> 
> and the second set of configurations could be specified as
> 
> ```json
> {
>   "configs": {
>     "d": {
>       "setting": 1
>     },
>     "e": {
>       "setting": 2
>     }
>   }
> }
> ```
> 
> Now we have all the same information as before, but the error case demonstrated above is now impossible thanks to the structure of JSON.
> 
> ### Alternative Solution
> Are there any alternatives? Yes! The most obvious one is cross-validation, which is intended to handle situations exactly like this one - where the validity of one input is dependent upon the value of other inputs. Having the ability to enforce uniqueness with cross validation would be superior in some ways, because multiple fields could be checked for uniqueness. In the example used above, uniqueness was needed for only one field: "name". But what if uniqueness needed to be enforced for "setting" too? There isn't a way to leverage JSON to do that automatically for us.
> 
> Another way in which cross-validation would be superior to dynamic keys is that it could (presumably) enforce uniqueness on any data type, not just strings. This is a limitation of JSON, in which only strings can be keys in object literals.
> 
> So if cross-validation has so many advantages over dynamic keys, why should there even be a debate about which one to use? Well, it necessarily an either-or, having both available might be good. There may be a lot of situations where dynamic keys are sufficient for enforcing valid inputs, dynamic keys would might be easier to implement and flush out bugs in than cross-validation.
> 
> ### Additional Considerations
> Dynamic sets of keys might be handy in a lot of scenarios, but there may be scenarios where the key sets should be constrained in certain ways. For example, enforcing a Regex pattern on all keys, setting bounds on the number of keys (upper and lower), requiring that certain keys always be present or establishing protected keys that can't be used, etc. may be necessary in some cases.

can you briefly explain what is the issue, why is it important, and how can it be fixed? (following what-why-how) pattern.

**Comment by PooyaHekmati** [comment]
> ## Implementation-Specific Issues
> * Code Duplication:
>   
>   * Code duplication is an extremely bad practice, and there are several duplicated functionalities in the Input Manager.
>   * `_validate_tabular_element()` is essentially a combination of `_validate_dict_element()` and `_array_type_validator()`, with the added functionality of validating array elements. While addressing the above comment labeled "Agnostic to Inputs" and [Expand array input data validation capabilities in IM #683](https://github.com/RuminantFarmSystems/MASM/issues/683), `_validate_tabular_element()` should either be changed to have unique functionality or be removed.
>   * Multiple functions have `reduce(lambda d, ...)`. This logic should either be extracted and put in a dedicated function or removed entirely (more on that below).
> * Disuniform Method Signatures:
>   
>   * Not all methods that may need to work with each other have the same signature, making them incompatible.
>   * Several methods that have the same signature are `_validate_input_type_dynamic()` and the four validator methods it calls, but these signatures are different from `_validate_dict_element()` and `_fix_data()`, making it difficult and inconvenient if not impossible to call the latter methods from the former.
>   * This plays a big part of why array element validation has been so intractable.
> * Unnecessary Complexity:
>   
>   * `_validate_dict_element()` is overly complex (which is why it has a `noqa`). It needs to be changed to be less complex.
>   * As mentioned above, there are several `reduce(lambda ...)` statements in the code. These expressions are especially difficult to understand, and ideally the code would be rewritten so that they are no longer necessary.
> * No Metadata Properties Validation:
>   
>   * Even though the properties used to validate and correct inputs are written in JSON, they can be thought of as code - and what do we do with code that we write? We test it!
>   * Currently there is no testing of the properties, which means they are just as vulnerable to bugs as any other part of the code base. Situations like minimums being greater than maximums, invalid defaults, and incorrectly structured properties can and have happened.
>   * Code to either test property validity or revalidate properties alongside inputs (or both) should be developed.

I think we need a more prescriptive approach and mindset here. Ok, we identified the problems, good! What's next? How should they be addressed?

**Comment by Isgotkowitz** [comment]
> > What does this mean in practice? First let's acknowledge that IM has to be gnostic to where input data is coming from. If input data is in a JSON file, we use the json library to extract that data from the file. If the data is in a CSV file, we use Pandas to extract the data, and we can extend the same idea to working with data collected from API and database streams. But once we have loaded the data from its source, the way it is managed and validated in IM should be agnostic to the source stream.
> 
> To me, this paragraph sounds like confusing/mixing verification, validation, and persistence steps.

I think I am not understanding the verification vs. validation vs. persistence as it pertains to the IM.

> Different streams are subject to different defects, therefore, needing specialized data cleaning, validation, and verification approaches. However, we can say that IM has to persist and present data to downstream processes such that they are agnostic to the data origin, which is the other way of saying IM has to be SSOT.

I think of "validation" as looking at the input data and executing a series of steps to determine if it is valid based on the properties specified for it in the metadata. This happens after it has been collected from the source stream (call this step "collection"). In this sense, "validation" is downstream of "collection". By assuming that the structure of the data being fed into the validation step is agnostic to the stream it was collected from, we can make the code and the properties implementing the validation step a lot less duplicative.

**Comment by Isgotkowitz** [comment]
> Putting a limit to the data complexity falls in functional requirement #2, and doesn't need a new requirement. The main question is how this can be achieved.
>> I would like to emphasize that there should be no in-between fully validating arbitrarily complex inputs and limiting input complexity. If the IM manager is written in such a way that it doesn't fully validate some input data against a valid set of properties, then it would be failing functional requirement #2.
>
> How can we fix it?

First step to fixing it is defining how we measure complexity, then think about how to bound it appropriately.

I propose that 1) everything is thought of as a JSON, and 2) the complexity of a JSON is defined as the number of complex data structures (i.e. arrays and objects) one must go through to get to the deepest non-complex data (i.e. _not_ an array or object). See below examples.

A maximum complexity value can be declared (and easily adjusted) in the IM, and a complexity counter can be incremented in successive recursive calls. If the complexity counter is found to be equal or greater than the maximum allowed complexity then an error will be logged, the data will be considered invalid, and whatever method found the overly complex data returns.

Complexity examples:

`{"a": 1}`, `{"b": "value"}`, and `{"c": true}` have complexity = 0.

`{"x": [1, 2, 3]}` and `{"y": {"i": 1, "j": true}}` have complexity = 1.

```json
{
  "a" : [
    {"b": "c"},
    {"e": "f"}
  ]
}
```
and `{"a": [[1, 2, 3], [4, 5, 6]]}` have complexity = 2.

```json
{
  "a": [
    {
      "e": [1, 2, 3],
      "f": true
    },
    {"g": 4}
  ]
}
```
has complexity = 3.

**Comment by Isgotkowitz** [comment]
> > ## Implementation-Specific Issues
> > 
> > * Code Duplication:
> >   
> >   * Code duplication is an extremely bad practice, and there are several duplicated functionalities in the Input Manager.
> >   * `_validate_tabular_element()` is essentially a combination of `_validate_dict_element()` and `_array_type_validator()`, with the added functionality of validating array elements. While addressing the above comment labeled "Agnostic to Inputs" and [Expand array input data validation capabilities in IM #683](https://github.com/RuminantFarmSystems/MASM/issues/683), `_validate_tabular_element()` should either be changed to have unique functionality or be removed.
> >   * Multiple functions have `reduce(lambda d, ...)`. This logic should either be extracted and put in a dedicated function or removed entirely (more on that below).
> > * Disuniform Method Signatures:
> >   
> >   * Not all methods that may need to work with each other have the same signature, making them incompatible.
> >   * Several methods that have the same signature are `_validate_input_type_dynamic()` and the four validator methods it calls, but these signatures are different from `_validate_dict_element()` and `_fix_data()`, making it difficult and inconvenient if not impossible to call the latter methods from the former.
> >   * This plays a big part of why array element validation has been so intractable.
> > * Unnecessary Complexity:
> >   
> >   * `_validate_dict_element()` is overly complex (which is why it has a `noqa`). It needs to be changed to be less complex.
> >   * As mentioned above, there are several `reduce(lambda ...)` statements in the code. These expressions are especially difficult to understand, and ideally the code would be rewritten so that they are no longer necessary.
> > * No Metadata Properties Validation:
> >   
> >   * Even though the properties used to validate and correct inputs are written in JSON, they can be thought of as code - and what do we do with code that we write? We test it!
> >   * Currently there is no testing of the properties, which means they are just as vulnerable to bugs as any other part of the code base. Situations like minimums being greater than maximums, invalid defaults, and incorrectly structured properties can and have happened.
> >   * Code to either test property validity or revalidate properties alongside inputs (or both) should be developed.
> 
> I think we need a more prescriptive approach and mindset here. Ok, we identified the problems, good! What's next? How should they be addressed?

It is easy to flip the first three points from problems into appropriate solutions:
Problem: code duplication. Solution: deduplicate code.
Problem: inconsistent method signatures. Solution: unify method signatures.
Problem: unnecessarily complex code. Solution: rewrite it to be less complex.

The solution to the last problem is less straightforward. I think it would be good to write in a command-line option to specify whether to validate the properties at the same time it is validating input. This way, if RuFaS is being run in a client-server scenario where clients provide inputs but the server uses the same set of properties for each run, the properties validation can be turned off (the same set of properties doesn't need to be validated over and over again). But if a researcher is experimenting with RuFaS and modifying the properties to accommodate their simulation, or a developer is adding to/modifying the properties, they can easily turn on property validation.

**Comment by Isgotkowitz** [comment]
## Dynamic Keys (Feature) (Concise Version)

### What?
There is currently no way to define the structure of an input file such that different versions of the input file can have different names and numbers of keys.

### Why?
Being able to write the same type of input file but with different sets of keys would allow for more readable, concise input files to be written. Also, in the case of JSON, it puts the burden of enforcing key uniqueness on the `json` library making it harder for bugs to be introduced in the code for validating inputs.

### How?
Introduce a boolean field in the properties of an object called "dynamic_keys". If true, it signals to IM that the number of keys in the object is variable. Additionally, other fields could be introduced that make sure certain keys are or are not present, or the number of keys is bounded in some way, etc.

**Comment by Isgotkowitz** [comment]
Another change that should be made to the code: if `get_data()` is called with an address that doesn't match any data, it should not crash (the current behavior is to raise a KeyError).

**Comment by Isgotkowitz** [comment]
Closing this issue because I have written up the findings from the investigation as four different issues that can actually be implemented in the IM.
