### ISSUE TITLE
Display in the console the number of warnings and errors and/or links to the OM warning and error log files

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1251]
**Is your feature request related to a problem? Please describe.**
I often forget to open the warning and error log files after the simulation finishes. So, I think having some form of a reminder would be very helpful. It seems incomplete to say that the simulation runs successfully but there are warnings and errors I'm not aware of right away. 

**Describe the solution you'd like**
My proposed solution is to display the counts of warnings and errors at a minimum and also have an opt-in command line argument option to display the links (absolute or relative) to the location of the log files at the end of the simulation. 

**Describe alternatives you've considered**
To keep it even more minimal, only display the counts of warnings and errors if there is at least one warning/error.

**Comment by PooyaHekmati** [comment]
@ltp23 Shouldn't this have a dev team label?

**Comment by PooyaHekmati** [comment]
Reopenign the issue per comment I left here: https://github.com/RuminantFarmSystems/MASM/pull/1302#pullrequestreview-1896611618
Should be easy to fix.
