### ISSUE TITLE
[Output Manager] Populate output with units

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1254]
It is expected that all variables that are reported to OM have accompanying units. We have to modify how OM populates outputs so that it includes units. 
* Consider adding a formatting method to OM (if applicable) to avoid code duplication.
* Consider both csv and json files.
* How do we want to handle reports and graphs? Do we want to pass the units to those as well? If yes, how do we want to handle them during the report/graph generation process, and what is the expected behavior?
* How do we want to handle complex data structures such as dictionaries? Would filtering by exclusion lead to weird scenarios?

@jadamchick @JoeWaddell @KFosterReed @krb78 @tomhuhh seeking your insight here. I can propose some technical solutions, but would like to know your perspective first.

**Comment by PooyaHekmati** [comment]
Blocked by #1253

**Comment by PooyaHekmati** [comment]
Handling the units in OM only makes the issue's T-shirt size small, bringing the graph and report generators into the picture can make it medium or even large.

**Comment by allisterakun** [comment]
1. If the variable received by OM does not have a unit in the info_map, we will reject it.
2. Formatting the output to include the units is being done in #1416.

**Comment by ltp23** [comment]
The handling of units in json output will be tackled in issue #1434, specifically. There are separate issues for each of the remaining output formats — csv (#1514), graphs (#1515 ), and reports (#1516).

**Comment by Isgotkowitz** [comment]
Grooming session: we have units in outputs, so we are closing this issue.
