### ISSUE TITLE
Housing emissions double counting 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1268]
The number of animals/stalls are double counted in the `housing_methane_emission` & `housing_carbon_dioxide_emission` functions.

The `num_animals` is used when calculating housing methane. 
<img width="654" alt="Screenshot 2024-02-13 at 10 27 13 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/52800053/4a507897-2f3d-4937-a12b-421ed43c5f47">

The `num_stalls` is used when calculating barn area. 
<img width="638" alt="Screenshot 2024-02-13 at 10 30 57 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/52800053/a0ba5f68-c20c-43f0-b71c-fbabb78eb2c3">

Similar issue also happens in the `housing_carbon_dioxide_emission` function. Please double check in the code file to make sure that I am not missing anything.  

## Expected Behavior

The barn area is a multiplication of stall area and the number of stalls, `num_stalls`.  So we do not further multiply it by `num_animals` when calculating housing emissions. 

## Current Behavior

The number of animals/stalls are double counted. 

## Possible Solution

Delete `num_animals` in the return statement of the  `housing_methane_emission` & `housing_carbon_dioxide_emission` functions. Please make sure to update the unit tests.  

## Steps to Reproduce

1. Simulate any manure management scenarios and make sure you have a filter that outputs housing methane and total methane. 
2. Check the ratio of housing methane to total methane and if it is above 5% (as suggested by the literature), there is an issue of overestimating housing methane. 
3.
4.

**Comment by elle-andreen** [comment]
For context: this occurred from [this commit](https://github.com/RuminantFarmSystems/MASM/pull/1144/commits/1bfd4a32bf1b1f9543adcacdeaa4c2f9b5fe4640) in PR 1171, which was addressing TAN issues. You can see we made the appropriate updates within the `housing_ammonia_emission` function to avoid double-counting, but not for other calculations in calculator.py that rely on barn area! So you are correct that double-counting is occurring for `housing_methane_emission` & `housing_carbon_dioxide_emission`. 

We should also consider updating `manure_manager_pen.py` as the docstring still describes barn area as per animal, not per stall.
