### ISSUE TITLE
Volatile solids initialization in the manure module 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1269]
Currently the manure module only retrieves the total volatile solid (VS) output from the animal module. To obtain degradable VS (VSd) and nondegradable VS (VSnd), it uses an assumed ratio between VSd and VS which is `0.2/0.48 = 0.41` as suggested by the Chianese et al. 2009 and Sommer 2004 paper. 

However, this creates an disconnection between the outputs of animal module and the inputs of manure module. We potentially lose the opportunity to evaluate the impact of animal factors on manure gas emissions as predicted by VSd and VSnd. 

Instead, we should consider passing on the VSd and VSnd output from the animal module to the manure module and using these values in the calculations of, for example, storage methane.    

## Expected Behavior

I would expect the manure module to directly use the outputs of animal module, i.e. VSd, VSnd, when calculating emissions such as storage methane emissions.  

## Current Behavior

The manure module uses the VS output from the animal module and an assumed ratio between VSd and VS to calculate VSd and VSnd, and then calculates gas emissions such as storage methane emissions. 

This assumed ratio is from studies done in Europe, and the potential issue with that is that the European diets typically is higher in forage (i.e. alfalfa) which can lead to lower VSd to VS ratio. 

## Possible Solution
 

I would first check how the animal module outputs VSd and VSnd. Then I would add these two variables to the input attribute of the manure module. In the `calculator.py` file, I would then use VSd and VSnd for calculations of for example, storage methane.  

## Steps to Reproduce

1.
2.
3.
4.

**Comment by elle-andreen** [comment]
Haowen and I created [this document](https://docs.google.com/document/d/1EfYQUIwoIrt05yWLauEefcdTlgkGkk0WX6EoVqrL6eQ/edit) that has additional detail on this issue. Please note as per the doc that issues 1269-1271 are interrelated and build upon one another. Let us know if there are further questions or clarifications needed!
