### ISSUE TITLE
Storage methane emission calculations 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1271]
Currently the `methane_emission_from_slurry_storage` is not correctly implemented. There seem to be some flaws with the approach proposed by Chianese et al. 2009  (https://www.researchgate.net/publication/43286301_Simulation_of_Methane_Emissions_from_Dairy_Farms_to_Assess_Greenhouse_Gas_Reduction_Strategies). More recent literature (Peterson et al., 2016, Peterson et al. 2024) refers back to the original paper (Sommer et al. 2004; https://doi.org/10.1023/B:FRES.0000029678.25083.fa) when they present the storage methane emission calculations. 

Here is a comparison between the two approaches. As you can see, on a daily basis, the Chianese approach overestimated the amount of storage methane by about 20 times.  

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/73056f2a-cfc8-4d14-89a7-15de3d8bf036)

In addition, more recent literature (Peterson et al. 2016: 10.1371/journal.pone.0160968; Peterson et al. 2024: https://doi.org/10.1016/j.jenvman.2024.120233) suggest updates for constants used in the `methane_emission_from_slurry_storage` function. Please also check in the discussion section of the Peterson et al. 2016 paper for more details on why the updates were made.  

![Screenshot 2024-02-13 at 11 37 53 AM](https://github.com/RuminantFarmSystems/MASM/assets/52800053/51303c0e-7e28-4248-9214-6c1c86e9244f)

To summarize the changes in the constants used, we should use an Ea of 81 instead of 112.7 KJ/mol and lnA of 31.2 instead of 44.3.  Also to note, these two constants are great fit for sensitivity analysis of model constants.    

## Expected Behavior

The `methane_emission_from_slurry_storage` function correctly calculates daily storage methane emissions from accumulated manure storage (volatile solids). 

## Current Behavior

The approach used overestimated the daily storage methane emissions and some constants are outdated based on more recent publications from the same group.  

## Possible Solution

Update the  `methane_emission_from_slurry_storage` function based on the most recent publication (Peterson et al. 2024).  

## Steps to Reproduce

1. Simulate slurry storage and make sure your filter has storage methane and enteric methane.  
2. Compare storage methane to enteric methane. These two values should be somewhat within each other's range because they account for the two major sources for methane on dairy farms. 
3.
4.

**Comment by PooyaHekmati** [comment]
more inputs from SMEs to come.

**Comment by elle-andreen** [comment]
Haowen and I created [this document](https://docs.google.com/document/d/1EfYQUIwoIrt05yWLauEefcdTlgkGkk0WX6EoVqrL6eQ/edit) that has additional detail on how/where these calculations should be updated. Please note as per the doc that issues 1269-1271 are interrelated and build upon one another. Let us know if there are further questions or clarifications needed!
