### ISSUE TITLE
Modifying array element in IM pool during runtime

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1273]
**Feature Description**
Implement the ability to modify one (or some) specific element(s) of an array in the IM pool during runtime.

**Proposed Solution**
Create a new function that utilizes the current IM functions (`get_data`, `add_tabular_variable_to_pool`, and `_add_variable_to_pool`) to implement the functionality. The new function should take in the element hierarchy of the target array. It should call `get_data()` to retrieve the current array data and save it to a local variable. It would also take in other necessary parameters to modify the array. Finally, it would call `add_tabular_variable_to_pool` or `_add_variable_to_pool` to replace the array with the updated data.

**Comment by Isgotkowitz** [comment]
Grooming session: closing this as not planned
