### ISSUE TITLE
Analyze Results from Uncalled Functions in Codebase

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1277]
Analyze the lists linked in the comments at the end of issue #1105 and do a deeper dive to look through the list of uncalled functions to see if any are genuinely stale.

The explanation of how the list was put together is in #1105 but here is a direct link to the list of functions uncalled during a default-scenario simulation. They've been sorted by module/origin:

[Uncalled Functions](https://docs.google.com/document/d/1NroaHk1C9DDKxRtudM6MKKgyX31tC2PXiYClEirpt_Y/edit)

Some suggested approaches:
1. Are the functions uncalled because of the settings of the scenario run? Try running different scenarios using different manure, animal, etc settings to see if those functions that are currently listed as uncalled.
2. Speak with other developers and SMEs about specific areas they may have more familiarity with. Do they know the circumstances under which one of these "uncalled" functions may be needed? Try to create those circumstances.

**Comment by Isgotkowitz** [comment]
This has to be considered in issues #1235 #1236 and #1237.

**Comment by ltp23** [comment]
- [x] Convert the GDoc to GSheet.
- [ ] Look at the edit history of the functions listed to get some clues/insights.

**Comment by allisterakun** [comment]
Here is the Goole Sheets containing all 262 functions mentioned in the GDoc:
[Uncalled Functions in RuFaS](https://docs.google.com/spreadsheets/d/1l3SucZs4BqUZsFk7SPg_A9ksz8cjXR8cWicGUuWp7uA/edit#gid=0)

**Comment by allisterakun** [comment]
I made three issues to make decisions and take action on the uncalled functions in each of the three biophysical modules: 
1. #1466.
2. #1468.
3. #1469.
Closing this issue with this comment.
