### ISSUE TITLE
Rename of the Event class in Field folder

### ISSUE THREAD

**Issue by matthew7838** [RuminantFarmSystems/RuFaS#1283]
Likely not something for this PR but it seems like Event is a little too general a class name even with it being a parent class which multiple subclasses inherit from. @Isgotkowitz Has it ever been discussed to change the name of this to something more specific to C&S? I asked chatgpt for some suggestions based on the notes section:

AgronomicEvent: This name indicates that the events are related to agronomy, covering a broad range of agricultural activities, including planting, harvesting, and soil treatment.

CropManagementEvent: This name focuses on the management aspect of crops, encompassing events from planting to harvesting, including the application of manure or fertilizer.

FieldManagementEvent: This suggests a focus on managing the field, which could include a variety of events related to crop and soil management.

CropCycleEvent: This name ties directly to the lifecycle of the crop, from planting through growth to harvesting, and includes soil amendment for fertility.

SoilAndCropEvent: This name highlights both critical aspects of the class functionality - managing both the crop lifecycle and soil treatment activities.

_Originally posted by @ew3361zh in https://github.com/RuminantFarmSystems/MASM/pull/1262#discussion_r1488811681_

**Comment by Isgotkowitz** [comment]
@ew3361zh following in the footsteps of the Manure modules, what about `BaseFieldManagementEvent`?

**Comment by ew3361zh** [comment]
I'm on board with that - especially since the naming would make it consistent across modules.
