### ISSUE TITLE
Create an Enum for acceptable units

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1288]
**Is your feature request related to a problem? Please describe.**
Not having units attached to outputs is a problem. Issues #1253 and #1254 have been written to address this. However, when adding units, it would be good to be able to ensure that something is in fact a _valid_ unit.

**Describe the solution you'd like**
Create an Enum that contains every single unit used by RuFaS outputs. This will probably need to be a large Enum, and will probably be fluid for some time as units and outputs are added.
Please update all the add_variable calls to include the units using the newly created Enum. Also, update the OM.add_variable to reject the variable if the received variable's unit is not the type of the newly created Enum.

**Describe alternatives you've considered**
The temporary fix (which is planned to be used for 1253 and 1254) is to use strings to specify what the unit is. The problem with this is that it would be difficult to verify that something is a proper string without have a long list of acceptable strings or a complicated Regex expression or both. By using Enum elements to indicate units, all that is needed to verify that something is a valid unit is to check whether it is a member of the Enum.

**Additional context**

**Comment by Isgotkowitz** [comment]
Blocked until #1253 is completed.

**Comment by allisterakun** [comment]
During grooming:

Sister issue is #1254.
