### ISSUE TITLE
[IM Change] Modify `get_data()` in IM to not throw KeyError

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1334]
## Current Behavior
When the `get_data()` method is called in the Input Manager, it will throw a KeyError if it cannot find any data associated with the address that is passed to it.

## Desired Behavior
Create a new function `property_exists_in_pool()` (probably a better name), that accepts a data_address (string in the format of "a.b.c"), parses the data address and checks if the variable exists in  InputManager.__pool. This function will be a public method so that other modules can directly call this method to find out if a variable exists in the pool,

`get_data()` would call the new method to find out if a variable exists in InputManager.__pool first. if it doesn't exist, get_data() should return None and log an error to the Output Manager.

## Notes
Changing `get_data()` will probably be really simple. ~~But making sure this change is properly accounted for in all methods that call `get_data()` will probably be a ton of work.~~ I don't believe we need to change anything here, because all the current calls to `get_data()` already assume the variable exists in the pool.

**Comment by Isgotkowitz** [comment]
@allisterakun does this issue description seem right?

**Comment by allisterakun** [comment]
> @allisterakun does this issue description seem right?

Updated the description!
