### ISSUE TITLE
[IM] Address issues and features in the Input Manager.

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1335]
## Overview
There are some issues present in the implementation of the Input Manager that have impeded efforts to expand and improve its functionality. This issue outlines some ways in which the Input Manager can be refactored so that future features and improvements can be made more easily and in a more sustainable manner. Also, there are a number of features which could be implemented in the Input Manager that would greatly enhance its functionality and the functionality of RuFaS overall.

## Issues

- [x] #1487
- [x] #1488
- [x] #1489
- [x] #1490

## Features

- [x] #1273 
- [x] #1274 
- [x] #1331 
- [x] #1332 
- [x] #1333 
- [x] #1424

## Additional context
The problems with the Input Manager described here were investigated in issue #1249.

**Comment by allisterakun** [comment]
During grooming:
@Isgotkowitz will break this into smaller issues, current children issues: #1409 and #1410.

**Comment by Isgotkowitz** [comment]
Blocked because the only issue left is #1331, and that is currently blocked.

**Comment by Isgotkowitz** [comment]
Grooming session: all issues in this issue have been completed, closing this issue
