### ISSUE TITLE
Remove class and method name from auto-populated legend keys

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1338]
**Is your feature request related to a problem? Please describe.**
When using regex style filters in making a graph (see below), the automatically populated legend uses the full key name from output manager. This is likely too verbose in most cases. Adding an option to use just the final part of the key name would be ideal. E.g. instead of using `AnimalModuleReporter.report_daily_pen_totals.number_of_animals_in_pen_3_LAC_COW` in the legend, it would just use just `number_of_animals_in_pen_3_LAC_COW`.

**Example filter**
When using: 
```"filters": [
        "AnimalModuleReporter.report_daily_pen_total.*"
      ],
      "title": "AnimalModuleReporter daily_pens"
```

The resulting figure looks like this: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/c5cf395e-7dc4-4075-944e-9aa3033af5e9)

While legend labels like `number_of_animals_in_pen_3_LAC_COW` would still overlap much of the figure (I saw that in another PR @ew3361zh noted a fix for the overlap, which will be excellent), it would be better than the current behavior.

**Additional considerations**
This behavior is particularly troublesome when dealing with similarly grouped keys (like this example) that are dynamic - in this case, the number of pens is not predetermined from the start (though there is a number of starting pens), so we cannot provide a series of specific keys and legends to plot before running a simulation.

**Describe alternatives you've considered**
Some option for the automatically generated legend, e.g. verbose (as it currently is), minimal (the suggestion above), or None, may be useful.

**Comment by allisterakun** [comment]
During grooming:
Alternatively, we can also replace the prefix with the filter used to get the variables.
Or introduce a flag in the report to delete the prefix. This key would default to False.
