### ISSUE TITLE
[IM][Refactor] Make metadata properties uniform to simplify input validation.

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1346]
### What
Currently, the IM loads _and validates_ data differently based on the format of the data source. This can be observed in the following code:
```python
data_type_to_loader_map: Dict[str, Callable] = {
    "json": self._load_data_from_json,
    "csv": self._load_data_from_csv,
}

for file_blob_key, file_details in self.__metadata["files"].items():
    file_path = file_details["path"]

    try:
        file_type = file_details["type"]
        data_loader = data_type_to_loader_map[file_details["type"]]
        input_data = data_loader(file_path)
    except KeyError:
        raise KeyError(
            f"Faulty data type in {file_blob_key}," f"supported types are: {data_type_to_loader_map.keys()}"
        )

    -- snip --

    for metadata_property in metadata_properties.keys():
        -- snip -- 
        if file_type == "json":
            element_counter_and_validity = self._validate_dict_element(
                [metadata_property],
                properties_blob_key,
                filtered_input_data,
                eager_termination,
                element_counter_and_validity,
            )
        if file_type == "csv":
            element_counter_and_validity = self._validate_tabular_element(
                metadata_property,
                properties_blob_key,
                filtered_input_data,
                eager_termination,
                element_counter_and_validity,
            )
```

The IM should be changed so that it only has to differentiate between different input streams when calling `data_loader()`. After that point, when it is validating data, it should not have to take different paths of execution for different types of input streams.

### Why
By eliminating the separate validation paths, the code for the IM is made simpler and less complex. In this way, this issue closely aligns with #1335. Implementing this change will also have the side effect of making the metadata more flexible - more on this below.

### How
To have one set of methods that can validate input data from any input source, the structure of properties for different inputs must be the same. Once these properties have been rewritten, the `if` statements checking the data stream type can be removed.

Here is an example of how the economic properties could be rewritten:
```json
"emissions_properties": {
  "alfalfa_tillage_emissions": {
    "type": "number",
    "description": "The amount of total tonnes CO2-eq generated from alfalfa tillage",
    "minimum": 0,
    "default": 500
  },
  "corn_grain_tillage_emissions": {
    "type": "number",
    "description": "The amount of total tonnes CO2-eq generated from corn grain tillage",
    "minimum": 0,
    "default": 300
  },
  "corn_silage_tillage_emissions": {
    "type": "number",
    "description": "The amount of total tonnes CO2-eq generated from corn silage tillage",
    "minimum": 0,
    "default": 400
  }
}
```
changes to this:
```json
"emissions_properties": {
  "alfalfa_tillage_emissions": {
    "type": "array",
    "description": "The amount of total tonnes CO2-eq generated from alfalfa tillage",
    "properties": {
      "minimum": 0,
      "default": 500
    }
  },
  "corn_grain_tillage_emissions": {
    "type": "array",
    "description": "The amount of total tonnes CO2-eq generated from corn grain tillage",
    "properties": {  
      "type": "number",
      "minimum": 0,
      "default": 300
    }
  },
  "corn_silage_tillage_emissions": {
    "type": "array",
    "description": "The amount of total tonnes CO2-eq generated from corn silage tillage",
    "properties": {
      "type": "number",
      "minimum": 0,
      "default": 400
    }
}
```

A side effect of rewriting the metadata and changing the IM as described above would be that, in some cases, the same input data could come from different streams and would be validated against the same properties.

### Other
See [this comment](https://github.com/RuminantFarmSystems/MASM/issues/1249#issuecomment-1936632693) for more conversation on this issue.

**Comment by ew3361zh** [comment]
Thanks for the write-up, Ed, it's very helpful. I'm reviewing right now but could you say a little more about the last sentence:

> A side effect of rewriting the metadata and changing the IM as described above would be that, in some cases, the same input data could come from different streams and would be validated against the same properties.
