### ISSUE TITLE
Validate default values in metadata beforehand

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1347]
I see one instance in the metadata json where the default value doesn't satisfy the constraints. So, I think it is a good preprocessing step to validate the default values first and then validate the input data. If there is something that needs to be fixed in the input data, we can 'trust' that the replacement default values at least meet the specified constraints. Overall, this also implies that the constraints must be assumed to be valid and verified by the user since we don't have anything else to check them against.

```
"packing_density": {
    "type": "number",
    "description": "Packing Density -- The density of ensiled feed material, kg DM /m3",
    "minimum": 200,
    "maximum": 800,
    "default": 14
  }
```

**Comment by Isgotkowitz** [comment]
This issue is addressed in #1332.
