### ISSUE TITLE
Misalignment in graphs (and reports) due to instantiation of new variables during simulation

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1366]
## Status
This is a problem encountered in #1263, specific to the creation of new pens, and it may extend to other outputs.
When a new output is added to output manager, it causes misalignment in graphs and other outputs, because an assumption that the first entry is on simulation day 0 is incorrect.

**A super-simplified example of the problem**
Assume one runs a simulation for 15 days.
The simulation starts with 4 pens.
A 5th pen is instantiated on day 10 (see logic in #1263).
At the end of the simulation, each output related to pens 0-3 have a length of 15 (or 16, if we're counting day 0).

*The problem:* any outputs related to pen 4 has 10 fewer days, and so there's a misalignment in those outputs.

**Example output from a longer sim**
Note the crude arrows showing shorter line lengths.
![default_animalmodulereporter-daily_pens-05-Mar-2024_Tue_11-10-38](https://github.com/RuminantFarmSystems/MASM/assets/109082924/8caad026-a6e3-4261-b2db-cb788faad1e6)

Note below the hidden rows to show the "ragged" nature of these new pen outputs (this is without the "padding" I instituted in 1263).
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/dac78bde-f539-46f0-9a26-85b7e9ffe236)

So without some note of what the time is at the time of collection, we lose information. (Note in "Yet another solution" that we can already store that in info_map, but that's harder for an end user to access, and lost completely in graphs).

## Intention
We need to ensure that the user is certain of when data was logged in output manager.

**What the above *should* look like** (thanks @Isgotkowitz for the suggestion to show some examples of ideal behavior)
- There are two options I see for the reports/CSVs:
    - Each variable would have its x-axis value printed next to it, so that there would be double the number of columns in that example. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/01703a25-4fbd-45b4-b9f5-4fc38fd1118e)

    - To avoid the duplication inherent in the previous bullet point, there could be a single x-axis that all results are aligned with, e.g. the first column is simulation_day, and every entry in a column is aligned to that axis.
    - However, this would have a problem when printing a mix of monthly and daily variables, since there would be enormous gaps, and would be annoying for those mainly working in Excel.
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/3dd98c67-5eff-492e-ada6-da7b2d0e63b5)

- As for graphs, the end of each of the lines on the graph would all align to the x-axis (in the above examples, they'd align at the end). Then the user can see when the new pens "start" existing. This example is harder to competently mock up, but hopefully this one is easy to imagine.

**Additional problems**
- If a pen (or other outputs) are intermittently recorded, those gaps are also problematic. After chatting with @Isgotkowitz there may be a similar issue in crop and soil, e.g. if corn is grown on days 150-220 of the simulation, 

**Current implementation**
In that PR I (@JoeWaddell) added some janky code that pads out calls to OM to fill in gaps with blanks (still only local). However, this requires an additional set of 5+ lines for each call to output manager, and requires that any new pen-specific outputs are carefully managed.

**Current workaround**
This doesn't solve the problem re: misalignment in graphs, but for reports, when slicing from the last entries, those misalignments are avoided (provided that they aren't reported intermittently).

## Request: in a sentence
Record simulation day alongside every call to the OM variables pool.

**Proposed solution**
Like the new units field, adding simulation_day could be an option when adding variables to output manager. Sometime this addition might not be necessary, so it could also be an optional arg.

**Another solution**
OM could automatically log when in the simulation a variable was added, so it would require no changes to currently implemented calls to OM.

**Yet another solution** Graph and report generators could be enhanced to look for `simulation_day` in `info_map` (if available) to set the x-axis variable.

## Additional thoughts

**Additional benefits**
- Monthly and daily outputs could be plotted on the same figure, since the x-axis would be defined explicitly.
- Multiple points can show up for a single day: e.g. if we're recording individual animal data.
- Would work nicely with #912, since it's an assumption there that the data on the x-axis are aligned such that the first entry is day 0.

**Complications**
- This would require not only changes to OM, but graph generator, report generator, etc, which may be easier said than done.
- This also means more information is being logged to OM. Granted, only an integer, but still: one for each variable. Consideration should be given to a potential increase in file size and simulation time, and whether all of this is particularly useful now or in the future.

**Comment by ew3361zh** [comment]
It would be better to continue working on this issue after #912 is closed.
