### ISSUE TITLE
Fix update of VS in anaerobic digestion and lagoon treatment

### ISSUE THREAD

**Issue by elle-andreen** [RuminantFarmSystems/RuFaS#1368]
This issue is related to Issue #1270: Volatile solids updates in the manure module. Issue 1270 refers primarily to slurry storage outdoor and underfloor methods, whereas this issue will cover anaerobic digestion treatment file, as there are some differences in how volatile solids (VS) should be updated.

## Expected Behavior
In the anaerobic digestion portion of the ADL treatment, we expect that a portion of the manure VS loaded into the digester will be destroyed through the anaerobic fermentation process that occurs inside the digester. Therefore, the VS content of the manure (effluent) leaving the digester and subsequently entering the anaerobic lagoon should be lower than the manure from the reception pit. This ultimately results in lower methane emissions from the anaerobic lagoon.

Additionally, if a separator is employed between the digester and lagoon (i.e., anaerobic digestion and lagoon with separator treatment), the VS content of manure entering the separator (and other nutrients, though this issue focuses on VS) should be updated to reflect VS loss during anaerobic digestion as well. The diagram below depicts both situations.

For example, say a pen's manure VS on one day is 100 kg (already accounting for any emissions lost in housing). Assume we lose 35% of the total VS through anaerobic digestion - the VS content of the manure leaving the digester is now 65 kg. Next, we optionally use a rotary screen separator and remove 40% of the VS - the VS content of the manure leaving the separator is now 39 kg. Thus, the manure entering the anaerobic lagoon on this day contains 39 kg of VS. If we had not used the separator, the manure VS would be 65 kg. 

## Current Behavior
Currently, there is no loss of VS or TS accounted for in the anaerobic digestion treatment file. Additionally, the individual VS fractions are not tracked and updated separately.

## Possible Solution
Please see [the first page of this doc ](https://docs.google.com/document/d/1xKSRiwmKHE0tPmK0C0dkyzXynBt-DBimWSkwsSt4KAU/edit)for further detail on how VS loss in anaerobic digestion should be calculated and updated. The subsequent pages contain some information and subject matter discussion. 

The PR to address this issue should:
1. Institute tracking of degradable and non-degradable volatile solids (VSd and VSnd) in the anaerobic digestion treatment file, and removes tracking of total volatile solids.
2. Institute a conversion factor to convert from CH4 generated to CH4+CO2 generated, i.e., total VSd loss/reduction during anaerobic digestion.
3. Update the content of VSd and total solids in manure effluent leaving the digester, which becomes the input to either a separator followed by anaerobic lagoon, or become the input to the lagoon directly. 

## Diagram
![image](https://github.com/RuminantFarmSystems/MASM/assets/148499778/7f153363-43f5-43ff-8b2e-502018786d0a)

**Comment by tomhuhh** [comment]
**Some additional information related to this issue:** 

The amount of manure volatile solids including degradable and non degradable volatile solids should be updated daily at the anaerobic digestion step.

**Current Behavior**
The amount of manure volatile solids including degradable and non degradable volatile solids is not updated at the anaerobic digestion step.

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/1a8d1dc0-350a-47c8-8d9e-dd295e66fbb9)

**Possible Solution**
Add updates of the amount of manure volatile solids including degradable and non degradable volatile solids to new_daily_output.

**Comment by ltp23** [comment]
I made a [diagram](https://whimsical.com/anaerobic-digestion-and-lagoon-59p6ssMHwsBTcZoyP21xrk) to keep track of the different output objects.
