### ISSUE TITLE
Remove `simulation_engine._run_pre_annual_routines()`

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#137]
## Expected Behavior

The function should have a good docstring.
## Current Behavior

I could not write the docstring as not enough information was available.
## Possible Solution

while refactoring field.py, add docstring here.
## Steps to Reproduce

1.Just look at the code
2.
3.
4.

## Detailed Description

This function was created using the function extraction method while refactoring simulation_engine

**Comment by allisterakun** [comment]
`simulation_engine._run_pre_annual_routines()` is only calling the `routines.annual_feed_routine(self.state.feed)` as a wrapper function. Please remove the wrapper function and update the unit tests accordingly.

**Comment by Isgotkowitz** [comment]
The status of the (old) Feed module needs to be confirmed before addressing this issue.
