### ISSUE TITLE
[CI/CD] Make mypy locally runnable

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1380]
We have integrated mypy in our CI/CD pipeline on GitHub. It is beneficial to make it easy to run mypy locally as well so that we can check the code before submitting PRs. Also, we should unify any configs that is being used. This is very similar to what we did with flake8. @Isgotkowitz may have some transferrable experience here.

With the addition of the mypy type checker to the github workflows, there should be an entry page in the wiki to describe its basic functionality, the error count badge on the readme page, and the later enforcement of making sure each new PR does not introduce more type-checking errors.

**Comment by Isgotkowitz** [comment]
A possible place to start:

Add the following to line 28 of `lint_branch_changes.sh`:
```sh
mypy $changed_files
```

And insert the following at line line 37 of `lint_branch_changes.bat`:
```bat
    mypy %changed_python_files%
```

**Comment by Isgotkowitz** [comment]
Another thing that might help would be to tell Mypy to limit it's check only the source file(s) it is specified to check.
To see what I mean, try running the following two commands and see the difference:
```sh
$ mypy main.py
```
```sh
$ mypy --follow-imports=skip main.py
```
One of them yields a wall of errors that feels very intractable, the other yields just a handful of errors that feel very addressable.

To make this change in the config file, add the following line to the Mypy section of pyproject.toml:
```toml
follow_imports = 'skip'
```

A potential next step, after fixing all errors that Mypy finds with `skip`, would be to change it to `silent` and then work through all of those errors.
