### ISSUE TITLE
Milk production does not change as expected when "Jersey" lactation parameters are updated 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1393]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [X] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status
 

- What is the current behavior?

When "breed" = "JE", there is no change to milk output when changes are made to the second set of brackets for "wood_l". 

When the parameters in the second set of brackets are unchanged and those in the first brackets are updated, the milk output changes (even while breed is still set to "JE"). 

this indicates that RuFaS is using the inputs in the first set of brackets to determine milk production, even when breed is set to "JE". 

To recreate this: (I did these same steps on both Main and Pilot_testing_Dec2023 and had identical results). 

1- run the default metadata with default_animal.json. Record total herd milk and milk/cow/d

 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Total   milk, kg_ver_agg | Milk   per cow/d, kg_hor_ver_agg
-- | --
1311464 | 41.38274

</div>

</body>

</html>

(I used the filters:            
```
{
            "name": "Total milk, kg",
            "filters": ["AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production"],
            "vertical_aggregation": "sum",
            "slice_start": -365
           },
           {
            "name": "Milk per cow/d, kg",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production",
                "AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"
            ],
            "horizontal_aggregation": "division",
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production",
                "AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"
            ],
            "horizontal_first": "true",
            "vertical_aggregation": "average",
            "slice_start": -365
           },
```

2. update "breed" to "JE", with no other changes. Record the total + per cow milk production. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Total   milk, kg_ver_agg | Milk   per cow/d, kg_hor_ver_agg
-- | --
1309829 | 41.33305

</div>

</body>

</html>

3. With Breed still set to "JE", set the second set of parameters for "wood_l" to 0's 

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/237ff712-6ea1-4f2c-a103-43159853470d)

Record total milk and milk/cow/d - again unchanged

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Total   milk, kg_ver_agg | Milk   per cow/d, kg_hor_ver_agg
-- | --
1304592 | 41.18463

</div>

</body>

</html>

4. Set the second set of parameters back to defaults, and update the first set of parameters to 0's

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/8f09744f-ff3e-4073-8128-7099b3c6e89a)

Record total milk and milk/cow/d: 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Total   milk, kg_ver_agg | Milk   per cow/d, kg_hor_ver_agg
-- | --
15843.85 | 0.494662

</div>

</body>

</html>

-->

## Intention

It is expected that milk for Jersey herds will change when parameters in the second set of brackets change. 

This is only necessary because it is user expectation. I'm not actually sure why they need separate spots for inputs, unless RuFaS uses different equations for the different breeds but I'm not aware of that. 

- Why is this change necessary?

It is very frustrating when there is a disconnect between the inputs I think I am giving RuFaS (2nd set of brackets) and the effect on the outputs (i.e. RuFAS is ignoring my input and using a different set of inputs).  

You can achieve the needed milk production control by using the first set of brackets even for Jersey inputs, as long as the user knows that is the necessary workaround.

**Comment by tomhuhh** [comment]
Following up on this issue- I tested with the default input files on main and encountered the same issue that Julie reported, which is when setting the breed to 'JE' and lactation curve parameters to 0, the daily milk yield that I got is ~40 kg/d/animal. 

So what I found is that the self.breed is correctly set to 'JE' in the animal initialization file. When 'simulate_animals' is set to True in the config input file, the self.breed in the cow.py file still gives 'HO', which is incorrect.  

My thought is that the animals are not initialized correctly when the breed is switched from 'HO' to 'JE'. 

This issue still needs more investigation.

**Comment by tomhuhh** [comment]
Hi Julie @jadamchick ! After chatting with Allister, I believe we will just need to re-initialize the animal database by using the code below to make the Jersey selection work. 

` python3 main.py -I -s `

**Comment by YijingGong** [comment]
I am just thinking about this issue after reading Haowen's comments. 
Then would it be worthwhile to include also Jersey animals in the animal database (animal_population.json)? Because it would take very long to re-generate the animals in the animal_population.json (> 50MB). (our original purpose for having this animal_population.json is to avoid re-generating the big pool every time we run the model)

**Comment by tomhuhh** [comment]
For future reference: 

I did not initialize animals by myself, but from what Allister told me, it only took him under 20 minutes to generate that file. With a faster computer, it should take even shorter (~ 5 minutes). 

Also Allister mentioned it is not possible to have both Holstein and Jersey cows in the same file with the current set-up unless we edit the file manually which may cause other unforeseen issues.

One thought is that we could start to think about if we need to generate a new file with Jersey animals only or how to make the two files (Holstein and Jersey) into the same format (per my conversation w/ Yijing). 

Thanks!

**Comment by jadamchick** [comment]
Thanks for looking into this @tomhuhh! 
I agree with Yijing that it's not ideal, but good to understand the root cause. 
Just to make sure I'm clear: we need to initialize animals every time we run a Jersey herd? So if I need 4 simulations of a 8000-cow Jersey herd, I will need to re-initialize those animals before each run?

**Comment by tomhuhh** [comment]
Great question! Thanks Julie! 

I think we should just need to initialize the herd once before running the replicate simulations for one farm.  

> Just to make sure I'm clear: we need to initialize animals every time we run a Jersey herd? So if I need 4 simulations of a 8000-cow Jersey herd, I will need to re-initialize those animals before each run?

This is just my understanding of the workflow. Hope it helps. Thanks!

**Comment by jadamchick** [comment]
Hi, update here- 
I tried running herd c2f22 on pilot_testing_Dec2023 as Haowen said (-I -s). It simulated smoothly (5000/5000 in 3:29), but then ended the simulation with approximately 1 bajillion errors (give or take :)) along the lines of: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/796d9f33-ec3a-4c2f-871a-55fed0d8bfa2)

Is this user error on my part? @allisterakun @tomhuhh 
thanks!

**Comment by KFosterReed** [comment]
> For future reference:
> 
> I did not initialize animals by myself, but from what Allister told me, it only took him under 20 minutes to generate that file. With a faster computer, it should take even shorter (~ 5 minutes).
> 
> Also Allister mentioned it is not possible to have both Holstein and Jersey cows in the same file with the current set-up unless we edit the file manually which may cause other unforeseen issues.
> 
> One thought is that we could start to think about if we need to generate a new file with Jersey animals only or how to make the two files (Holstein and Jersey) into the same format (per my conversation w/ Yijing).
> 
> Thanks!

I think Haowen's idea to have two separate files for the animal population is on the right track. In theory, it would mean having two json files for the animal population. For example one could be `animal_population_holstein.json` and the other could be `animal_population_jersey.json`

this doesn't solve Julie's errors above which looks like somehow all of the jersey animals have invalid attributes?

**Comment by allisterakun** [comment]
Hi

> Hi, update here- I tried running herd c2f22 on pilot_testing_Dec2023 as Haowen said (-I -s). It simulated smoothly (5000/5000 in 3:29), but then ended the simulation with approximately 1 bajillion errors (give or take :)) along the lines of: ![image](https://private-user-images.githubusercontent.com/146877580/314159910-796d9f33-ec3a-4c2f-871a-55fed0d8bfa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDMyMTIsIm5iZiI6MTcxMDk0MjkxMiwicGF0aCI6Ii8xNDY4Nzc1ODAvMzE0MTU5OTEwLTc5NmQ5ZjMzLWVjM2EtNGMyZi04NzFhLTU1ZmVkMGQ4YmZhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMzU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2I5ODc2NWM0ODdhODg5OTdjZTcyNjRhMTRiYmQ2YmUyY2ZjZjIyYWUyNmUxYTM2NDVjYzEwYjcwZDU1ZTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xVh0nokJpUHjIRVx7UUowCATLOko6un1gnvpPcNhE0k)
> 
> Is this user error on my part? @allisterakun @tomhuhh thanks!

I am looking at this error, I believe this is probably due to some miscommunication in the update of the reproduction methods in the animal module. Can I please clarify the possible input values for the following variables:

1. For `heiferIIs`, `heiferIIIs`, `cows`, and `replacement`: what is the acceptable values for `tai_method_h` and `synch_ed_method_h`?
    1. The currently acceptable values for `tai_method_h` are `md5CG2P` or `md5CGP`. It seems that the animal module is updated to expcet `5dCG2P`, `5dCGP`, and user-defined, but the metadata is not updated accordingly.
    2. For `synch_ed_method_h`, the currently acceptable values are `2P` or `CP`, but the input data seems to be passing in `5dCG2P` (as one of the expected values)
4. For `cows` and `replacement`: what is the acceptable values for `repro_program`?
    1. The currently acceptable values for `repro_program` are `ED` or `TAI`. Missing the `ED-TAI` option.

**Comment by jadamchick** [comment]
Hi Allister,
I'm not sure if this answers this question! But those values no longer exist as animal inputs since the repro refactor (`tai_method_h`, `synch_ed_method_h`, `repro_program`). I will tag @ltp23 in here in case your question needs a more nuanced answer :)

**Comment by jadamchick** [comment]
I think Allister already has this figured out, but just to confirm -- I get this same error even when running the default herd on the Main branch (with breed = "Ho")

**Comment by allisterakun** [comment]
> I think Allister already has this figured out, but just to confirm -- I get this same error even when running the default herd on the Main branch (with breed = "Ho")

Yes I believe we just need to update the metadata and the animal generation (making sure that the aniaml_population and the metadata, along with the expected values in the animal modules are in sync) I tried generating a herd with all `JE` cows and runner simulation on those (and changes some metadata properties), the simulation seems to run and complete without any complains.

**Comment by KFosterReed** [comment]
I did a little poking around in the breed and birthweight assignment this morning and I think part of the problem seems to be that the breeds are not changed when an animal is initialized so if they are a Holstein in the initialization database, they remain a holstein and then give birth to Holstein calves

**Comment by jadamchick** [comment]
> > I think Allister already has this figured out, but just to confirm -- I get this same error even when running the default herd on the Main branch (with breed = "Ho")
> 
> Yes I believe we just need to update the metadata and the animal generation (making sure that the aniaml_population and the metadata, along with the expected values in the animal modules are in sync) I tried generating a herd with all `JE` cows and runner simulation on those (and changes some metadata properties), the simulation seems to run and complete without any complains.

Thanks @allisterakun . I'm not clear from this -- should I also be able to generate a herd with all JE cows? Or you are saying you were able to do that after making modifications to the metadata properties on your local branch, and that is something that needs to be updated on main? If so, should I create a separate issue for that, or is it something you are already working on? 
Happy to chat more about this if it would be helpful! 
Relatedly -- is there documentation that describes more about the animal generation process? I'd love to understand it a little better than I do now. Thanks!

**Comment by KFosterReed** [comment]
It seems like there are some values in the metadata animal_properties file that need to be updated. I don't understand why the body weight variables are giving an error but I also got that same error when I tried to initialize a jersey herd. However, when I saved the animal file and then tried to run a simulation that referenced that new jersey file, I got errors associated with the repro inputs including the following inputs: 
`repro_program` - for cows only
`tai_method_h` - for heiferIIs, heiferIIIs, and cows
`synch_ed_method_h` - for heiferIIs, heiferIIIs, and cows`

@allisterakun are you able to work on this today or this week?

**Comment by Isgotkowitz** [comment]
@jadamchick is this issue good to close out? I have tried running several different simulations, changing the breed, Wood Parameters, and herd file and I think the resulting changes are correct.

**Comment by jadamchick** [comment]
> @jadamchick is this issue good to close out? I have tried running several different simulations, changing the breed, Wood Parameters, and herd file and I think the resulting changes are correct.

Yes! The initial issue seems to have resolved (milk production now seems to respond to the appropriate set of lactation curve parameter input brackets, according to which breed is specified in the animal.json). And we have addressed and updated the barriers to generating a new animal population when needed. Thanks everyone!
