### ISSUE TITLE
Mypy error raised when adding function name with `__init__` in `info_map`

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1394]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [x] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

Mypy error raised when adding function name with `__init__` in `info_map`

![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/d333ab89-7d58-4879-9606-9f53be1e481f)

## Intention

Either this shouldn't be flagged as an error, or we write the `self.__init__.__name__` in a different way.

## Request

One option is "telling" mypy to ignore this error throughout the codebase, but another is simply changing the way we enter data when using `__init__`, e.g. either manually writing the resulting string, or baking the method into OutputManager itself (e.g. recognizing where it was called automatically).

**Comment by Isgotkowitz** [comment]
Grooming session solution: hardcode name of __init__ as "__init__" as a string when adding it to Info maps.
