### ISSUE TITLE
[IM] Reviewing recent changes to IM and making plans for housekeeping tasks

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1401]
This issue mostly focuses on figuring out what housekeeping tasks that IM would need to improve further. Due to some significant additions to the IM (i.e., mofidiable data at runtime, array validation, and unifying json and csv formats), it is good to take a step back and review how those new changes fit together and what can be streamlined and refactored.

- [x] Remove the `_dict_type_validator()` method and use `_validate_input_by_type()` directly in `_populate_pool()` and `_add_variable_to_pool()`, and fix broken tests.
- [x] Check test coverage and improve it.
- [ ] Review the interaction between the two features - modifiability at runtime and array validation.
- [ ] Review the `called_during_initialization` parameter.
- [ ] Review the usage of the ElementsCounter and ElementState classes to see if it should be integrated into the InputManager class.
- [ ] `_add_variable_to_pool()` is too complex according to flake8.
- [ ] ...

**Comment by Isgotkowitz** [comment]
This task is strongly tied to #1335.

**Comment by ltp23** [comment]
Closed because the description is unclear.
