### ISSUE TITLE
Update inputs to anaerobic lagoon in the anaerobic_digestion_and_lagoon.py 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1408]
We want to update the inputs to anaerobic lagoon in the `anaerobic_digestion_and_lagoon.py` so that they are taking in the accumulated outputs and not the daily inputs.  

## Expected Behavior

Anaerobic lagoon takes in accumulated values instead of daily values as the input. 

## Current Behavior

Anaerobic lagoon takes in daily values as the input. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/8b797b19-5338-4244-aafa-a0a552ee60f6)

## Possible Solution

Update the input path. 

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by elle-andreen** [comment]
Link to Google doc for further discussion and information: https://docs.google.com/document/d/1xKSRiwmKHE0tPmK0C0dkyzXynBt-DBimWSkwsSt4KAU/edit?usp=sharing
