### ISSUE TITLE
[OM] Improve on the handling of data origins info

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1416]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [x] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

Currently, when using json output filtering, the data origins info is extracted from the info maps and paired with its corresponding value (PR #1404). Also, this process is coupled with the command line option `-i`. When the user disables the info maps, the data origins info is also disabled. 

## Intention

We want to improve data origins info further by customizing it based on user's choices. The user can decide the format of the data origins-value pairs and whether to include this information at all. 

When the data origins-value pairs are included, it is probably best to not include `values` field because the values are already part of the data origins-value pairs.

## Request

Issue #1432 
- [x] Change the output json key from `detailed_data_origins` to `detailed_values`
- [x] Currently the way to produce a json output is to make a filter file in the `.txt` format. We probably want to keep this option to minimize disruption and allow the `.json` format as well. With the filter file in the `.json` format, it is easier to make customization.

Issue #1433
- [x] To enable/disable this whole feature, allow its specification in the filter file by adding an option like: `"origin_label": "selected_option"` (where "selected_option" is one of the following — `true and report origins`, `true origin`, `report origin`, `none or nothing or disabled` (default)). This would enable the decoupling from the command-line option `-i` that turns on/off info maps.
- [x] Probably create an Enum class that handles those different options.
- [x] Change the data origin-value pairs from `[["[true.origin]->[report.origin]", value]]` to a stringified version that matches the specified option like this `"[true.origin]->[report.origin]: stringied_value units"`.
- [ ] When this whole feature is used, consider whether it is possible to remove the `values` field in the json output. Be extra careful with this since it may affect the graph and report generators.
- [x] Update the wiki entry for output manager.

Issue #1514 
- [x] Include units directly in the csv column names.
- [x] Remove extra columns like `.prefix`, `.units`.

Issue #1515 
- [x] Include units in graphs when specified by the user.
- [x] To make the formatting of units more consistent, consider reusing the code for formatting units.
- [x] Update wiki

Issue #1516 
- [x] Include units in the reports when specified by the user.
- [x] To make the formatting of units more consistent, consider reusing the code for formatting units.
- [x] Make sure the functionality `graph with report` still work like before.
- [x] Update wiki

**Comment by ltp23** [comment]
Need to rewrite this issue by splitting it into smaller issues.

**Comment by ew3361zh** [comment]
All the sub issues in this parent mega issue have been successfully closed.
