### ISSUE TITLE
[GH Actions] Combine linting action yaml with the main action yaml file

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1451]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [x] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

With PR #1448 merged, we now have three yaml files for the following — pytest-mypy combo (`combined_pytest_mypy.yml`), linting (`lint_flake8.yml`), and sphinx (`sphinx.yml`). Preferrably, this issue should be done after resolving any issues with the Black formatter.

## Intention

For this issue, we want to combine the linting action into the combo yaml file `combined_pytest_mypy.yml`. We hope to be able to save more time and resources as we consolidate the github actions incrementally.

## Request

- [ ] Make sure the linting action works first. 
- [ ] Combine the three actions - mypy, pytest, linting - into one yaml file. Update the filename.
- [ ] Check the badges on README to see if things work: mypy, coverage percentage.
- [ ] Check the log messages when running actions.
- [ ] Check the black formatting commit.

**Comment by ew3361zh** [comment]
@ltp23 would you be okay with closing this? I believe this is covered in PR #1470.

**Comment by Isgotkowitz** [comment]
Closed by #1470
