### ISSUE TITLE
[GH Actions] Combine sphinx action yaml with the main action yaml file

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1452]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [x] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

With PR #1448 merged, we now have three yaml files for the following — pytest-mypy combo (`combined_pytest_mypy.yml`), linting (`lint_flake8.yml`), and sphinx (`sphinx.yml`). We may have only two now if the issue #1451 has been resolved.

## Intention

For this issue, we want to first fix any lingering issue with building sphinx docs and then combine the sphinx action into the main yaml file. We hope to be able to save more time and resources as we consolidate the github actions incrementally.

## Request

- [ ] Make sure the sphinx action works first. 
- [ ] Combine the sphinx action into the main yaml file. Update the name of the main yaml file.
- [ ] Enable the Sphinx workflow manually on github actions page.
- [ ] Check the badges on README to see if things work: mypy, coverage percentage.
- [ ] Check the log messages when running actions.
- [ ] Check the black formatting commit.
- [ ] Check the `docs` folder.

**Comment by Isgotkowitz** [comment]
Sphinx will be run manually when updates are made.
