### ISSUE TITLE
[GH Actions] Automate the cleanup of old actions results

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1454]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

The number of GH actions workflow runs can build up really quick and their logs get expired after a while anyway.

## Intention

So, to tidy things up, we probably should either write a script to run locally or incorporate the automated task somehow into one of the main yaml.

The command I use to delete the logs locally is

```
# Replace the workflow name. List the last 800 runs and keep the latest 300.
# The rate limit for this is 5000 requests per hour. It costs more than 1 request per deletion.

gh run list --limit 800 --workflow 'Test and Coverage' --json databaseId,createdAt | jq -r 'sort_by(.createdAt) | .[:-300] | .[] | .databaseId | @sh' | xargs -I{} gh run delete "{}"
```

## Request

- [ ] There should be a step that specifies the logic of what we want to keep: how many results or how old they are.
- [ ] Either write a script or update the main yaml file.
- [ ] Check the results on the github actions page to see the changes in the counts. make sure the intended workflow is enabled.

**Comment by allisterakun** [comment]
This issue is closed as not planned during the grooming session.
