### ISSUE TITLE
Negative Parity Indices in Herd Initialization

### ISSUE THREAD

**Issue by yangcatherine** [RuminantFarmSystems/RuFaS#1457]
When I run the simulation on the farm-specific-lactation-curve branch, upon initializing the herd, negative parity indices are generated, which gives us a buy with our code because we use the parity index to access the parameter values from the dictionary. 

## Expected Behavior
Biologically, negative parities don't really make sense. 

## Current Behavior
By using a negative index, the simulation ends in an error. 

## Possible Solution
For now, we are just checking that if the parity index is less than 0, we will set it to 0. But this is more of a bandaid solution.

**Comment by Isgotkowitz** [comment]
Grooming session: with the completion of the lactation curve module, the parity index will no longer be used at all and can be removed entirely from the `Cow`. A new issue dedicated to removing this attribute will be written.
