### ISSUE TITLE
Make the breakdown of reasons for non-repro/production related culls a user input instead of hard coded

### ISSUE THREAD

**Issue by krb78** [RuminantFarmSystems/RuFaS#1459]
**Is your feature request related to a problem? Please describe.**
RuFaS used to have 2 different disease related culling inputs: 1) the ability to change the likelihood a cow was culled (removed from the herd) on a given day of lactation and 2) the % of total non-reproduction/milk production related culls associated with a given reason (ie. 16% feet and legs, 24% mastitis, etc.). The information requested in the first culling input is an array of probabilities adding up to 100%, with each probability corresponding to a specific days in milk. The second culling input was just a single number. Through a variety of refactors, the 1st input is the only one that still exists as changeable by the user and the 2nd one is hard coded. However, if we consider what data is accessible to users, the easier to obtain data is the single % (item 2), not the array of probabilities (item 1). 

**Describe the solution you'd like**
I would like to see user inputs associated with the total % probability that a cow is culled for a specific reason. From the paper we used they are as follows: 
Feet and legs 16.33
Injury 28.83
Mastitis 24.39
Disease 13.91
Udder  6.45
Unknown  10.09
These can exist as the user visualized defaults, but I would like to see them be editable by the user. 

**Describe alternatives you've considered**
Truthfully, I haven't considered very many alternatives to this, because I think it should be relatively easy to lift these from being hard coded to being user inputs but I'm open to suggestions.

**Comment by PooyaHekmati** [comment]
Target deadline: end of April 2024.
