### ISSUE TITLE
Errors occur when new animal population files are created. 

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1463]
We are not able to create a new animal population file directly from initializing a new herd for two reasons:

1. The animal population metadata properties are out of date
2. Once the meta data properties are fixed, then there are occasional runtime errors related to either the ReproStateEnum or the body_weight_history.

## Expected Behavior
We should be able to save the initialized herd population file as described in the RuFaS Command Line Arguments and then use that saved population file as the input to initialize a new herd

## Current Behavior

There are two barriers to this success: 

1. The metadata properties for the repro programs need to be updated
2. There are occasional errors that arise that stop the simulation. These two errors are in the attached files:

[c2f9_jersey_errors_27-Mar-2024_Wed_12-03-59.json](https://github.com/RuminantFarmSystems/MASM/files/14782111/c2f9_jersey_errors_27-Mar-2024_Wed_12-03-59.json)
[c2f9_jersey3_errors_27-Mar-2024_Wed_13-48-29.json](https://github.com/RuminantFarmSystems/MASM/files/14782112/c2f9_jersey3_errors_27-Mar-2024_Wed_13-48-29.json)

## Steps to Reproduce

To replicate the first metadata error
1. Run a simulation and save the animals (--save_animals) and specify a directory that you can use as an input file (--save_animals_dir)
2. Reference that filepath in the animal_population filed in the metadata file

To replicate the second, runtime error
4. On the JerseHerd_hotfix_pilot_testing_Dec2023 branch, run the c2f28_metadata or c2f9_metadata files

## Context (Environment)
This is preventing us from running farms that have Jersey breed animals which is critical for our success in the FARM ES collaboration

I believe there were some changes made in the repro refactor that changed some of the repro metadata inputs and potentially the animal reproduction attributes that are related to this. 

## Detailed Description
When an animal population file is saved, the animals in that population should be able to initialize a new simulation without manually modifying the metadata or the population file.

**Comment by ew3361zh** [comment]
Allister is most familiar with this topic.
Loi has made some initial progress on addressing this issue within PR #1464.

**Comment by Isgotkowitz** [comment]
@Isgotkowitz the "Trying to exit the PREGNANT repro state" error can reproduced in c2f28 with the random seed 2401192515 and looking at cow with id 2150

Current fix idea: when a cow is init'ed, check if it is pregnant. If it is, have the `_repro_state_manager` switch to pregnant state immediately.

**Comment by Isgotkowitz** [comment]
@KFosterReed I have been able to fix the error related to the `ReproStateManager` being in the `PREGNANCY` state, but have been unable to reproduce the error related to body_weight_history. This is mostly due to C2F9 exhausting my computer's memory when I try to run it. Are you able to reproduce it still, or do you think at this point it is stale?
