### ISSUE TITLE
[IM] Consolidate methods for adding data to the Input Manager at runtime

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1489]
The various methods for adding or replacing input to the Input Manager at runtime should be consolidated into a single method.

## Expected Behavior

There should be one method available for adding input to the Input Manager at runtime (i.e. mid-simulation), and this method should be capable of handling all different types of data that RuFaS needs to add to the Input Manager during runtime.

## Current Behavior

Two different methods are present in the Input Manager for adding data during runtime, `add_dict_variable_to_pool` and `add_tabular_data_to_pool`, which respectively add dicts and lists to the Input Manager.

## Possible Solution

Consolidate `add_dict_variable_to_pool` and `add_tabular_data_to_pool` into a single method. Also ensure that this new method will be capable of adding all different types of data that RuFaS needs to add to the Input Manager during runtime.

Note that this issue is strongly tied to #1273.

**Comment by allisterakun** [comment]
It is being sized as Medium for testing purposes. Please make sure this PR is properly tested, as the consequences/impact of a defect will be significant. 
The actually work required for this issue is somewhere a S or XS.
