### ISSUE TITLE
[Weather] Write up design doc for proposed changes to simplify Weather data structure.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1507]
As noted in #753, the structure of the weather data is too complex for ease of use with RuFaS in its current foramt. It should be refactored but may need a design document to cover all the affected aspects.

## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [x] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

Currently, all the weather data are stored in separate 2D arrays of the following format:
variable_name: [year_num][day]
Where variable_name is the variable of interest (e.g., T_max => maximum temperature of the day), year_num is the difference between the year of interest and the starting year (e.g., for a simulation starting in 2019, the year 2020 would be index 1), and finally the Julian date.

## Intention

The current weather data structure introduces unnecessary complexity, and it should be flattened or completely reformatted.

## Request

Start with a design document.
As a starting point, here are some suggestions from ChatGPT as to how to approach the refactor of the current data structure:

## 1. Flattening to a Single DataFrame
One effective approach is to flatten your 2D arrays into a single pandas DataFrame, where each row represents a day, and columns represent the different weather variables for that day. Additional columns for the year, Julian day, and a constructed date column can make analysis more intuitive.

Steps to Flatten:

Convert 2D Arrays to DataFrame: Convert each 2D array into a DataFrame with year and day as indices.
Merge DataFrames: Merge these individual DataFrames into a single DataFrame where each variable becomes a column.
Add Date Information: Calculate the actual date from the year and day information for easier time series analysis.

Pros:

Simplifies access to the data by consolidating it into a single structure.
Facilitates operations like filtering, aggregation, and visualization.

Cons:

Memory Usage: A single DataFrame containing all variables for all days and years can become large, especially for long-term simulations or high-resolution data, potentially leading to high memory usage.
Performance: Operations on a very large DataFrame can be slower, especially if not properly indexed.
Complexity in Handling Different Data Types: If your weather data includes various types (e.g., temperatures as floats, weather conditions as strings), managing these within a single DataFrame can sometimes complicate processing and visualization.

## 2. Using MultiIndex DataFrame
If preserving the year and day structure is essential for your analysis, you can use a pandas DataFrame with a MultiIndex consisting of year and day. This approach keeps the hierarchical structure but in a more flexible and powerful format than raw 2D arrays.

Pros:

Retains the hierarchical structure of the data, making certain types of queries and analyses more intuitive.
Efficient storage and access for data that naturally fits a multi-dimensional model.

Cons:

Complexity: Working with MultiIndex DataFrames can be more complex, especially for users unfamiliar with pandas' advanced indexing features.
Performance Issues: While pandas is highly optimized, complex indexing and slicing operations on MultiIndex DataFrames can sometimes be less performant than simpler structures, particularly with large datasets.
Difficulty in Visualization: Visualizing data directly from MultiIndex DataFrames may require additional steps to reset indexes or pivot the data into a more graph-friendly format.

## 3. Time Series Format
For many applications, especially those involving time series analysis, converting your data into a time series format with a DateTime index can be particularly useful. This format can simplify operations like resampling, filtering by date, and plotting time series data.

Conversion to Time Series:

You can use the flattened DataFrame from the first approach and set the Date column as the DataFrame's index.

Pros:

Ideal for time series analysis, making it easy to perform operations like resampling, window functions, and time-based indexing.
Direct support for plotting and analysis using time series libraries.

Cons:

Limited by Time Granularity: If your simulation requires analysis across multiple time scales (e.g., daily, monthly, yearly), you might need to perform additional transformations or aggregations.
Assumes Regular Time Intervals: Time series analysis often assumes data points are spaced at regular intervals, which might not always be the case (e.g., missing days, leap years).
Date Index Overhead: While efficient for time-based queries, maintaining a DateTime index incurs overhead, potentially impacting memory usage and performance for very large datasets.

**Comment by Isgotkowitz** [comment]
The design doc for Weather must fully capture all changes and requirements of the Weather class as a whole, as listed in #1510.

**Comment by ew3361zh** [comment]
From retro session 5/22: @allisterakun did a refactor of the Time module on which Weather is heavily dependent. To prevent issues before the Weather refactor is complete, Allister added several properties to the Time class which should be deprecated once the Weather refactor is complete. These properties are: `years`, `start_year_int`, `start_day`, `end_year_int`, `end_year`.

These are documented in PR #1643.

**Comment by ew3361zh** [comment]
Weather design doc:
https://docs.google.com/document/d/1QUTRhsaMCJZRekaHSY05hPyxMoRl-Xw4Wq9xrHXwn4A/edit?usp=sharing

Please review @Isgotkowitz @allisterakun

**Comment by allisterakun** [comment]
> Weather design doc: https://docs.google.com/document/d/1QUTRhsaMCJZRekaHSY05hPyxMoRl-Xw4Wq9xrHXwn4A/edit?usp=sharing
> 
> Please review @Isgotkowitz @allisterakun

Great work, Niko. As mentioned during the work-together meeting, I have no further issues. Maybe make a diagram for the Weather Functional requirements.

**Comment by ew3361zh** [comment]
Diagram has been added for functional requirements section.

**Comment by Isgotkowitz** [comment]
I think it looks good @ew3361zh. I had a few minor comments and things to consider, but the doc is definitely good enough for us to start taking the next steps with the Weather refactor.

**Comment by ew3361zh** [comment]
Have addressed all feedback from Ed and Allister and will be closing this issue out to make way for next steps in Weather in the subsequent sprint!
