### ISSUE TITLE
[IM] Add feature to compare two metadata properties

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1511]
In a metadata, we reference a `properties` file. Here we want to add a function that makes it possible to compare two different properties files. Since these are `json` files, consider using existing tools and libraries to make it easier and faster.

**Comment by ew3361zh** [comment]
@PooyaHekmati can you explain this a little further? What would the comparison be used for? Is this envisioned as another gnu arg that would output a list of differences?

**Comment by PooyaHekmati** [comment]
The functionality implemented in PR #1557 should be in `input_manager.py`. A follow-up PR is needed to move the code to were it should be.
