### ISSUE TITLE
[IM] Add feature to generate list of inputs

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1512]
`OutputManager` automatically produces a file containing all the output variables. Here we want to replicate the functionality for inputs.

**Comment by PooyaHekmati** [comment]
Target deadline: end of April

**Comment by ew3361zh** [comment]
Adding this thread from Slack for context. It is the origin story of this issue.


![Image](https://github.com/RuminantFarmSystems/MASM/assets/70217952/bbfdf8b9-e4cb-474d-85a4-8786a408c94a)



![Image](https://github.com/RuminantFarmSystems/MASM/assets/70217952/883cec28-e229-48e0-8b53-09094345e1cc)

**Comment by PooyaHekmati** [comment]
PR 1555 is violating IM requirement 6: `IM must report its activities’ logs to Output Manager’s logs pool.` There are no logs for the attempts to save CSV files. A follow-up PR is needed.

**Comment by PooyaHekmati** [comment]
Reverted #1597 via #1605 due to incorrect docstrings.
