### ISSUE TITLE
[OM] Include units in graphs when specified

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1515]
This is part 6 of the issue #1416 

Part 6 
- [ ] Include units in graphs when specified by the user.
- [ ] To make the formatting of units more consistent, consider reusing the code for formatting units.

**Comment by ltp23** [comment]
@JoeWaddell @tomhuhh @jadamchick 

Please provide suggestions/preferences (if any) on how you want to display units in graphs.

**Comment by allisterakun** [comment]
During grooming session:
If info_map is not excluded, the units will be passed to the GraphGenerator in the info_map section, and we can extract the units from there.
If info_map is excluded, no units will be passed to the GraphGenerator. Therefore, we won't put units on graphs.
