### ISSUE TITLE
[OM] Include units in reports when specified

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1516]
This is part 7 of the issue #1416 

- [ ] Include units in the reports when specified by the user.
- [ ] To make the formatting of units more consistent, consider reusing the code for formatting units.
- [ ] Make sure the functionality `graph with report` still work like before.

**Comment by ltp23** [comment]
@JoeWaddell @tomhuhh @jadamchick 

Please provide suggestions/preferences (if any) on how you want to display units in reports.

**Comment by tomhuhh** [comment]
Hi Loi! Thanks for bringing this to our attention. It seems to me that the variables that I've been working with all have their units specified (either in variable names or info maps), even though some may not be correct. Do you have any specific examples of the options for displaying units? Also, are you referring to the report generated by the txt filter, the report generated by the json filter, or the graphic report? Thanks!

**Comment by ltp23** [comment]
Thanks @tomhuhh. I made a separate issue for each output format type (#1434, #1514, #1515, #1516) , but you can make suggestions on any of them. Julie did mention a good example of auto-including the units in the report column names. I will try to always somehow include a flag to turn the features on and off.

**Comment by allisterakun** [comment]
During grooming session:
If info_map is not excluded, the units will be passed to the ReportGenerator in the info_map section, and we can extract the units from there.
If info_map is excluded, no units will be passed to the ReportGenerator. Therefore, we won't put units on graphs.

**Comment by allisterakun** [comment]
> During grooming session: If info_map is not excluded, the units will be passed to the ReportGenerator in the info_map section, and we can extract the units from there. If info_map is excluded, no units will be passed to the ReportGenerator. Therefore, we won't put units on graphs.

This issue is being sized as L because through the process of aggregation, new complex units can emerge. The RG code should be able to handle this. 
For example, if variables `foo` and `bar` are aggregated through division, the units of `foo / bar` will be `x/y` where `x` is the unit of `foo`, and `y` is the unit of `bar`.
