### ISSUE TITLE
[Time] Refactor Time class

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1522]
Adapt the current `Time` class to be passed around the model and regulated/advanced via SimulationEngine. `Time` should be the single-source of truth for tracking and measuring time in RuFaS.

## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [x] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

This issue is really 2 issues that should be done together because they depend on one another:
Step 1:
- [ ] Rework SimulationEngine to be the central manager of the Time class between other modules. This likely needs to be folded into what's being done with #1411.
- [ ] Issue #1533 - update all references to time to use the newly refactored `Time` class (advise the PR addressing this issue to be branched off the PR addressing issue #1522 (this issue) after the PR solving 1522 is approved).

## Intention

All cases where time needs to be managed or tracked should utilize the newly refactored `Time` class.  

## Request

1. The `Time` class should be refactored to be clearer and references to it throughout the model should be more uniform (e.g. not passing parts of the Time class but the whole class so references are clearer as to where that data is coming from and how it's regulated).
2. Currently Time is only advanced in `SimulationEngine` in its `_advance_time()` method and `_run_post_annual_routines()` method. We want to be sure `Time` is not advanced anywhere else.
3. Update all current references to `Time` to ensure compatability and proper function with the newly refactored `Time` class.
4. Testing should be updated.

#### Additional Information

If refactoring Time AND updating all references to time (those currently using the current `Time` class and those using alternate avenues of simulation/calendar time) seems like too much for one single issue, we can break this up into two issues that could be done in tandem. 

In the first issue the refactor happens. 
The second issue is then branched off that refactor before the PR to address the first issue is merged into main. 
This will help ensure it's properly introduced and tested and accounted for.

Seems good to have 1 person do everything outlined in this issue within one Sprint if possible.

**Comment by Isgotkowitz** [comment]
Grooming session: these issues need to be reworked, so that Time is not designed as a singleton. Tagging @ew3361zh
