### ISSUE TITLE
Graph generation exception too vague

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1532]
## Urgency Level

- [ ] Wishful: the issue should not be prioritized over any others

## Expected Behavior

Graph generation exception should give the name of the filter that caused the exception. 

## Current Behavior

![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/197a564e-8df7-494c-9ba0-c792278cfde6)
and 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/30e4a94c-8f59-4a54-9d0d-1ea64cb359b0)

Neither give an indication of which filter is causing the problem.

## Possible Solution

Reporting the filter name in either the error log or in console would greatly speed up debugging.

## Steps to Reproduce

1. Unsure which is causing a problem! If necessary I can send all my active filters to reproduce elsewhere, otherwise tag me in the PR and I'll try it locally.

## Context (Environment)

Some graph filters were used for testing reasons, but I could see a user setting up multiple filters and then being confused which is failing (especially when many are in place, and when variable/output names change, or when graph options are tweaked, etc).

**Comment by Isgotkowitz** [comment]
Add context about where this exception was produced, and which graph/filter caused it, to the info map.
