### ISSUE TITLE
Cows entering preg check with ReproStateEnum other than PREGNANT - throws error and ends simulation if tries to exit state 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1539]
## Expected Behavior

I think that cows entering preg check should have the ReproStateEnum of PREGNANT. Then, if self._compare_randomized_rate_less_than("loss_rate"), she loses the pregnancy and the ReproStateEnum exits the pregnant state. 

## Current Behavior

Sporadically, a simulation will end early with the error: 'Attempting to exit a state that is not entered: ReproStateEnum.PREGNANT' and reference to line 1622 in cow.py (full error message attached below). This seems to happen more often in herds with a higher rate of preg loss (which makes sense). 

What I think is happening: occasionally a cow enters this loop with ReproStateEnum.WAITING_FULL_ED_CYCLE. If the dice decide that she is to "lose her pregnancy", it throws the error when trying to exit pregnant state. 

[c1f1_monensin_1of4_11Apr_warnings_11-Apr-2024_Thu_14-53-42.json](https://github.com/RuminantFarmSystems/MASM/files/14950905/c1f1_monensin_1of4_11Apr_warnings_11-Apr-2024_Thu_14-53-42.json)

How I got there: 
a) insert this print statement: print(self._repro_state_manager._states) on line 1622. As soon as a cow comes through with the "waiting for full estrus cycle" state, the simulation ends. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/b191ed9d-b385-4d7b-80c1-8e9e3392b576)

b) insert the same print statement on line 1621. Occasionally a cow will show up with the "waiting for full estrus cycle" state but the simulation does not end (presumably because she keeps her pregnancy and it never tries to exit the Pregnant state). 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/8a891f86-5c1c-47f1-8f57-aaaf5e220967)
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/7eb59596-b6f6-42a2-868d-97097f8b821e)

## Possible Solution

I'm not sure, I haven't investigated why cows with ReproStateEnum.WAITING_FULL_ED_CYCLE are entering _handle_preg_check

## Steps to Reproduce

1. Enter one of the print statements into cow.py as described above 
2. To see it more frequently, increase preg_loss_rate_1 (or 2 or 3, or all of the above) to 0.1. 
3.
4.

## Context (Environment)

Because this error happens sporadically and causes the simulation to end and not continue on to later simulations in the scenario manager list, it is very disruptive of work flow. 
When trying to run a herd with intentionally increased preg loss rates, I had to run it ~25 times (manually restarting every time) to get 4 complete simulations. 

I do not know the implications for herd or results of having individual cows with inappropriate repro state / preg check mismatch.

**Comment by Isgotkowitz** [comment]
Lol @jadamchick you're one step ahead of me. I just opened PR #1541 to address this exact issue.

Do you have a sense of when this error is occurring in the simulation? I was able to get the bug reproducing as part of addressing #1463, and what I found was that it was occurring when a pregnant cow was added to the herd as part of setting it up (so simulation day = 1).

**Comment by jadamchick** [comment]
> Lol @jadamchick you're one step ahead of me. I just opened PR #1541 to address this exact issue.
> 
> Do you have a sense of when this error is occurring in the simulation? I was able to get the bug reproducing as part of addressing #1463, and what I found was that it was occurring when a pregnant cow was added to the herd as part of setting it up (so simulation day = 1).

Hi Ed - excellent! 
On timing, I didn't formally look into it but it does seem to happen early on. (If it runs for a while, then it's going to finish without the error). 

One update; I see a farm I tried to run last night had a bunch of cows in the IN_OVSYNCH state instead of WAITING_FULL_ED_CYCLE, for what that's worth. It had the same repro settings as the previous (ED-TAI with OvSynch56) so I'm not sure why the difference. It did eventually have one enter the preg loss loop and end the simulation. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/9057aec6-be0c-45a0-991c-2b234f4e87af)

**Comment by Isgotkowitz** [comment]
> > Lol @jadamchick you're one step ahead of me. I just opened PR #1541 to address this exact issue.
> > Do you have a sense of when this error is occurring in the simulation? I was able to get the bug reproducing as part of addressing #1463, and what I found was that it was occurring when a pregnant cow was added to the herd as part of setting it up (so simulation day = 1).
> 
> Hi Ed - excellent! On timing, I didn't formally look into it but it does seem to happen early on. (If it runs for a while, then it's going to finish without the error).
> 
> One update; I see a farm I tried to run last night had a bunch of cows in the IN_OVSYNCH state instead of WAITING_FULL_ED_CYCLE, for what that's worth. It had the same repro settings as the previous (ED-TAI with OvSynch56) so I'm not sure why the difference. It did eventually have one enter the preg loss loop and end the simulation.
> 
> ![image](https://private-user-images.githubusercontent.com/146877580/321978965-9057aec6-be0c-45a0-991c-2b234f4e87af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzE5MjcsIm5iZiI6MTcxMjkzMTYyNywicGF0aCI6Ii8xNDY4Nzc1ODAvMzIxOTc4OTY1LTkwNTdhZWM2LWJlMGMtNDVhMC05OTFjLTJiMjM0ZjRlODdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNDIwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWQzMzM4MTJjMzkzYjE3MjgzOWUwOTBkMGEwYTBiZTFjY2UyNzNjZDU2MGNkYzYxMGVhZGJkMGNmYWEwYjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GWDDMTxnhEb5VOJ6OM1E7NXgu2X88ZqkfD-r894filU)

Excellent - hopefully this means there is a single case causing these errors. When a cow is pulled into the herd from the animal population on the first day of a simulation, it is not checked whether or not it is pregnant and the ReproStateManager is set to the `None` state. Then when it gets to the pregnancy check, it checks an attribute indicating pregnancy that is different from `ReproStateManager` and fails if there is a mismatch between the two

**Comment by jadamchick** [comment]
> > > Lol @jadamchick you're one step ahead of me. I just opened PR #1541 to address this exact issue.
> > > Do you have a sense of when this error is occurring in the simulation? I was able to get the bug reproducing as part of addressing #1463, and what I found was that it was occurring when a pregnant cow was added to the herd as part of setting it up (so simulation day = 1).
> > 
> > 
> > Hi Ed - excellent! On timing, I didn't formally look into it but it does seem to happen early on. (If it runs for a while, then it's going to finish without the error).
> > One update; I see a farm I tried to run last night had a bunch of cows in the IN_OVSYNCH state instead of WAITING_FULL_ED_CYCLE, for what that's worth. It had the same repro settings as the previous (ED-TAI with OvSynch56) so I'm not sure why the difference. It did eventually have one enter the preg loss loop and end the simulation.
> > ![image](https://private-user-images.githubusercontent.com/146877580/321978965-9057aec6-be0c-45a0-991c-2b234f4e87af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzE5MjcsIm5iZiI6MTcxMjkzMTYyNywicGF0aCI6Ii8xNDY4Nzc1ODAvMzIxOTc4OTY1LTkwNTdhZWM2LWJlMGMtNDVhMC05OTFjLTJiMjM0ZjRlODdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNDIwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWQzMzM4MTJjMzkzYjE3MjgzOWUwOTBkMGEwYTBiZTFjY2UyNzNjZDU2MGNkYzYxMGVhZGJkMGNmYWEwYjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GWDDMTxnhEb5VOJ6OM1E7NXgu2X88ZqkfD-r894filU)
> 
> Excellent - hopefully this means there is a single case causing these errors. When a cow is pulled into the herd from the animal population on the first day of a simulation, it is not checked whether or not it is pregnant and the ReproStateManager is set to the `None` state. Then when it gets to the pregnancy check, it checks an attribute indicating pregnancy that is different from `ReproStateManager` and fails if there is a mismatch between the two

Makes sense. Why do you think it is showing that cows are entering preg checks with repro states of Waiting_full_ed_cycle or In_Ovsynch? (I would expect "None" based on what you described?)

**Comment by Isgotkowitz** [comment]
> > > > Lol @jadamchick you're one step ahead of me. I just opened PR #1541 to address this exact issue.
> > > > Do you have a sense of when this error is occurring in the simulation? I was able to get the bug reproducing as part of addressing #1463, and what I found was that it was occurring when a pregnant cow was added to the herd as part of setting it up (so simulation day = 1).
> > > 
> > > 
> > > Hi Ed - excellent! On timing, I didn't formally look into it but it does seem to happen early on. (If it runs for a while, then it's going to finish without the error).
> > > One update; I see a farm I tried to run last night had a bunch of cows in the IN_OVSYNCH state instead of WAITING_FULL_ED_CYCLE, for what that's worth. It had the same repro settings as the previous (ED-TAI with OvSynch56) so I'm not sure why the difference. It did eventually have one enter the preg loss loop and end the simulation.
> > > ![image](https://private-user-images.githubusercontent.com/146877580/321978965-9057aec6-be0c-45a0-991c-2b234f4e87af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzE5MjcsIm5iZiI6MTcxMjkzMTYyNywicGF0aCI6Ii8xNDY4Nzc1ODAvMzIxOTc4OTY1LTkwNTdhZWM2LWJlMGMtNDVhMC05OTFjLTJiMjM0ZjRlODdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNDIwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWQzMzM4MTJjMzkzYjE3MjgzOWUwOTBkMGEwYTBiZTFjY2UyNzNjZDU2MGNkYzYxMGVhZGJkMGNmYWEwYjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GWDDMTxnhEb5VOJ6OM1E7NXgu2X88ZqkfD-r894filU)
> > 
> > 
> > Excellent - hopefully this means there is a single case causing these errors. When a cow is pulled into the herd from the animal population on the first day of a simulation, it is not checked whether or not it is pregnant and the ReproStateManager is set to the `None` state. Then when it gets to the pregnancy check, it checks an attribute indicating pregnancy that is different from `ReproStateManager` and fails if there is a mismatch between the two
> 
> Makes sense. Why do you think it is showing that cows are entering preg checks with repro states of Waiting_full_ed_cycle or In_Ovsynch? (I would expect "None" based on what you described?)

As I understand it, the states related to management practice stuff (ED stuff, OvSynch stuff, etc.) are not mutually exclusive to the "biological" states (pregnant, not-pregnant). But I don't know much about repro in the real world, so I have no idea if this accurately reflects reality. I think @ltp23 would be the person to ask this stuff.

**Comment by ltp23** [comment]
> Why do you think it is showing that cows are entering preg checks with repro states of Waiting_full_ed_cycle or In_Ovsynch? (I would expect "None" based on what you described?)

Hi @jadamchick, I think this happens because there are two variables involved here — `days_in_preg` and `days_in_milk`. The `days_in_milk` variable mostly controls the behavior of the waiting and ovsynch states. The `days_in_preg` variable is trickier to handle since a cow can come from the graduation from heifer III, from the replacement batch, or from the original herd. So if you see a cow in the pregnant state along with some other state, it is likely that those two variables are out of sync at some point.
