### ISSUE TITLE
[Manure] Incorrect manure volume used in anaerobic lagoon NH3-N emission

### ISSUE THREAD

**Issue by elle-andreen** [RuminantFarmSystems/RuFaS#1546]
## Expected Behavior
A component of the equation predicting ammonia emission from liquid manure storages (anaerobic lagoon or slurry storage) is the total mass of manure in storage ([see equation M.3.A.10 on page 14](https://3.basecamp.com/3486446/buckets/5296287/cloud_files/7195916818)). This value should be obtained from the accumulated manure treatment output, not the daily output. See the slurry_storage_outdoor.py file for a correct implementation of this functionality.

## Current Behavior
Currently, in anaerobic_lagoon.py, the **daily** manure volume is utilized in the equation for storage ammonia emission. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/148499778/6072fa7f-136d-4565-b776-9c75909b0f55)

The value for `manure_volume` in this equation should be updated to be `accumulated_output.liquid_manure_daily_volume`. 

The expected outcome of this change is that predicted ammonia emissions from the anaerobic lagoon will decrease considerably (~50%), and will be more in-line with estimated emissions from slurry storage outdoor, where the function was being implemented correctly. The decrease occurs because the total manure mass value is in the denominator of the equation - we are moving from a smaller (daily) to a larger (accumulated) value, so the final value will decrease.

**Comment by ew3361zh** [comment]
@elle-andreen

A couple questions for you:

1. It looks like the only thing we're doing with the calculated `storage_ammonia_emission` is to add it to the `daily_output.storage_ammonia`. Is that the correct place we want to add the newly-calculated `storage_ammonia_emission` to? It seems logical to me but wanted to double check with you.
2. In terms of the order of operations in the the AnLag `_daily_update_helper()` method, the call to `self._update_ammonia_emission` is after adding precipitation volume but before calculating methane emissions from non-degradable volatile solids. Does that seem like the correct placement? I have no reason to think it doesn't make sense but wanted to double check with you while we're in here making these updates.

**Comment by elle-andreen** [comment]
1. I think I understand your question but let me know if this doesn't answer it well, but yes, I believe ammonia emission from storage (according to the storage_ammonia_emission method at least) is just incorporated into the daily_output.storage_ammonia value for each treatment that uses it (AnLag, SSO, and SSU). Those treatment files then use that value to update the daily and accumulated values for N & TAN.
2. I think so? Daily precipitation volume would affected ammonia emission, but not methane emission I believe, so I think the placement as-is is okay!
