### ISSUE TITLE
[Crop & Soil] Flatten all instances of nested units within Crop & Soil Module

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1548]
There are a handful of instances in the model where the units for variables added to OM are nested within a second dictionary within their respective units dictionary (see image for example):

<img width="883" alt="Screenshot 2024-04-15 at 1 49 48 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/8a49c9b9-5a34-4a36-8398-c59217c4ca34">

These should be flattened out to be the same level as the other units in the units dictionary. This will make testing in OM to ensure units added are members of the `MeasurementUnits` enum easier.

## Expected Behavior

When units are added to info maps accompanying variables added to the OM, they should only be one level deep (i.e. no nesting).

## Current Behavior

There are a handful of units, I believe exclusively within the C&S module, that have units in nested dictionaries.

## Possible Solution

Remove the nested dictionary of units and add the units at the same level of depth as the other non-nested units.

Testing will likely need to be updated.

**Comment by Isgotkowitz** [comment]
Grooming session: to search for these nested units, consider using a Regex pattern or patterns to find all the nested units. The example given in the issue description has been fixed, but there are other instances of nested units within the crop and soil module.
