### ISSUE TITLE
[OM] Create methods to preprocess output filters 

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1559]
One potential way to save on memory usage at runtime is to preprocess the filter files to keep track of what variables from the variables pool would be requested later. This can provide a shortcut to storing only those variables during runtime. Naturally, if the filters are exhaustive and cover all the variables, then this approach wouldn't save anything.

For this issue, I want to gauge the usefulness of this approach by first creating one or more methods to record and count the frequency of all the requested variables and save the results to a file for further analysis.

**Comment by PooyaHekmati** [comment]
Create a method in OutputManager that reads all filter files and for each variable in the OM's pool, counts how many times it has been referenced by filters. The objective is to generate a list that contains the count of each variable's usages.
