### ISSUE TITLE
"Hard coded" total dry down

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#156]
Currently, the values for dry down percent (`biomass_dry_down_percent`), dry-mass percent at harvest (`DM_harvest_percent`), and whatever `NDF_harvest_percent` is are hard coded into each crop's data (crop_config.py)

Rather than hard-coded values, the `BaseCrop` class should probably have default methods, and each child class (alfalfa.py, corn.py, etc.) should contain any crop-specific versions of these methods.

Note: This pertains to sequential_v3 branch as of this issue opening.

**Comment by Isgotkowitz** [comment]
This issue is stale. Refer to #353 for implementing dry-down.
