### ISSUE TITLE
Unit Conversion error in Soil Nitrogen Removed By Water Routine

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1613]
The function `calculate_nitrogen_removed_by_water` has a unit conversion error resulting from an incorrect unit attributed to the extraction_coefficient

## Expected Behavior

This function sould take in the soil nitrogen content in units of kg N/ ha and the amount of water that is extracting the nitrogen in units of mm and return the amount of N that is lost from the soil in that water in units of kg N/ha.
## Current Behavior

Currently the method does the following: 

1. Calculates the total volume of water that is moving nitrogen in that soil layer in the whole field in units of liters
2. Calculates the concentration of nitrogen in the soil in units of mg N/ kg soil
3. _States_ that it is calculating the nitrogen lost to the water in units of mg N / kg soil mass (`nitrogen_leached_in_mg_per_kg`) but _actually calculates_ the total mass of nitrogen lost in the whole field in units of mg. 
4. Calls the `determine_soil_nutrient_area_density` routine to try to convert the `nitrogen_leached_in_mg_per_kg` to `nitrogen_leached_in_kg_per_ha` but because the value for the N content is incorrect, the returned value is also not correct

The error in Step 3 above is due to the incorrect unit attributed to the `extraction_coefficienct` which was thought to be (1/L) but is actually (kg/L)

## Possible Solution

We propose to simplify this routine by removing the need to convert from the soil N concentration in mg/kg soil to an area concentration by dividing the total mg of N lost that is calculated in step 3 above by the field size. Thus the `calculate_nitrogen_removed_by_water` would have the following calculations:

1. Calculates the total volume of water that is moving nitrogen in that soil layer in the whole field in units of liters (remains unchanged)
2. Calculates the concentration of nitrogen in the soil in units of mg N/ kg soil (remains unchanged)
3. Calculates the nitrogen lost to the water in units of mg N / ha  as follows: 

- `nitrogen_leached_in_mg_per_ha = nitrogen_content_in_mg_per_kg * extraction_coefficient * water_amount_in_liters /field_size`
4. Converts the nitrogen lost to water from mg N/ha to kg N/ha as follows: 

- `nitrogen_leached_in_kg_per_ha = nitrogen_leached_in_mg_per_ha * MILLIGRAMS_TO_KILOGRAMS`

5. Returns the minimum of either the soil N content or nitrogen lost (remains unchanged)

The unit for the `extraction_coefficient` should also be updated

## Context (Environment)
This is one factor that is resulting in unrealistically high nitrogen losses to the water.

## Possible Implementation

I have started to test and implement a fix for this on the branch `soil_crop_debugging`
## Target Deadline

This is a very urgent issue and can hopefully be fixed fairly quickly so ideally by early next week (May 13-14)

**Comment by ew3361zh** [comment]
@KFosterReed it looks like you've implemented the suggested fix on your `soil_crop_debugging` branch. Is the only thing remaining to update the testing or were there other aspects to the issue you still wanted addressed?

**Comment by KFosterReed** [comment]
> @KFosterReed it looks like you've implemented the suggested fix on your `soil_crop_debugging` branch. Is the only thing remaining to update the testing or were there other aspects to the issue you still wanted addressed?


I think just the unit tests! And if you could tag Kevin P-B on the PR review, that would be great!
