### ISSUE TITLE
Crop dry down method

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#162]
# Problem
More sophisticated methods for calculating crop dry down is needed. Currently, `calc_dry_down()` (yields.py) is set to the above ground biomass (`bio_AG`) minus product of above ground biomass and crop-specific dry down percent (`biomass_dry_down_percent`).

(sequential_v3)

# Suggested solution
This method should probably be implemented in the `BaseCrop`  or `Crop` class as a generic and additional crop-specific methods should be implemented in the crop child classes where more sophisticated equations are known.

**Comment by Isgotkowitz** [comment]
This issue is stale. Refer to issue #353 for implementing dry-down as a feature.
