### ISSUE TITLE
Update replacement animals to heiferIIIs and use a separate male calf rate in herd init

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1621]
This issue was created after the PR had been made.

Tasks to accomplish:
- Change the type of replacement animals from cows to heiferIIIs in herd factory and life cycle modules.
- Reduce the frequency of assigning heiferIIIs to the replacement group because this would affect the stability of the herd size and distribution over time.
- Create a separate parameter for male calf rate so that it is used only during herd initialization. The male calf rate indirectly determines how many calves we start with. To be more exact, male calves will be sold so the complement of that rate (1 - male calf rate) will give us a rough estimate of the number of female calves. And then during the herd generation process, this male calf rate will be used again to determine the gender of the newborn calves. The reason we want a separate parameter is that a very low rate is much more preferred and effective in herd generation, whose main purpose is to make cows and heifers.

**Comment by Isgotkowitz** [comment]
Blocked by #1680
