### ISSUE TITLE
Disentangle the Manure and Crop & Soil modules

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1625]
The connection between the Manure module and the Crop and Soil module should be disentangled so that they meet the requirements outlined in #1622.

## Suggested Solution

The method `_check_manure_application_schedule` in `Field` should be moved from `manage_field` into its' own wrapper method (or just made public), and should return a `NutrientRequestResults` containing requested manure (if any) to `FieldManager`. This request is then returned by `FieldManager` to `SimulationEngine`, which passes it to `ManureManager`'s `request_nutrients` method. That method will return `NutrientRequestResults` which should be passed back into `FieldManager`. It might be easiest to pass the `NutrientRequestResults` into `FieldManager` through `daily_update_routine`, which then routes the different manure applications to different `Fields` using a mapping based on the field's name.

The implementations of `NutrientRequest` and `NutrientRequestResults` should be moved into a new directory that is not in either the Crop and Soil module or the Manure module. A new subdirectory may be needed for this.

The Crop and Soil module will request manure from the `FieldManureSupplier` (instead of the `ManureManager`) when no animals are simulated, and this behavior must be preserved. One of the easiest ways of doing this might be to simply move the `FieldManureSupplier` into the Manure module and have the `ManureManager` manage the logic how manure applications are created.

## Current Behavior

The Crop and Soil module's `FieldManager` takes the Manure module as an argument at initialization and keeps it as an attribute of `Field` instances when animals are simulated. When a manure application needs to be created (and animals are being simulated), the Manure Manager is called to construct a manure application in `Field._execute_manure_application`.

**Comment by Isgotkowitz** [comment]
Grooming session: @adhikaripradip75 we (the dev team) would like to get your input on how the Manure and Crop & Soil modules should be connected.

**Comment by adhikaripradip75** [comment]
Hello Ed, Thanks for question.
Today I am at Marshfield and the internet connection is poor and I am not
able to access slack properly.
By the way what is coming out from the manure module: solid manure (kg),
liquid manure (L) and slurry too ??.

There will be a couple of options for the manure that is coming out of the
dairy to manure storage and storage to the cropping fields.
1. 100% applied to the fields.
2. Many dairy producers export portion to the third party and apply
the remaining portion in the crop fields.
3. Some dairy imports manure too.
4. 100% exported to the third party

Many dairy farmers have multiple crop fields, they only apply manure to the
fields where required, based on NPK  soil  and manure test values. I am
thinking of including these options in the manure application/schedule. We
can discuss about this issues in the coming days as well as during the
annual meeting next week.

Thanks
Pradip
