### ISSUE TITLE
Arbitrary parameters in residue calculation

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#163]
# Problem
* [ ] The `calc_residue` function (yields.py) has a hard coded values tillage percent of the first soil layer (`soil_layers[0].tillage_percent`). Presumably, though, this should be dependent upon the management practices.
* [ ] Similarly, lignin as a percent of soil residue at harvest seems to be arbitrarily set to 17% both above ground (`AG_lignin_res_percent`) and below ground (`BG_lignin_res_percent`). These values should also depend upon management practices, crop types, and other factors rather than being constant. 
* [ ] In the `residue_partitioning()` function (residue_partitioning.py), nitrogen fraction `fr_N` needs to be validated.

(sequential-v3)

# Suggested solution
I suspect that both problems should be solved by implementing methods in the `Soil` class (or perhaps in the `Crop` class if crop-specific methods are needed for lignin).

**Comment by Isgotkowitz** [comment]
Closing this issue as stale. The handling of crop residues is still not in a great state, but that is tied into other issues related to carbon cycling and should be addressed as part of those issues.
