### ISSUE TITLE
Verify soil parameters

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#164]
## April 2023 Note
Many of the names of these variables have changed but it is still important to verify soil parameters with scientists. Update this issue as needed.

---

# Problem
* The following initialization attributes in the `Soil` class (soil.py) need verification:
   - above and below ground lignin is initialized as 17. This problem overlaps with issue #163
   - `silt_to_clay_percent` is hard-coded as 0.5
* Also, the `initialize_profile_characteristics()` method of `Soil` class is not tracking organic phosphorus (`org_P`) in the soil pool. Currently, `org_P` is simply a function of organic carbon, bulk density, and thickness of the soil layer.
* the sediment calculation function (`calc_sed()`; soil_erosion.py) and the bio-cover weighing factor function (`calc_bcv()`; soil_temp.py) both contain an "arbitrary snow flag" which simply assumes there is snow if the day is between December and February. Albedo is also arbitrarily calculated in `calc_bcv()`. 
* manure leaching parameters `MTF_1` and `MTF_2` are hard coded - I don't know what these variable correspond to * in `update_all()` (manure_leach.py).  They don't seem to be in the pseudocode yet. 
* there's also a requirement for rainfall to be greater than 0 in dissolved P calculations (`manure_leach.update_all()`)

(sequential_v3)

# Suggested solution
* [ ] soil lignin should depend upon external factors. Soil residue functions should also be cross-referenced (#163) to ensure correct assignment of lignin once appropriate methods are determined.
* [x] the silt/clay ratio should depend upon external factors like a database or input
* [ ] RUFAS should probably track organic phosphorus (labile and active) rather than the current crude calculation based on correlations. 
* [x] a true `snow` flag should be implemented. 
* [x] validate `MTF_1` and `MTF_2`
* [ ] check the dissolved P rainfall function and find an alternative way to solve the divide by 0 problem that caused the rainfall condition in the first place.

**Comment by Isgotkowitz** [comment]
Closing this issue as stale. SMEs should review the soil inputs, but that should happen naturally in the process of them creating simulations to run.
