### ISSUE TITLE
Add proportion of organic bedding to manure non-degradable volatile solids pool

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1642]
**Is your feature request related to a problem? Please describe.**
Currently organic bedding is not added to the mass of manure that is tracked in the manure management system. There is a lot of uncertainty around this flow and its impact on emissions but we need to start tracking them. 

**Describe the solution you'd like**
I would like a method that adds a fraction of the organic bedding types (sawdust, manure solids, straw) to the non-degradable volatile solids in the reception pit. This fraction would be equal to `(1-`"bedding_cleaned_fraction"`)`, where the bedding cleaned fraction is a user input to the `"bedding_configs"`

**Describe alternatives you've considered**
Alternatives are to:

1.  ignore the organic bedding like we are doing right now
2.  split the organic bedding that ends up in manure into the degradable and non-degradable volatile solid pools. However, there is not a lot of information about how we would do this so I don't think it is a viable option right now. 

**Additional context**
Methane generated from manure storage is impacted by the type of bedding and there is concensus that organic bedding contributes to methane generation. Although there is uncertainty about the magnitude of this contribution, it is still important for us to start to represent this based on the best available knowledge we have right now. 

Also, before we can implement this, we need to identify default estimates for `"bedding_cleaned_fraction"` for each of the organic bedding types. 

**Target Deadline**
It would be great to have this implemented before the end of May.

**Comment by ew3361zh** [comment]
Grooming session:
- @Isgotkowitz to follow up with Elle to see status of this issue.

**Comment by Isgotkowitz** [comment]
Followed up with @elle-andreen: status is that it still needs to be done. The solution described in the "Describe the solution you'd like" section should be implemented by a dev, and Elle with follow-up with external SMEs to discuss how alternative #2 might work.

I'm marking this as "High" priority just so that it will get picked up quickly by a dev, I have not confirmed that this is actually a burning issue with anyone.
