### ISSUE TITLE
update manure application methods

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#166]
* [ ] the `formulate_manure_application()` function (manure_applicaiton.py) currently uses a rudimentary manure purchasing equation. A more robust method should be implemented, which would "require drawing purchased manure from some variety of input (likely a database)". 
* [ ] faction of nitrogen and phosphorus (`N_frac`, `P_frac`) also need validation (`formulate_manure_application()`)

(sequential_v3)

**Comment by Isgotkowitz** [comment]
This issue is stale.
