### ISSUE TITLE
[IM] [Metadata] Gather nullable input data from SMEs/SWEs

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1664]
Now that nullability is a valid option for string, bool, and number types, the properties that should have nullability allowed need to be added to metadata properties.

A survey/spreadsheet of SMEs and SWEs should be done to collect these properties along with any precautions/extra steps that need to be taken for implementing nullability for those fields.

Some considerations to collect from SMEs/SWEs (this is not an exhaustive list):
- Should the default be null?
- What associated input files need to be updated?
- Is there associated code in RuFaS that uses this field that will need to be updated if a null value is now allowed?

This will likely lead to further issues being created to implement some of the more complicated nullable inputs where it's not just updating the metadata property to allow the field to be nullable.

**Comment by Isgotkowitz** [comment]
Grooming session: For this issue, the main focus should be on the third bullet in the description, "Is there associated code in RuFaS that uses this field that will need to be updated if a null value is now allowed?" Some outreach to SME's would be good, but not all nullable inputs have to be gathered at once.
