### ISSUE TITLE
[Input Manager] Utilize new utility functions

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1669]
Two new utility functions `convert_flat_dict_to_nested_dict` and `deep_merge` are introduced to the code base. These can probably be used in Input Manager to both improve existing functionalities and code cleanliness and to introduce new features. Explore this possibility. 
Hint: take a look at the unit tests to see what these functions can and cannot do.

**Comment by allisterakun** [comment]
This issue can interfere with the issue #1273
