### ISSUE TITLE
[Wiki] Revisit GNU Args page

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1670]
[This wiki page](https://github.com/RuminantFarmSystems/MASM/wiki/RuFaS-Command-Line-Arguments) is outdated. Update it.

**Comment by Isgotkowitz** [comment]
I may have already taken care of most of this, but it should definitely get another pair of eyes on it.

**Comment by allisterakun** [comment]
I will take this for the next sprint. I will also review the TaskManager wiki as part of this task.
