### ISSUE TITLE
[Wiki] Update the overview map

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1671]
[This diagram](https://github.com/RuminantFarmSystems/MASM/wiki/Output-Manager#diagram) which has been used in multiple wiki pages is outdated. First, we don't have a post-processing block, it is handled by RG. Second, it doesn't illustrate the Task Manager. Fix all occurrences of this digram.

**Comment by ew3361zh** [comment]
Current version where TM is incorporated.

https://whimsical.com/rufas-pipeline-4Ebrd24prxFVS6fWuqwwPx



![Image](https://github.com/RuminantFarmSystems/MASM/assets/70217952/af9570db-d18c-42ca-9d6d-dc580862307b)

**Comment by ew3361zh** [comment]
Updated diagram -
1.  Horizontalizes tasks list.
2. Adds single simulation to tasks.
3. Has single simulation as blown-up detail view of the single simulation task.

![Image](https://github.com/RuminantFarmSystems/MASM/assets/70217952/38184799-991d-4c45-b85b-6f45424fa68d)

**Comment by ew3361zh** [comment]
Wiki pages updated with new diagram:
- Graph Generator
- Input Manager
- Output Manager
- Report Generator
- Task Manager
