### ISSUE TITLE
Ration Driver: IndexError in <get_user_defined_ration> Function Due to Empty animal_list or body_weight_history 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1672]
## Expected Behavior

The `get_user_defined_ration` function should return a dictionary of the rations by feed and the status of the NLP optimization. The expected behavior includes multiple outcomes:

1. If the user has defined a lactation reduction percent of 0.0 and tolerance of 0.0, the fixed ration is used.
2. If the optimization is a success, the optimized solution (within the tolerance bounds) is used.
3. If the optimization fails:
    3.1. If lactation reduction is set to 0.0, no reattempt is made.
    3.2. If not, optimization is reattempted until the lactation reduction threshold is reached (e.g., milk_reduction_maximum).

## Current Behavior

An IndexError occurs when the `animal_list` or `body_weight_history` is empty, causing the code to stop working and crash.

## Possible Solution

Add if statements to check if animal_list or body_weight_history is empty before accessing their elements, and handle these cases gracefully by raising an appropriate error.

A solution suggested by ChatGPT: 

```
constraints_failed_list = []
if failed_constraints is not None:
    for constr in failed_constraints:
        constraints_failed_list.append(constr.get("fun").__name__)

animal_list = list(pen.animals_in_pen.values())

# Check if animal_list is not empty to avoid IndexError
if not animal_list:
    raise ValueError("No animals in pen to create fail summary.")

# Check if body_weight_history is populated
if not animal_list[0].body_weight_history:
    raise ValueError("Animal's body weight history is empty.")

last_body_weight_entry = animal_list[0].body_weight_history[-1]

# Check if last entry in body_weight_history has simulation_day
if not hasattr(last_body_weight_entry, "simulation_day"):
    raise ValueError("Last body weight entry does not have simulation_day attribute.")

fail_summary = {
    "simulation day": last_body_weight_entry.simulation_day,
    "reattempt number": num_reattempts,
    "constraints_failed_dict": constraints_failed_list,
    "ration_attempted": cls.make_ration_from_solution(available_feeds, solution),
    "pen requirements": pen.avg_nutrient_rqmts,
}
```

## Steps to Reproduce

1. Use the feed input file` feed_W_Diet_15.json` from the SYSEN-MAy24-HH branch.
2. Run the get_user_defined_ration function.
3. Observe the error that occurs if animal_list or body_weight_history is empty.

## Context (Environment)

This issue stops the code from working and crashes the program when it encounters an empty animal_list or body_weight_history. It impacts the functionality and reliability of the system.

## Possible Implementation

- Add if statements to check if animal_list or body_weight_history is empty.
- Raise an appropriate error if these lists are empty to handle the situation gracefully.
- Update the function to include these checks and test with various input files to ensure the issue is resolved.

## Target Deadline

As soon as possible.

**Comment by JoeWaddell** [comment]
closed via: https://github.com/RuminantFarmSystems/MASM/pull/1863
