### ISSUE TITLE
Remove second Mypy run from GitHub Action

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1710]
There is an unnecessary second Mypy run on PRs by the GitHub Action `combined_format_lint_test_mypy.yml`.

## Status

To determine the net change in the Mypy error count between the feature branch and the base branch, the Action check's out the main branch and runs Mypy on it (see the step named "Run mypy on the main branch"). This second run of Mypy is unnecessary, because the number of Mypy errors on the main branch has already been recorded in the README.

## Intention

Make the GitHub Action faster/more efficient by removing the Mypy run on main branch.

## Request

Change the "Run mypy on the main branch" task to read the number of Mypy errors in the README on the main branch, instead of rerunning Mypy.

**Comment by ew3361zh** [comment]
After talking this through with @PooyaHekmati, this isn't a sound idea as the README is not a protected file - it's easily changeable and therefore the MyPy error count recorded in it is not a reliable count. Additionally, after reviewing the runtime for the Github Actions both with and without this second MyPy run, there is little to no difference so it's not saving us any GHA minutes.
