### ISSUE TITLE
Field Nitrous Oxide emission estimates incorrectly attribute all denitrified nitrogen to Nitrous Oxide

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1712]
The process of denitrification in the soil produces both nitrous oxide (a greenhouse gas) and nitrogen gas (also known as N_2, which does not contribute to the greenhouse effect). Right now we incorrectly attribute all of the denitrified soil nitrogen to nitrous oxide emission so we need to add a method to:

1. Estimate the ratio of denitrified nitrogen that is emitted as nitrous oxide. 
2. Apply that fraction to the methods that predict and report nitrous oxide emissions from the soil

## Expected Behavior

Nitrous oxide should be a variable fraction of denitrified nitrogen that can range from (roughly) 0.05 to 0.80. This fraction is dependent on 3 things: 

- Soil nitrate content (kg/ha)
- Soil pH
- and total soil carbon content (kg/ha)

## Current Behavior

All denitrified nitrogen is attributed to nitrous oxide emission

## Possible Solution

- Create a function to estimate the ratio of denitrified nitrogen that is partitioned to nitrous oxide within `denitrification.py` following the equations/logic to be provided in more detail in a google doc soon. 
- When defining the `layer.nitrous_oxide_emissions` soil layer attribute in the `denitrify()` method of the nitrogen_cycling directory, set it equal to `nitrified_nitrates/(1+nitrous_oxide_ratio)`
- In addition, the above 'nitrified_nitrates' is misnamed. References in variables and documentation notes for 'dentrification.py' should be 'denitrification' or 'denitrified'.

@KevinP-B or @KFosterReed will provide a more detailed description of the method for estimating the ration via a google doc linked to this issue soon but for now, a screenshot of the SWAT documentation is provided below. 

## Context (Environment)
We are currently over predicting nitrous oxide emissions by quite  a lot. This is the largest source of greenhouse gases in the field and it is important that we estimate this correctly. 

## Detailed Description

Proposed solution details can be found in the google doc
https://docs.google.com/document/d/1HWEU_hv2UPsiupqZjc_SkfYCExFuALZ7qVyZnlKa2Lc/edit?usp=sharing
## Target Deadline

This is an urgent task. May 31 deadline is very important to acheive.

**Comment by allisterakun** [comment]
During the grooming session:
@KFosterReed this issue is labeled with the "dev-team" tag. Should dev team be actively working on this?

**Comment by Isgotkowitz** [comment]
Followed up with @KFosterReed about this issue. It is not burning, but should be worked on - so marking it as "high" priority.

**Comment by Isgotkowitz** [comment]
Moving this to blocked until the nitrate effect equation gets sorted out

**Comment by Isgotkowitz** [comment]
@KevinP-B and I had a meeting this morning, where we got the issues with the nitrate effect equation worked out. Parton et al did not have their parentheses correct in their paper, which is why we were getting such funky results.

Also, while comparing the Parton and SWAT papers, we realized that the carbon effect should be taking carbon _respiration_ as an input as specified in Parton et al, not the total carbon in the soil as specified in SWAT
