### ISSUE TITLE
Homegrown feed emissions estimation methods

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1714]
**Is your feature request related to a problem? Please describe.**
I have to run to a meeting soon but wanted to get this out before the sprint planning meeting: 
[https://docs.google.com/document/d/1aGeSL-8RXqgZjQPQsoRVvXVlPH-E7QivZcCnnbt16Q8/edit?usp=sharing](https://docs.google.com/document/d/1aGeSL-8RXqgZjQPQsoRVvXVlPH-E7QivZcCnnbt16Q8/edit?usp=sharing)

**Describe the solution you'd like**
Ideally this can be implemented in the EEE module

**Describe alternatives you've considered**

**Additional context**
I will provide a report filter and excel file that includes examples of the exact desired calculations by the end of the day today. 

**Target Deadline**
May 31st

**Comment by KFosterReed** [comment]
I am added an example CSV file to calculate emissions using outputs from an example report that is also attached. These example results were obtained by running the `homegrown_feed_test_metadata` scenarion on the 'Homegrown_feed_emissions' branch
[Template for Homegrown Feed Emissions Calcs.xlsx](https://github.com/RuminantFarmSystems/MASM/files/15436489/Template.for.Homegrown.Feed.Emissions.Calcs.xlsx)
[report_homegrown_feed_emissions.json](https://github.com/RuminantFarmSystems/MASM/files/15436496/report_homegrown_feed_emissions.json)

**Comment by krb78** [comment]
I made some comments/edits to the spreadsheet but it didn't appear to be a live link, so here's a [live excel sheet](https://rosedmi-my.sharepoint.com/:x:/g/personal/kaitlyn_briggs_dairy_org/EcDwYdnlb9NKr_9xfyZqto8B9n-Ynk-G9pclGWscLFqFwA?e=Pb9J7C)

**Comment by KFosterReed** [comment]
There was a duplicate feed ID number in the emissions.py file that had me scratching my head for a bit but I corrected it and then reviewed the corn silage, corn grain, and alfalfa silage actual purchased feed and emissions outputs... so far so good!
