### ISSUE TITLE
Add a service for getting the FIPS code of a location.

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1730]
A service should be created for getting the FIPS county code of a location.

## Status

With the change made in #1727, RuFaS will strictly require the FIPS county code for a simulation to be provided in inputs. This means that a user will have to manually get this information for any new location that they want to simulate.

## Intention

Although easy to get manually, there should be a service to automate getting the FIPS code based on a pair of latitude-longitude coordinates from the API that the FCC maintains for doing just that.

## Request

Add a new service to the one created in #1729 which will retrieve the FIPS county code from the FCC's API based on a coordinate.

### Additional Information

See the implementation of `PurchasedFeedEmissionsEstimator` prior to the changes made in #1727 as a guide for how to interact with the FCC's FIPS code API.

**Comment by ktthr** [comment]
I created a Python script that automates the process to get the FIPS county code before-- it had been used to find the FIPS county codes for farms in the pilot testing.
Pasted below as additional reference:

```
import requests

class CountyFinder:

    def _eval_arr(arr):
        """
        Given an array of tuples (latitude and longitude coordinates), prints out a list of all coordinates with the corresponding county code to its right.

        Notes
        -----
        This method works by:
        - Iterating through the inputted array and calling _get_county_code to find the county code for each coordinate.

        """
        for i in range (len(arr)):
          print("(" + str(arr[i][0]) + "," + str(arr[i][1]) + "): " + str(CountyFinder._get_county_code(arr[i][0], arr[i][1])))

    def _get_county_code(latitude, longitude) -> int:
        """
        Maps parameters, latitude and longitude, to corresponding county code.

        Returns
        -------
        int
            5 digit county code. Raises an error if the latitude and longitude parameters do not map to a county.

        Notes
        -----
        This method works by:
        - Calling an API (https://geo.fcc.gov/api/census/block/find) to find a county code.

        """
        endpoint = "https://geo.fcc.gov/api/census/block/find"
        params = {"latitude": latitude, "longitude": longitude, "format": "json"}
        response = requests.get(endpoint, params=params)
        if response.status_code == 200:
            answer = response.json()
            returned_FIPS_code = answer["County"]["FIPS"]
            return int(returned_FIPS_code)
        else:
            raise "Invalid input"
        

#example call to get county code from cohort 2 (farms 4 and 12) latitude & longitude data
CountyFinder._eval_arr([(44.8429, -72.9340), (42.9813, -77.9510)])
```

**Comment by Isgotkowitz** [comment]
Wrote in service to get FIPS code in the [Input-Service](https://github.com/RuminantFarmSystems/Input-Service). Took ~1 hour, will mark down the size accordingly and find someone to "review" it.

**Comment by Isgotkowitz** [comment]
Requesting review from @matthew7838. The things to look at are:
- The module `src/fips_code_collector/fips_code_collector.py`
- The new method for writing FIPS outputs in `io_routines.py`.
- The section of `main.py` that handles parsing the FIPS code inputs.
- The Readme's section that describes how to use the FIPS code collector.

There is currently no testing, so there is not much to do with the review besides checking that there are no glaring design errors, and ideally running the code to check that it works.

**Comment by matthew7838** [comment]
@Isgotkowitz LGTM works with all the American cities that came to my mind, but it is not working for international destinations(as expected for now).
