### ISSUE TITLE
K5,K6,K7 values differ in actual code vs. pseudocode

### ISSUE THREAD

**Issue by Brandon-DeBoer** [RuminantFarmSystems/RuFaS#176]
In the `pseudocode_soil doc [S.6.C]`, K5,K6, and K7 are said to be .14, .00038 and .00013 respectively according to Parton et al., 1987. In the actual code in `pool_gas_partitioning.py` they are initialized to be .02, .000542857, and .0000185714 respectively. Just want to make sure the values in the code are correct, and then pseudocode needs to be adjusted

**Comment by morrowcj** [comment]
This should be addressed in #223
