### ISSUE TITLE
[CurrentDayConditions] Review current latitude and daylength IM data usage and availability.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1765]
The calculate_daylength() function in CurrentDayConditions should be reviewed.

With CurrentDayConditions as a core part of the Weather class (post refactor #1764), it should be reviewed whether it's a good idea to have some data currently in weather (`daylength`) that is dependent on getting latitude from field inputs. This seems potentially problematic and either the latitude inputs should be relocated to a more intuitive and separate section of the inputs or the Weather class shouldn't have that data and shouldn't be doing the calculations for `calculate_daylength()`. And perhaps both things are true.

There are currently no known issues with the way things are set up but it seems worth reviewing.

**Comment by allisterakun** [comment]
During grooming session:

@Isgotkowitz mentioned that the field module is currently the only place where the `daylength` is used. However, the lat-long information would potentially be used in the EEE modules.

Therefore, we should instead pass in the latitude as an input to the `get_current_day_condition()` function. The `_get_latitude()` function in the `Weather` class should be deleted, as the `Weather` class should not have any knowledge of location baked in.

We must untangle the `Weather` class, the `CurrentDayConditions` class, and the rest of the biophysical modules. 
The `Weather` class should take the current time and a location as input to return the `CurrentDayConditions` result.

**Comment by Isgotkowitz** [comment]
Grooming session: this was addressed by #1908
