### ISSUE TITLE
Write end-to-end testing routine for `FeedStorage`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1768]
Add an end-to-end testing routine that will test how stored crops loss mass and nutrients over time.

## Status

Currently, `END_TO_END_TESTING` is an type of task that can be run, but there is nothing implemented for it in `TaskManager`.

The Feed Storage module's routines for processing mass and nutrient losses in stored crops are tested, but only with unit tests.

## Intention

End-to-end testing is desired so that the behavior of stored crops can be observed over longer, more realistic simulation periods. It will also provide an easier and more systematic way to catch problems when making changes to the Feed Storage module.

## Request

Modify the `TaskManager` so that it will run an end-to-end testing routine on the Feed Storage module. This routine should consist of loading in some weather and configuration data, as well as some pre-computed results to compare against.

The first iteration of end-to-end testing for Feed Storage should be very simple - this is just a start to end-to-end testing. It would suffice to create an instance of each final child of `Storage`, store a `HarvestedCrop` instance in each instance, and process the degradations in each on a weekly or monthly basis over a relatively short period of time (100 days to a year).

All outputs from the `Storage` child instances should have corresponding outputs in the precomputed end-to-end testing results. These outputs should be compared to check for equality, or for equality within a specified tolerance.

### Additional Information
When implementing this, there will be no precomputed results to compare against, so those will have to be created. These initial results should be checked with Kevin Panke-Buisse (@KevinP-B) to make sure that they are correct.

**Comment by PooyaHekmati** [comment]
Hi @Isgotkowitz , I have escalated the priority of this issue to urgent. You do not need to work extra on this, but please finish this as soon as possible, don't work on other tasks before finishing this.
Also, as we discussed, Please make sure the code structure allows easy expansion to cover other parts of the code base. 
Please tag me on the PR once it is ready.
