### ISSUE TITLE
[Animal] Milk Production Logic Check [1/2]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1795]
We need to review the current logic for the milk production process and prepare for the refactor.

Describe the solution you'd like
Go through the current codes related to the milk production process and create a logic diagram.

Describe alternatives you've considered
If preferred, the above logic can be incorporated into an informal design document or a block of pseudo-code.

Treat the MilkProduction submodule as a calculator. Please clearly indicate what information (variables) it needs to know about every single animal for the calculation and what exactly it will return (what exact variables it will modify).

**Comment by ew3361zh** [comment]
Please review: @allisterakun @JoeWaddell 

I went with a diagram comparing the current set-up with the new set-up:

https://whimsical.com/milk-production-logic-redesign-GVw1e2n22VqXH9PdnUFkjg

**Comment by ew3361zh** [comment]
And a word doc with the current milk-production related methods and the attributes/vars they require:

https://docs.google.com/document/d/1YYP-ynNp16SF2fRSOXZhG4BOd7UuDhpx4WQN2b_qQV0/edit?usp=sharing

**Comment by allisterakun** [comment]
Great job, Niko! Thank you for the detailed information! Looks good to me!

**Comment by Isgotkowitz** [comment]
In progress is the `LactationCurve` module (#1881, #1461). This may have a significant impact on this the Milk Production logic.

**Comment by ew3361zh** [comment]
@YijingGong can you please review the following two documents for this issue? Feedback here in the issue or in the documents themselves is fine!

Updated diagram and google doc reflecting proposed changes that track Animal attributes needed for MilkProduction update and Animal attributes changed by MilkProduction update:

Diagram:
https://whimsical.com/milk-production-logic-redesign-GVw1e2n22VqXH9PdnUFkjg

Google Doc:
https://docs.google.com/document/d/1YYP-ynNp16SF2fRSOXZhG4BOd7UuDhpx4WQN2b_qQV0/edit

**Comment by allisterakun** [comment]
Thank you, Niko. Great work! I left two comments on the Google doc, let me know what you think.

**Comment by YijingGong** [comment]
Great work! Very clear diagram! Both the diagram and doc look good to me!

**Comment by ew3361zh** [comment]
2 approved reviews, closing issue as complete.
