### ISSUE TITLE
[Animal] Nutrient Logic Check [1/2]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1796]
We need to review the current logic for the nutrient-related codes and prepare for the refactor.

Describe the solution you'd like
Go through the current codes related to the nutrient in the animal module and create a logic diagram.

Describe alternatives you've considered
If preferred, the above logic can be incorporated into an informal design document or a block of pseudo-code.

Treat the Nutrient submodule as a calculator. Please clearly indicate what information (variables) it needs to know about every single animal for the calculation and what exactly it will return (what exact variables it will modify).

**Comment by ew3361zh** [comment]
After discussion with @allisterakun, expanded this logic check to include animal daily phosphorus updates as well.

Setting nutrient requirements is not a daily update. It is done:
1. At the init stage of AnimalManager if `simulate_animals` is True.
2. When it's time to reformulate a ration for a pen.

Overview for restructuring Nutrient Logic is here in word-doc format:
https://docs.google.com/document/d/1SWJxhpoFgY0bBwC9b8P09ihXw4kyCg62I13Itrp2B6Q/edit

Overview for daily phosphorus updates logic is here:
https://docs.google.com/document/d/1PAro5--SNBkYvkScfHwWILVAA-jRUU5HRlhQNo8Y0Xw/edit

**Comment by ew3361zh** [comment]
@allisterakun can you please review?

**Comment by allisterakun** [comment]
@ew3361zh I left some comments in the two GDocs!

**Comment by ew3361zh** [comment]
After discussion with Allister, this issue has become focused solely on a daily phosphorus update for the animal. Here is a diagram outlining the proposed setup. There is also a google doc which outlines what data is needed for the phosphorus update and what data is then updated by that update and sent back to the animal.

Diagram:
https://whimsical.com/animal-daily-phosphorus-update-Pi4i3qov4Gb6SCN5P8vniV

Google Doc:
https://docs.google.com/document/d/1PAro5--SNBkYvkScfHwWILVAA-jRUU5HRlhQNo8Y0Xw/edit

**Comment by allisterakun** [comment]
Thanks Niko! This document and the diagram looks great! Good work!

**Comment by ew3361zh** [comment]
@JoeWaddell just a reminder if you could please review these two documents when you get some time, that would be much appreciated! Thanks!

**Comment by JoeWaddell** [comment]
Thanks! Adding notes/comments in the docs themselves

**Comment by ew3361zh** [comment]
Closing out with 2 approval reviews.
