### ISSUE TITLE
[C&S] Division by Zero when No Crop to Harvest

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1799]
In certain situations, like when there is no weather data, C&S won't grow the crops. However, due to its current structure, it still does the Harvest operation. This leads to uncaught Division by Zero exception when the Harvest operation tries to find the ratio of the crop being over and under the ground (there is no crop so it leads to 0/0). 

Add try-except clause to this operation and catch the division by zero exception. When it happens, log a warning to OM to let the user know about what happened. 

Keep @KFosterReed , @krb78 , and @PooyaHekmati updated about the progress here.

This is a follow up to #1088

**Comment by PooyaHekmati** [comment]
```
File "/home/jean/code/vyla/rufas-farm-es/RUFAS/routines/field/crop/crop_management.py", line 182, in cut_crop
    fraction_cut = self.data.cut_biomass / self.data.biomass
ZeroDivisionError: float division by zero
```

**Comment by matthew7838** [comment]
The current cause of missing weather data will be solved after the merge of refactored weather.py. However, try-catch statements and warnings will still be added to prevent any other unknown reason at this time.
