### ISSUE TITLE
Crop root biomass distribution by root growth patterns

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1811]
**Is your feature request related to a problem? Please describe.**
Crop roots often grow more near the surface and then have less root structure as the soil depth increases. We would like to improve the RuFaS representation of the distribution of the root biomass among the soil layers. 

Currently RuFaS predicts the total root biomass and then distributes the total root biomass between the soil layers based only on soil layer depth (i.e. each soil layer's proportion of the total soil profile) rather than the expected root biomass distribution among layers. 

**Describe the solution you'd like**

The method for the root distribution is described in this paper: https://www.sciencedirect.com/science/article/pii/S0378429016300399?via%3Dihub

EDIT: This method is slightly more involved than I originally thought so I started a design doc: https://docs.google.com/document/d/1iMSzJ_HXmAgOAC9d8apqzoRnQDxl9o0EkdGf0SB8Kxk/edit?usp=sharing

**Describe alternatives you've considered**

We could leave it as it is but results in not enough nutrient update from upper layers and too much nutrient deposition in lower layers on plant death

**Additional context**

**Target Deadline**
July 23

**Comment by PooyaHekmati** [comment]
To be worked on in sprint 19.
