### ISSUE TITLE
[Crop & Soil] Restructure Crop and CropData classes.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1815]
## Problem

A common pattern in the crop and soil submodules is the use of catch-all dataclasses, i.e., CropData and SoilData, that contain all the relevant attributes, and then those attributes get updated by some modifying functions. This approach keeps all the data together in one place, making it easier to access and update. However, those classes are large and harder to maintain. One tricky thing is that multiple classes can modify the same data, possibly leading to buggy behaviors and race conditions.

## Proposed Solution

We should break up the CropData class into smaller, more focused dataclasses and then use composition to build it back up. So now a class like NitrogenIncorporation should interact only with a subset of the relevant data in a CropData object. This helps reduce the extent of the coupling and should be done with the single responsibility principle in mind.

The following diagrams illustrate these proposed changes.

Crop class decomposition
The Crop class will be composed of various subcomponents, including CropData, GrowthConstraints, BiomassAllocation, WaterDynamics, WaterUptake, NitrogenIncorporation, PhosphorusIncorporation, HeatUnits, LeafAreaIndex, RootDevelopment, CropManagement, and Dormancy.

![Screenshot 2024-07-15 at 5 29 39 PM](https://github.com/user-attachments/assets/09c5fc01-3784-4876-9f3c-f7153f997e05)

The CropData class can be further broken down into smaller dataclasses such as CropIdentification, CropGrowth, CropNutrients, CropWater, and CropYield.

CropData class decomposition

- CropIdentification contains crop species, name, and plant category information, etc.
- CropGrowth holds data related to leaf area index, biomass, root depth, etc.
- CropNutrients stores information about nitrogen and phosphorus levels among others.
- CropWater includes water stress and water uptake data.
- CropYield contains harvest index and yield residue information.

![Screenshot 2024-07-15 at 5 32 57 PM](https://github.com/user-attachments/assets/c82c4984-53d2-45b0-8e38-d9954df703c6)

Each subcomponent of the Crop class interacts with a specific subset of the CropData class, promoting the single responsibility principle and reducing coupling.
The grow_crop() method in the Crop class orchestrates the interactions between the subcomponents and the CropData class.

## Alternative Solution to breaking down CropData into smaller dataclasses
Instead of creating more data classes, we identify the attributes in CropData that are only used by one crop component, and make them attributes of that component directly.

**Comment by KFosterReed** [comment]
This looks like a great plan to me and will hopefully add clarity to the multiple functions that affect crop growth that in reality happen simultaeneously and in RuFality have to have an order of operations. 

Edit: If this work can proceed without impact on I/O, then let's push this forward

**Comment by Isgotkowitz** [comment]
Grooming session: @Isgotkowitz and @ew3361zh will research/investigate how to address this issue without over- or undergeneralization of data. Will have some results by end of sprint 21 - Aug 28
