### ISSUE TITLE
[Crop & Soil] Break down main methods in field data reporter

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1818]
Split the two main reporter methods in FieldDataReporter into smaller, more focused reporter methods.

![Screenshot 2024-07-16 at 10 34 56 AM](https://github.com/user-attachments/assets/06d55ac7-6eb1-4660-ad3a-11d12b66bd0b)

The above diagram illustrates the proposed breakdown of send_daily_variables() and send_annual_variables() methods.
#### send_daily_variables() submethods	
- send_field_daily_variables() sends daily variables specific to the field. E.g., current_residue, transpiration, max_transpiration, etc.
- send_soil_daily_variables() handles sending variables related to the soil. E.g., water_evaporated, eroded_sediment, accumulated_runoff, etc.
- send_vadose_zone_layer_daily_variables() is responsible for sending daily variables for the vadose zone layer. E.g., active_organic_nitrogen_content, stable_organic_nitrogen_content, nitrate_content, fresh_organic_nitrogen_content, etc.
- send_soil_layer_daily_variables() handles sending daily variables for each soil layer. E.g., temperature, percolated_water, water_content, etc.
- send_crop_daily_variables() sends daily variables related to the crops. E.g., root_depth, biomass, usable_light, biomass_growth_max, etc.
#### send_annual_variables() submethods
- send_field_annual_variables() sends annual variables specific to the field. Currently, there is only one variable — annual_irrigation_water_use_total.
- send_soil_annual_variables() is responsible for sending annual variables related to the soil. E.g., annual_water_content_change, annual_nitrates_content_change, annual_soil_evaporation_total, etc.
- send_soil_layer_annual_variables() sends annual variables for each soil layer. E.g., annual_nitrous_oxide_emissions_total, annual_ammonia_emissions_total, annual_decomposition_carbon_CO2_lost, etc.

**Comment by KFosterReed** [comment]
I like this proposal and think it will make the field data outputs easier to work with! 

Please hold off on this one for at least one more month though as it will affect the FARM-ES team's deployment.
