### ISSUE TITLE
[Crop & Soil] Break down how fields are set up in FieldManager

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1819]
In FieldManager, _setup_field() is fairly complex so it should be broken down further where we move the field schedule setup method functionality into the data setup methods (where applicable).

#### _setup_field will contain the following methods:
- _setup_field_data() will focus on initializing the FieldData instance with the necessary attributes such as field_name, field_size, absolute_latitude, longitude, etc.
- _setup_soil_data() will handle the setup of the soil profile for the field and it will create the Soil instance. 
- _setup_fertilizer_data() will be responsible for setting up the fertilizer_related data for the field. It will also contain the functionality from the setup_fertilizer_schedule() submethod to create a FertilizerSchedule instance and retrieve the available fertilizer mixes.
- _setup_manure_data() will handle the setup of manure-related data for the field. It will contain the functionality in the _setup_manure_schedule() submethod to create a ManureSchedule instance.
- _setup_tillage_data() will be responsible for setting up the tillage-related data for the field. It will contain the functionality in the _setup_tillage_schedule() submethod to create TillageSchedule instance.
- _setup_crop_data() handles the setup of crop-related data for the field. It will contain the _setup_crop_schedules() submethod to create CropSchedule instances and generate planting and harvest events.

**Comment by KFosterReed** [comment]
This one feels like a home run! Let's do it!
