### ISSUE TITLE
[Crop & Soil] Restructure Schedule class and its subclasses

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1820]
#### Methods in the Schedule class are general enough to be moved to the Utility class:
1. elongate_list() lengthens a list to match the length of a reference list.
2. repeat_pattern() repeats a pattern of numbers based on the specified skip and repeat parameters.
3. validate_pattern_parameters() validates a set of parameters against a set of validation rules for a given schedule.
#### In Schedule subclasses:
1. The generate_*_events() methods in the Schedule subclasses share some common logic so a base class like EventGenerator would be helpful.
- The EventGenerator class will contain a common method generate_events() that generates events based on the provided event class, event arguments, pattern years, etc.
2. The _validate_*_parameters() follow the same pattern of checking a set of parameters against a set of validation rules, so it is possible to create a common method _validate_parameters() in the base Schedule class to perform the actual validation.
- Each _validate_*_parameters() method in the Schedule subclasses can focus on preparing the necessary parameters and validation rules and pass them to the _validate_parameters() method in the base class.
3. _determine_if_all_non_negative_values() - checks that all values in a list are >= 0. Could be moved to Utility class.

Example refactoring:
![Screenshot 2024-07-16 at 11 26 24 AM](https://github.com/user-attachments/assets/2cc7e6e8-34d7-475b-b4a0-81aaa58110fb)

**Comment by Isgotkowitz** [comment]
This is issue seems pretty similar to #561 - maybe it would be good to close it as unplanned and have this be the only issue pertaining to `Schedule`?

**Comment by KFosterReed** [comment]
Love this plan! A bit of context, methods for scheduling field operations are a challenge that all soil and crop modules face. Most models opted for reduced options for what the field's management schedule actually is. In RuFaS, we have kept it open for the user to decide which has been a tough objective to maintain both from the user input and implementation side of things. This seems like an excellent next step to keep that flexibility and improve the code clarity by making these methods more general and widely applicable. Well done!

This also gets the green light from me to start working on
