### ISSUE TITLE
[Animal] Refactor Design for DigestiveSystem [2/3]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1838]
Clarify the inputs, outputs, and the logic for the DigestiveSystem.

**Comment by allisterakun** [comment]
Here is the design document: [Digestive System](https://docs.google.com/document/d/1vY7EoFhiwWhCO9f_BNn01K0c_DohBlbZqdEEIBXgHG4/edit)

**Comment by tomhuhh** [comment]
The design doc looks good to me. I just left a minor comment. Thanks Allister!
