### ISSUE TITLE
[Animal] Refactor Design for AnimalGrowth [2/3]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1839]
Clarify the inputs, outputs, and the logic for the AnimalGrowth.

**Comment by allisterakun** [comment]
Here is the design document: [Animal Growth](https://docs.google.com/document/d/1Y1itje2VDS6LnJ_Y48fH9LGhfOztkAJoC2ItAMuSTek/edit?usp=sharing)

**Comment by jadamchick** [comment]
Hey Allister, this design doc looks clear and succinct. 
Depending on what level of detail you are typically going into for these docs, there might be value to defining the functions (such as get_bw_change) and/or linking to the scientific documentation? As is, it isn't really a stand-alone resource, but maybe that isn't the point.

**Comment by allisterakun** [comment]
Updated the function definitions!
