### ISSUE TITLE
Crop & Soil unit testing

### ISSUE THREAD

**Issue by Brandon-DeBoer** [RuminantFarmSystems/RuFaS#184]
I'll use this issue as a tracker for what I've tested so far in the C&S module, broken down by file and function. All files tested belong to the RUFAS/routines directory, more specific file paths will be provided 

* [ ] `field/field.py`

## Crop

* `field/crop/biomass.py`
   - [ ] `update_all()`
   - [x] `calc_act_biomass()`
   - [x] `calc_intercepted_radiation()`
   - [x] `calc_bio_AG()`
   - [x] `calc_gamma_wu()`

* `field/crop/crop.py`
  - [ ] `daily_crop_routine()`
  - [ ] `daily_reset()`
  - [ ] `annual_variable_update()`
  - [ ] `annual_crop_routine()`
  - [ ] `dormancy_routine()`
  - [ ] `is_kill_year()`
  - [ ] `Crop.__init__()`
  - [ ] `Crop.set_grow_regimen()`
  - [ ] `Crop.annual_reset()`
  - [ ] `Crop.iterate_planting_day()`
  - [ ] `calculate_start()`
  - [ ] `calculate_mimimum_day_length()`
  - [ ] `calculate_t_dorm()`
  - [ ] `in_dormancy()`
  - [ ] `get_year_length()`
  - [ ] `check_conditions_plant()`

* `field/crop/crop_types/base_crop.py`
  - [ ] `BaseCrop.__init__()`
  - [ ] `BaseCrop._use_data()`
  - [ ] `BaseCrop._set_crop_name()`
  - [ ] `BaseCrop._get_crop_data()`
  - [ ] `BaseCrop._set_species()`
  - [ ] `BaseCrop._set_species_attributes()`

* `field/crop/growth_constraints.py`
  - [ ] `update_all()`
  - [ ] `calc_gamma_reg()`
  - [x] `calc_w_stress()`
  - [ ] `calc_t_stress()`
  - [x] `calc_n_stress()`
  - [x] `calc_phi_N()`
  - [x] `calc_p_stress()`
  - [x] `calc_phi_P()`

* `field/crop/heat_units.py`
  - [ ] `update_all()`
  - [x] `calculate_fr_PHU()`
  - [x] `calculate_T_HU_min()`
  - [x] `calc_T_HU_max()`
  - [x] `calc_HU()`

* `field/crop/leaf_area_index.py`
   - [ ] `update_all()`
   - [x] `calculate_shape_coefficients()`
   - [x] `calc_fr_LAI_max()`
   - [x] `calculate_d_LAI_actual()`
   - [x] `calculate_LAI_actual()`

* `field/crop/nitrogen_fixation.py`
  - [x] `calc_N_fixation()`
  - [x] `get_root_accessible_layers()`
  - [x] `calc_f_gr()`
  - [x] `calc_f_NO3()`
  - [x] `calc_f_sw()`
  - [x] `calc_N_demand()`

* `field/crop/nitrogen_uptake.py`
   - [x] `update_all()`
   - [x] `calc_N_up_z()`
   - [x] `calc_fr_N()`
   - [x] `calc_n2()`
   - [x] `calc_n1()`
   - [x] `calc_log_term_of_shape_coefficients()`
   - [x] `calc_bio_N_opt()`
   - [x] `calc_N_up()`
   - [x] `calc_act_N_up_each_layer()`
   - [x] `N_uptake()`
   - [x] `calc_N_up_each_layer()`
   - [x] `calc_N_up_z()`
   - [x] `calc_bio_N()`

* `field/crop/phosphorus_uptake.py`
  - [ ] `update_all()`
  - [ ] `calc_fr_P()`
  - [ ] `calc_p2()`
  - [ ] `calc_p1()`
  - [x] `calc_log_term_of_shape_coefficient()`
  - [ ] `calc_bio_P_opt()`
  - [ ] `calc_P_up()`
  - [ ] `calc_act_P_up_each_layer()`
  - [ ] `calc_P_up_each_layer()`
  - [ ] `calc_P_up_z()`
  - [ ] `calc_bio_P()`
  - [ ] `P_uptake()`

* `field/crop/root_development.py`
   - [ ] `update_all()`
   - [x] `calc_daily_root_biomass()`
   - [x] `calc_z_root()`

* `field/crop/transpiration.py`
  - [ ] `update_all()`
  - [ ] `calc_max_water_uptake_each_layer()`
  - [ ] `calc_max_water_uptake_z()`
  - [ ] `inc_lower_layer_uptake()`
  - [ ] `decrease_efficiency_of_uptake()`
  - [ ] `calc_act_water_uptake()`

* `field/crop/yields.py`
   - [ ] `update_all()`
   - [x] `calc_HI_max()`
   - [x] `calc_HI_act()`
   - [x] `calc_dry_down()`
   - [x] `calc_yield_max()`
   - [x] `calc_yield_act()`
   - [ ] `calc_quality_assessment()`
   - [x] `calc_nutrient_removal()`
   - [ ] `calc_residue()`
   - [ ] `calc_harvest_quality()`
   - [ ] `kill()`
   - [x] `cut()`
   - [ ] `update_all()`

## Field Management

* [ ] `field/field_management/fertilizer_application.py`
* [ ] `field/field_management/field_management.py`
* [ ] `field/field_management/manure_application.py`
* [ ] `field/field_management/tillage_application.py`

## Soil

* [ ] `field/soil/carbon_cycling/carbon_cycle.py`
* [ ] `field/soil/carbon_cycling/decomp_factors.py`
* [ ] `field/soil/carbon_cycling/pool_gas_partitioning.py`
* [ ] `field/soil/carbon_cycling/residue_partitioning.py`

* [ ] `field/soil/nitrogen_cycling/denitrification.py`
* [ ] `field/soil/nitrogen_cycling/humus_mineralization.py`
* [ ] `field/soil/nitrogen_cycling/leaching_runoff_erosion.py`
* [ ] `field/soil/nitrogen_cycling/mineralization_decomp.py`
* [ ] `field/soil/nitrogen_cycling/nitrification_volatilization.py`
* [ ] `field/soil/nitrogen_cycling/nitrogen_cycling.py`

* [ ] `field/soil/phosphorus_cycling/erosion.py`
* [ ] `field/soil/phosphorus_cycling/fert_leach.py`
* [ ] `field/soil/phosphorus_cycling/manure_leach.py`
* [ ] `field/soil/phosphorus_cycling/P_mineralization.py`
* [ ] `field/soil/phosphorus_cycling/phosphorus_cycling.py`
* [ ] `field/soil/phosphorus_cycling/soluble_P.py`

* [ ] `field/soil/evapotranspiration.py`
* [ ] `field/soil/infiltration.py`
* [ ] `field/soil/percolation.py`
* [ ] `field/soil/soil.py`
* [ ] `field/soil/soil_erosion.py`

* `field/soil/soil_temp.py`
   - [ ] `calc_T_soil()`
   - [x] `calc_dd()`
   - [x] `calc_scale()`
   - [x] `calc_dd_max()`
   - [x] `sum_soil_water()`
   - [x] `calc_T_surf()`
   - [x] `calc_T_bare()`
   - [x] `calc_radiate()`
   - [x] `calc_albedo()`
   - [x] `calc_bcv()`

* [ ] `field/soil//soil_water.py`

**Comment by morrowcj** [comment]
These tests will be fully implemented in #223, with updated names.

**Comment by Isgotkowitz** [comment]
Closed with #714
