### ISSUE TITLE
[Crop & Soil] Disentangle Crop Class from other C&S classes

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1847]
A sub issue of #1544, all Field component modules should be disentangled. 

## Expected Behavior

Crop and the functions it contains should be able to be run independently of other C&S classes and Field itself. All communications and transfers of data between Crop and other C&S classes should happen at the `Field` level.

## Current Behavior

Currently Field handles the following crop-creating functionalities:
- `_make_crop_from_config_dict()` - initialize a new crop from a configuration dictionary.
- `_make_supported_crop()` - create a crop instance with attributes determined by species of the crops.
- `_make_custom_crop()` - create a crop instance with customized attributes.

 Some of these functionalities currently in Field may not be able to be further disentangled but it is worth examining. Many of them have functionalities that could be moved to the Crop class and then be coordinated by Field.
- `_harvest_heat_scheduled_crops()`
- `_plant_crop()`
- `_harvest_crop()`
- `_remove_dead_crops()`
- `_assess_dormancy()`
- `_execute_daily_processes()`
- `_cycle_water()`
- `_handle_water_in_crop_canopies()`
- `_evaporate_from_crop_canopies()`
- `_determine_total_above_ground_biomass()`

## Possible Solution

Migrating a lot of the functionalities in the above methods from Field to Crop would make crop more active and more encapsulated. It would also clean up the Field class from having to do so much of the work that should be in Crop.

### Important to note:
There are sister issues as a part of the C&S Action Items that focus on refactoring the Crop class. It would probably be a good idea do #1815 and #1816 in the same sprint (same SWE) as this issue.

**Comment by KFosterReed** [comment]
This proposal makes sense to me. As suggested, I agree that there may be some functions that cannot easily or fully be moved to teh Crop class, `cycle_water` for example. However, it is worth pursuing this in general to improve the oranization and boundaries between field and crop.

This seems like one that can be started now.
