### ISSUE TITLE
[Weather] Remove unnecessary calls to `_get_latitude` in `Weather`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1851]
The way that `_get_latitude` is used in the `Weather` module should be simplified.

## Status

The method `_get_latitude` is called in two different places in the `Weather` module, `get_conditions_series` and `get_current_day_conditions`. These method calls are redundant, because `_get_latitude` produces the same result every time it is called.

## Intention

By making a single call to `_get_latitude` instead of a call every single time that a Current Day Conditions instance is retrieved, the number of method calls to both `_get_latitude` and Input Manager's `get_data` can be reduced significantly. Additionally, if there was no latitude provided to a simulation, then the number of warnings will be significantly reduced as well.

## Request

Call `_get_latitude` in the `init` routine of `Weather`, and store the latitude as an instance attribute.

**Comment by ew3361zh** [comment]
Grooming session:
- Latitude shouldn't be stored in Weather (latitude isn't an aspect of weather), it should be stored in Field.
- Weather should request this information from Field.
- Hairy situations: latitude is used to get day-length. Right now C&S is the only module that uses it. But other modules may need this information. How to ensure they are using the correct latitude and not a default?
