### ISSUE TITLE
[IM][Wiki] Updated array validation

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1855]
From the chat:
Pooya Hekmati
  3:46 PM
team, are we running validation for individual elements within an array, or is it wip?
[3:46]
in the context of IM

Allister Liu
  3:47 PM
We’re validating every single item within the array. This happens in IM._array_type_validator()

Pooya Hekmati
  3:48 PM
Thanks Allister. So, we route to the correct validator? I.e., if the elements is a string, we check the regex, if it is a number we check min and max, etc?

Niko Tomlinson
  [3:52 PM]
Correct, we route each array element to the appropriate element-type validator

Allister Liu
  [3:52 PM](https://ruminantfarmsystems.slack.com/archives/C04AWM1BLRE/p1721764376568759)
Yes, confirming that

Pooya Hekmati
  [3:52 PM]
so the wiki is outdated

------------------------
This refers to https://github.com/RuminantFarmSystems/MASM/wiki/Input-Manager#the-properties-blob .
Update this section to reflect the new behaviour.

**Comment by ew3361zh** [comment]
Grooming session: 
- use pieces of the IM diagram to further explain different sections of the IM wiki.
- expand table explaining data validation guidelines to include whether guidelines are applicable to an entire array/object or to an element of the array/object or both.
