### ISSUE TITLE
Report generator crashes when given too many Nones

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1856]
![image](https://github.com/user-attachments/assets/56d22c23-c469-4448-b6d4-2e5c6157e3db)

Running the `sobol` branch using the fractional factorial method (@JoeWaddell may have local changes that mean it won't replicate the error - before tackling this issue, have me sync).

## Current Behavior

Simulation claims to have run successfully, but doesn't! Using the debugger, it seems to be a None type creeping in to the `data` field(s). 

## Possible Solution

The attempts I made so far were just making the existing code less elegant: I think it's upstream of this method, as it seems instead of an empty list, it's getting a None type object instead.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ew3361zh** [comment]
Grooming session:
- @JoeWaddell could you comment with the report filter and what inputs you were using when you encountered this error?
- Should also try to catch this error for future cases. We shouldn't need to change the aggregation functions but when we call them it should be wrapped in a try/except.

**Comment by JoeWaddell** [comment]
The report filter I used: [report_S30.json](https://github.com/user-attachments/files/16376926/report_S30.json)

For the inputs I used...this is trickier! I was using the `sobol` branch, and running this input file. 
[sobol_animal_tasks.json](https://github.com/user-attachments/files/16376931/sobol_animal_tasks.json)

However, it's only some runs that raise the error - you can see in this summary sheet I made doing some metaanalysis of the output logs, note the failed runs that *don't* have 9e24 as the simulation time. 
[sensitivity_analysis global animal FF run summaries.xlsx](https://github.com/user-attachments/files/16376915/sensitivity_analysis.global.animal.FF.run.summaries.xlsx)

Attached a log error file to show said error message. Can happily send any more files you need, and can meet to discuss this one on one. Hopefully this slew of files is enough to start with!
[test-9-animal_S256 run 019_errors_15-Jul-2024_Mon_19-56-56.json](https://github.com/user-attachments/files/16376999/test-9-animal_S256.run.019_errors_15-Jul-2024_Mon_19-56-56.json)

**Comment by matthew7838** [comment]
Using try-catch in TM.

**Comment by matthew7838** [comment]
The investigation is done. Errors were try-catched, we will return some information after the multiprocessing regarding failed tasks and add more details when adding the errors.
