### ISSUE TITLE
Add Representation of 'Cap and Flare' to outdoor manure storage/treatment systems 

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1857]
**Is your feature request related to a problem? Please describe.**
This manure management strategy covers long term liquid and slurry storage systems to capture the methane produced by the manure and then burns the methane to convert it to CO2 (which, in this case is not a greenhouse gas). Although, in theory, this practice could eliminate all of GHG emissions from the methane produced during storage, in practice, the burning or 'flaring' is not 100% effective and some methane still escapes depending on the weather and seal of the cover. This technology was on our original V1 requirements and we would like to add a simple representation of this method that is a modifier of our current `slurry storage outdoor` and `anaerobic lagoon` methods. 

**Describe the solution you'd like**
I propose a relatively simple modification to the existing methods for estimating methane emissions from outdoor slurry storage and anaerobic lagoons which will reduce the current estimates of methane emission from these systems by the reported average methane destruction efficiency of 81%. I think we can achieve this with the following steps:

1. Add an input option to the current `"manure_cover"` input field within the `"manure_treatment_configs"` section of the `manure_management` input file. The new option could be `"cover and flare"` to indicate that this storage system has a cover as well as a flare. 
2. Add either a new input or a manure module constant that is the `methane_destruction_efficiency` with a default value of 81%
3. In the methane update methods in `slurry_storage_outdoor.py` and `anaerobic_lagoon.py` use the new `cover and flare` input to indicate that when this input is provided, the methane predicted by the `methane_emission_from_slurry_storage` is multiplied by `(1- methane_destruction_efficiency/100)` before it is recorded in the `daily_output.storage_methane`
4. Add a new daily output from the manure treatment methods that is something like `storage_methane_avoided` and if the `cover and flare` input is provided, set this new output equal to the  `methane_emission*methane_destruction_efficiency/100`

**Describe alternatives you've considered**
There are many places that this 'methane destruction' could take place. We could, for example, implement the partitioning of the storage methane into the avoided/burned methane and the methane emission within the `methane_emission_from_slurry_storage` method in `calculator.py`. Alternatively, these could be implemented in the manure treatment files as suggested above. A third option would be to apply these calculations in the EEE module, although this seems like the least appropriate to me because it is a modification of a manure management practice and thus a change to the biophysical outcomes, not the way these outcomes are summarized.

**Additional context**
I have attached a white paper by April Leytem where she references the average methane destruction efficiency value I am proposing. 

In the future, we would like to make the methane destruction efficiency value a function of weather and specific manure storage attributes but we do not know enough about these relationships to define the underlying equations to be able to implement this at this time.  

[Cap and Flare White Paper - Final.docx](https://github.com/user-attachments/files/16365180/Cap.and.Flare.White.Paper.-.Final.docx)

**Target Deadline**
August 30th if feasible

**Comment by PooyaHekmati** [comment]
To be done in Sprint 20.

**Comment by matthew7838** [comment]
@KFosterReed regarding `methane predicted by the methane_emission_from_slurry_storage`, just to confirm that the calculations be applied on both outputs? The method returns methane_emission and methane_emission_from_degradable_volatile_solids.
