### ISSUE TITLE
Graphics Production Error with Certain Feeds due to improper filename parsing

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#186]
Some feeds have a parentheses in their name. For example feed #81: 'Grass-LEGUME MIXTURES Pr. LG. (10-13% HCEL.)'. Somewhere in the graphics production in the output handler, the filename causes an error and stops all graphics production. 
## Expected Behavior

It should produce and save a graph of each feed used for each pen - no matter what the name is. 

## Current Behavior

Instead, it produces this error: 
![image (4)](https://user-images.githubusercontent.com/41019131/185443210-d9a064df-4a80-45d9-a581-aa5a0a832af4.png)

I think the problem occurs in the backend_bases.py file that is part of the matplotlib package. On line 2142, the call to os.path.splittext() results in a setting the format as '))' instead of 'png'

## Possible Solution

Not sure? Change the feed names so they don't have parentheses?

## Steps to Reproduce

1. Run any file with an input of feed #81
2.
3.
4.

## Context (Environment)

We need to be able to simulate the use of all feeds and of course see what the outcomes of using those feeds are. The parentheses in the feed names provide distinguishing information for feeds that come from the same type of plant but we can maybe find another way to do this?

**Comment by ew3361zh** [comment]
Solved with [PR 265](https://github.com/RuminantFarmSystems/MASM/pull/265)
