### ISSUE TITLE
[Animal] Some combinations of gestation length and days in preg when dry can cause crash

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#1880]
## Expected Behavior

No crashing!

## Current Behavior

Currently in `cow.py` and specifically `get_bw_change`, the lines
```
bodyweight_tissue = self.tissue_changed / (
                    self.gestation_length - AnimalBase.config["days_in_preg_when_dry"]
                )
``` 
cause a problem if the `self.gestation_length` and `AnimalBase.config["days_in_preg_when_dry"]` are equal.

Such a case can happen given `gestation_length` is set in `_calculate_gestation_length` from `heiferII.py`, which use `AnimalBase.config["avg_gestation_len"]` and `AnimalBase.config["std_gestation_len"]`

## Possible Solution

Simplest fix is wrapping the equation in a try except block
```
            try:
                bodyweight_tissue = self.tissue_changed / (
                    self.gestation_length - AnimalBase.config["days_in_preg_when_dry"]
                )
            except:
                bodyweight_tissue = self.tissue_changed
```

However I'm uncertain this is ideal, as we could instead elect a more typical value in place of the denominator, e.g. the average for animals in their dry period.

## Steps to Reproduce

Modify the `default_animal.json` such that:
`"days_in_preg_when_dry": 282,` and `"avg_gestation_len": 320,`

**Comment by Isgotkowitz** [comment]
Grooming session: @allisterakun will revisit this issue and discuss it with SMEs before we groom it.

**Comment by Isgotkowitz** [comment]
Investigated this a little. With the help of @jadamchick, found that the problematic code should never be reached - the fact that it is reached indicates an error. With a little investigation, it seems that this only occurs when cows enter the herd at initialization.

I added the following code and ran the default sim with the values changed as above: 
```python
else:  # dry period
    if self.gestation_length <= AnimalBase.config["days_in_preg_when_dry"]:
        print(f"\n{self.days_born=} {self.id=} {self.events.events}")
    try:
        bodyweight_tissue = self.tissue_changed / (
            self.gestation_length - AnimalBase.config["days_in_preg_when_dry"]
        )
    except ZeroDivisionError:
        bodyweight_tissue = 0.0
```
It seems that every cow which has info printed for it has the same set of events: pregnancy checks 1, 2, and 3, then they are dry, then they enter the herd through initialization.

**Comment by Isgotkowitz** [comment]
After more investigation, I \*think\* I understand why this is happening. When animals are simulated for herd initialization, that initialization run may have different management inputs (such as "days_in_preg_when_dry") than the simulation which is pulling in those cows.

This breaks the assumption that is implicit in `Cow.milking_update`, which is that if a cow is pregnant and hasn't reached her dry-off day yet, she is in milk.

Potential solution: check animals entering the herd at initialization (and also when they are brought in as replacements too maybe - still unclear on that one) if they are pregnant and haven't reached the dry-off day yet then set them to be milking.

The pro is that this modifies the animals entering the herd to conform to the management practices specified for that simulation - which is really good! We don't want animals configured for management practices that are different from what the user specified for a simulation.

The con is that there would have to be some assumptions made about how many days the cow was in milk before she entered the herd.

**Comment by jadamchick** [comment]
I like it! 
Just to push back slightly -- why do you have to know Days In Milk? Could you just use Days In Preg? compare it to the herd's "days_in_preg_when_dry" and then assign her to either be Dry or Milking based on that? 
(Oh -- but if she is needing to switch from Dry to Milking, then you need to assign her a Days In Milk at that point, I bet... I take it back!). 

RuFaS does report this value as an output (by parity), so maybe you could use the specific herd's values? AnimalModuleReporter.report_life_cycle_manager_data.calving_to_preg_time_1

**Comment by Isgotkowitz** [comment]
> I like it! Just to push back slightly -- why do you have to know Days In Milk? Could you just use Days In Preg? compare it to the herd's "days_in_preg_when_dry" and then assign her to either be Dry or Milking based on that? (Oh -- but if she is needing to switch from Dry to Milking, then you need to assign her a Days In Milk at that point, I bet... I take it back!).

@jadamchick yes that is exactly right.

> RuFaS does report this value as an output (by parity), so maybe you could use the specific herd's values? AnimalModuleReporter.report_life_cycle_manager_data.calving_to_preg_time_1

I think it is possible to be even more precise, by finding exact day when a cow had her last calf and deriving the value from that
