### ISSUE TITLE
[GH Actions] Update the Sphinx GitHub Action

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1886]
The Sphinx GitHub Action needs to be updated so that it will run correctly.

## Status

The Sphinx GitHub Action is currently disabled and has not been run in a while. As a result, it no longer runs when triggered manually.

## Intention

A working Sphinx GitHub Action that can be triggered manually.

## Request

Work on the Sphinx GitHub Action until it runs properly again.

### Additional Information
It should be investigated when exactly this action should be run automatically. We may want it run automatically on any PR that is going from `test` to `main` but only run on any other PR if it is manually triggered, for example.

**Comment by PooyaHekmati** [comment]
This action doesn't need any automatic triggers at this point in time, being able to run it manually is enough.
