### ISSUE TITLE
Homegrown Feed Emission Estimator Error

### ISSUE THREAD

**Issue by krb78** [RuminantFarmSystems/RuFaS#1899]
The homegrown feed emission estimator works perfect, until you don't end your simulation at day 365 and instead end your simulation at another date. It gives a 0 for every homegrown feed if you choose a date other than 365. 

## Expected Behavior
The goal is that regardless of the day the simulation ends on, we can gather emissions from the last 365 days of the simulation and aggregate them into this single output. 

## Current Behavior
If a date other than YEAR:365 is put into the config as the end date, we get 0's for every single feed. This will occur if the plant is actually not being harvested (and that is normal), but in this case, the plants are being harvested and there is still no emissions. (for example, you can set the date to YEAR:364 and still get a 0 even if nothing of note is happening for the crop on day 365). 

Kristan thinks that perhaps this is occurring because the day_cutoff and year_cutoff are being used to collect filter outputs and therefore RuFaS is not "seeing" day 365 of year 1 as happening prior to day 1 of year 2. 

## Possible Solution
I think we will need to change the year_cutoff logic such that we are slicing the last 365 days (the same way a filter slice works) so that regardless of the day the simulation is stopped, the 365 days prior are what are summed for the emissions estimator

## Steps to Reproduce
1. I was using FARMES_fakefarm1 and set the end date of the configuration to be 2023:364 (or 294 or truly anything other than 365)
2. Using this filter you can see that the "Homegrown Feed Emissions" don't calculate, but all the following (phosphorus runoff, soil erosion, N2O emissions, NH3 emissions, etc) do.  
        {"name": "Homegrown Feed Emissions - Alfalfa Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_alfalfa_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {
            "name": "Homegrown Feed Totals",
            "filters": [".*_calculate_total_homegrown_feed_amounts_by_crop_type.homegrown_feed_totals.*"]
        },

        {"name": "Homegrown Feed Emissions - Alfalfa Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_alfalfa_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Alfalfa Baleage",
            "filters": [".*homegrown_feed_emissions.homegrown_alfalfa_baleage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Rye Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_cereal_rye_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Rye Grain",
            "filters": [".*homegrown_feed_emissions.homegrown_cereal_rye_grain_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Rye Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_cereal_rye_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Rye Baleage",
            "filters": [".*homegrown_feed_emissions.homegrown_cereal_rye_baleage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Corn Grain",
            "filters": [".*homegrown_feed_emissions.homegrown_corn_grain_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Corn Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_corn_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Soybean Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_soybean_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Soybean Grain",
            "filters": [".*homegrown_feed_emissions.homegrown_soybean_grain_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Grass Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_tall_fescue_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Grass Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_tall_fescue_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Grass Baleage",
            "filters": [".*homegrown_feed_emissions.homegrown_tall_fescue_baleage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Triticale Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_triticale_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Triticale Grain",
            "filters": [".*homegrown_feed_emissions.homegrown_triticale_grain_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Triticale Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_triticale_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Triticale Baleage",
            "filters": [".*homegrown_feed_emissions.homegrown_triticale_baleage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Winter Wheat Hay",
            "filters": [".*homegrown_feed_emissions.homegrown_winter_wheat_hay_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Winter Wheat Grain",
            "filters": [".*homegrown_feed_emissions.homegrown_winter_wheat_grain_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Winter Wheat Silage",
            "filters": [".*homegrown_feed_emissions.homegrown_winter_wheat_silage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {"name": "Homegrown Feed Emissions - Winter Wheat Baleage",
            "filters": [".*homegrown_feed_emissions.homegrown_winter_wheat_baleage_emissions.*"],
            "variables": [
                "nitrous_oxide_emissions",
                "ammonia_emissions",
                "carbon_stock_change",
                "nitrogen_fertilizer_used",
                "nitrogen_fertilizer_embedded_CO2_emissions",
                "phosphorus_fertilizer_used",
                "phosphorus_fertilizer_embedded_CO2_emissions",
                "potassium_fertilizer_used",
                "potassium_fertilizer_embedded_CO2_emissions",
                "manure_nitrogen_used",
                "manure_nitrogen_requested"
            ],
            "vertical_aggregation": "sum"
        },
        {
            "name": "Total eroded sediment",
            "filters": [
                "FieldDataReporter.send_daily_variables.eroded_sediment.field.*"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Phosphorus Runoff",
            "filters": [
                "FieldDataReporter.send_daily_variables.soil_phosphorus_runoff.field.*"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Fertilizer P Runoff",
            "filters": [
                "FieldDataReporter.send_daily_variables.runoff_fertilizer_phosphorus.field='.*'"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Nitrate Percolate",
            "filters": [
                "FieldDataReporter.send_daily_variables.percolated_nitrates.field='.*',layer='3'"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Soil CO2 emissions",
            "filters": [
                "FieldDataReporter.send_daily_variables.profile_carbon_emissions.field.*"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Soil N2O emissions",
            "filters": [
                "FieldDataReporter.send_daily_variables.nitrous_oxide_emissions.field=.*,layer=.*"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "Soil NH3 emissions",
            "filters": [
                "FieldDataReporter.send_daily_variables.ammonia_emissions.field=.*,layer=.*"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -365
        },
        {
            "name": "profile_carbon_total-1",
            "filters": [
                "FieldDataReporter.send_daily_variables.total_soil_carbon_amount.field=.*"
            ],
            "slice_start": -1
        },
        {
            "name": "profile_carbon_total-365",
            "filters": [
                "FieldDataReporter.send_daily_variables.total_soil_carbon_amount.field=.*"
            ],
            "slice_start": -365,
            "slice_end": -364
        }

## Target Deadline
Do you want me truest of true dreams? This would be complete ASAP (end of august at the latest) so it can be pulled in for FARM ES.

**Comment by Isgotkowitz** [comment]
> Kristan thinks that perhaps this is occurring because the day_cutoff and year_cutoff are being used to collect filter outputs and therefore RuFaS is not "seeing" day 365 of year 1 as happening prior to day 1 of year 2.

@KFosterReed nailed it, as usual.

The problem is located in the following lines of code, within method `_gather_homegrown_feeds_and_fertilizer_apps` in `RUFAS/routines/EEE/emissions.py` (lines 141 - 145):
```python
filtered_yields = list(
    filter(
        lambda crop: crop["harvest_day"] >= day_cutoff and crop["harvest_year"] >= year_cutoff, processed_yields
    )
)
```
The reason this filter fails when the ending simulation day is pushed forward by a day (going from 365 to 364) is that the `day_cutoff` is expected to be low (i.e. it is expected to be day 1) and when it gets pushed forward a day it goes from 1 to 365. This results in `crop["harvest_day"] >= day_cutoff` evaluating to false when we want it to be true.

Suggested solution: create `datetime.date`s with the cutoff and harvest dates, then execute the comparison.
