### ISSUE TITLE
[Feed Storage] [Time] Use alternative to `Time` in Feed Storage module when tracking dates in order to remove `deepcopy`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1922]
Instances of `Time` are used to track dates in the Feed Storage module, and these instances created using `deepcopy`. This slows down the code dramatically when processing degradations in the Feed Storage module.

## Status

`HarvestedCrop`s use instances of the `Time` module to track dates - when the crop was harvested, stored, and last degraded. The instances are created from other `Time` instances using `deepcopy`, so that the time is preserved and doesn't keep moving forward as the main `Time` instance is incremented.

## Intention

Make the code run faster by switching to a way of tracking time that does not require the use of `deepcopy`.

## Request

Instead of using `Time` instances to track dates, use `datetime.date` instances. This is just a suggested solution though, it will need to be thoroughly tested to ensure this is a viable solution.

**Comment by matthew7838** [comment]
Grooming session: The current behavior is feed storage makes a deep copy of Rufas Time class, but we only need the current date to indicate the last time the feed was degraded, instead of making a copy of Rufas time class we can just extract the required information as built-in time class.
