### ISSUE TITLE
[Animal] Clean up `Cow` code that is related to lactation

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1925]
With the introduction of PR #1461, a lot of lactation related code has moved from the `Cow` class to the `LactationCurve` class. As a results, some things need to be updated in the `Cow` class.

## Status

With the introduction of the `LactationCurve` class, a lot of code in the `Cow` class has become duplicative or unnecessary. It should be removed from the class.

## Intention

Clean up and simplify the code in `Cow`. This will hopefully make it easier to comprehend and refactor.

## Request

Please address the following areas of `Cow` in `cow.py`:
1. Remove the `breed_index` and `breed_parity` attributes. These are no longer used.
2. Change `calculate_daily_milk_produced` to use the implementation of Wood's equation implemented in `get_milk_yield_values_wood_curve` in `LactationCurve`.
3. Remove `determine_param_value` and use `Utility.generate_random_number` instead.

### Additional Information

It may be better to wait on this issue until after the Animal module refactor is completed. My two cents is that it may help the refactor go more smoothly if `Cow` is in a better state before the refactor starts.

**Comment by Isgotkowitz** [comment]
Blocked - until #1461 is merged this cannot be worked on.

**Comment by ew3361zh** [comment]
From Grooming session:
- Can be done as a part of MilkProduction refactor of Animal module #1930

**Comment by Isgotkowitz** [comment]
This issue should be taken care of after issue #1930

**Comment by Isgotkowitz** [comment]
Marked as completed with the merged of #2005. 2005 did not actually remove any of the problematic code, but it did leave it behind in the `routines` directory and only implemented the necessary code in `biophysical`.
