### ISSUE TITLE
[Emissions] Add unit testing to the `Emissions` module (1/2)

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1926]
There is currently no unit testing of the routines in the `Emissions` module, this should be changed.

## Status

When the routines in the `Emissions` module were written, they needed to be delivered quickly. This resulted in unit tests not being written, and have not been written since the code was added several months ago.

## Intention

Verify correct behavior of the `Emissions` module by writing unit tests for the methods in it.

## Request

Write unit tests for the `Emissions` class located in `emissions.py`.

### Additional Information

There are a lot of methods in `Emissions`, some of them quite large and complex. So unit tests could be split into different PR's to keep the sizes of those PRs more reasonable. Also, if bugs or bad code if found while testing, they should be fixed.

**Comment by ew3361zh** [comment]
From grooming session:
- If you find areas in the code that can be improved as you are writing the unit tests, please implement those changes or write issues for those proposed changes if they are significant.
