### ISSUE TITLE
[Animal][DigestiveSystem] DigestiveSystem Refactor Implementation [3/3]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1927]
Follow the Design in this Google Doc: [Digestive System](https://docs.google.com/document/d/1vY7EoFhiwWhCO9f_BNn01K0c_DohBlbZqdEEIBXgHG4/edit?usp=sharing) to implement the refactor of the DigestiveSystem submodule.

**Comment by matthew7838** [comment]
Grooming session: Update the size if there are already tests that exist.
