### ISSUE TITLE
[Animal][MilkProduction] MilkProduction Refactor Implementation [3/3]

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1930]
Follow the Design in this Google Doc: [Milk Production](https://docs.google.com/document/d/1YYP-ynNp16SF2fRSOXZhG4BOd7UuDhpx4WQN2b_qQV0/edit) to implement the refactor of the MilkProduction submodule.

**Comment by matthew7838** [comment]
Grooming session: Update the size if there are already tests that exist.
