### ISSUE TITLE
[Feed Storage] Determine how bale size should be set and implement it

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1960]
The way that bale size is determined for a hay bale is not specified in the design doc, and the code currently uses a default value as a temporary solution.

## Status

The Feed Storage design doc specifies:

Hay has the following attributes:
...
- Bale_size
  - (enum) diameter of the bale in meters
    - 1.2, 1.5, 1.8

It however does not specify how this bale size should be calculated or determined.

## Intention

Find the methodology for how the bale size is set so that it can be set properly, instead of using a default.

## Request

Read the Feed Storage design doc, communicate with the original authors as need be, and either verify or determine the methodology for how bale size should be set.

Also, if determined to be appropriate, have `bale_size` return an enum element instead of a float.

**Comment by allisterakun** [comment]
Grooming session: 
@KevinP-B seeking your guidance here. 
Is `bale_size` a user input? Or should it be calculated?
Also, is it a universal/global value? Or is it case-dependent?

**Comment by KevinP-B** [comment]
It's user-defined and currently accepts only 2 or three values, iirc

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ew3361zh** [comment]
From grooming session:
- Moving forward with assuming this is a number (float) with a min/max for validation purposes
- @KevinP-B what are your thoughts on using a number within the range of the minimum and maximum of the 3 values presented above (1.2, 1.5, 1.8) but that is not one of those specific values? What if a value was slightly outside that range (e.g. 1.0 or 2.0)?
- cc @PooyaHekmati

**Comment by KevinP-B** [comment]
Obligatory reality/rufality reference. It can be a float. We don't have the associated surface area to volume ratio calculations to go with it, but when we do, a constrained float value is the more appropriate than enum. There is the issue of square vs. round bales, which will likely be an enum user-input regardless of this. Informatically, it would be most efficient to do everything based on surface area to volume ratio, but I don't see a way to get that as a reasonable input. Is that helpful?
