### ISSUE TITLE
[E2E Testing][Animal] Add end-to-end testing coverage for the Animal module

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1992]
## Status

The end-to-end testing routine for RuFaS currently does not cover the Animal module

## Intention

End-to-end testing should cover the Animal module in order for maintainers to more easily verify that correct behavior is maintained in when reviewing changes.

## Request

Add the following files to the directory `input/data/end_to_end_testing`:
- `e2e_json_animal_filter.json`. This file should contain a filter for gathering actual results from the animal module, as well as contain the expected animal-related results. Use `e2e_json_feed_storage_filter.json` as an example for how to write this file.
- `e2e_comparison_animal_differences.json`. This file should contain a filter that will gather the results of end-to-end testing the Animal module. Use `e2e_comparison_feed_storage_differences.json` as an example for how to write this file.
- `end_to_end_testing_result_paths.json`. This file already exists, but an entry should be added that specifies the Animal domain, the path to expected outputs, and the pattern used to find the actual outputs from the Animal module. Use the existing entry for Feed Storage as an example for how to write this.

**Comment by ew3361zh** [comment]
From grooming session:
- @Isgotkowitz to write up wiki page on how to do e2e testing
- Would be beneficial for animal module refresh to ensure results from refresh match with pre-refresh.
- @ew3361zh to review wiki page and implement this
