### ISSUE TITLE
[CropSoil] Log errors to the OM before raising ValueErrors in `HeatUnits`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#2072]
Instead raising ValueErrors as soon as an exception is found in `HeatUnits` module, log an error to the OM first.

## Status

In the `_check_absorb_heat_for_input_errors`, ValueErrors are raised if invalid values are found without logging any issues to the OM first.

## Intention

Have issues logged to the OM as well as possible before halting simulations.

## Request

Change the code log errors to the OM before raising ValueErrors in `_check_absorb_heat_for_input_errors` in `HeatUnits`. Also, investigate the code and check if this validation is necessary. If it is not, remove this method from the code entirely.

**Comment by matthew7838** [comment]
All the conditions checked right now have a default set, so this check is unnecessary. The related PR should remove the method.
