### ISSUE TITLE
[Output Manger] Make use of the log routing method across codebase

### ISSUE THREAD

**Issue by matthew7838** [RuminantFarmSystems/RuFaS#2082]
There's a function in the route log that allows saved errors/warnings/logs to be correctly routed and reported by the OM. Right now that method is not public and a few classes have the copy of the exact same method.

## Expected Behavior

OM should have a public routing method that allows usage across the codebase.

## Current Behavior

Routing is an OM private method.

## Possible Solution

1. Make it a `_route_log` static method.
2. Utilize it on the report generator and IM.
3. Implement the suggestions in PR #2061 by Ed.

## Steps to Reproduce

1.
4.
5.
6.

**Comment by Isgotkowitz** [comment]
@matthew7838 is this issue closed?

**Comment by matthew7838** [comment]
> @matthew7838 is this issue closed?

yes
