### ISSUE TITLE
Ability to suppress messages (global verbose=False)

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#211]
RuFaS should have an option to not print any basic status messages during a run (e.g., "running simulation", "creating graphics", etc). 

This feature would greatly help when running RuFaS in batch mode. 

There currently exists a `PRINT_STATUS_MESSAGES` global variable (`config/global_variables`) but it needs to be implemented. Perhaps there could also be levels of verbosity: 0 for no messages, 1 for only warnings or important abnormal behavior, 2 for all messages.

**Comment by morrowcj** [comment]
Similarly, we should be able to specify where output files are saved (`OUT_DIR`)

**Comment by ew3361zh** [comment]
Addressed with PR #828
