### ISSUE TITLE
Assessing quality of feed at harvest

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#237]
In `SC_Redesign/Crop_and_Soil/crop/yields.py` in the the `SC_Redesign` branch, there is a function called `calc_quality_assessment` which attempts to "assess quality of feed at harvest". 
Should this be determined in the Yields module, or should it be written in the Feed module and referenced from there?
The pseudocode that this function points to ("Feed Inventory Pseudocode" F.1.1) does not actually contain any information about what this function is trying to do

Also, found this gem in the function:
`crop_type.feed_id = crop_type.feed_id`

**Comment by morrowcj** [comment]
#346 included a TODO mentioning that this will be handled in separate module.
