### ISSUE TITLE
Double check cow and heiferIII calc_all_p_comp assignments

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#240]
Wanted to confirm a couple lines of code from a closed PR [Animal Management Refactor #1](https://github.com/RuminantFarmSystems/MASM/pull/138/files).

## Expected Behavior
in RUFAS/routines/animal/animal_management.py, the function "calc_all_p_comp" calculates each animal class's P concentration. There is a 1 to 1 self.p_comp['animal_class'] = self._calc_p_comp(self.animal_class) relationship for Calf, HeifierI, and HeiferII.

## Current Behavior
When the method reaches the HeiferIII class, it skips HeiferIII and sets the self.p_comp for the Cow class and sets that by using the self._cal_p_comp method on the HeiferIII class. This doesn't follow the pattern up to this point so I wanted to make sure it is correct before entering these calculations into the OutputManager.
self.p_comp['calf'] = self._calc_p_comp(self.calves)
self.p_comp['heiferI'] = self._calc_p_comp(self.heiferIs)
self.p_comp['heiferII'] = self._calc_p_comp(self.heiferIIs)
**self.p_comp['cow'] = self._calc_p_comp(self.heiferIIIs)**

## Possible Solution
Prior to the refactor, this pattern was followed:
self.calf_p_comp = self.p_comp(self.calves)
self.heiferI_p_comp = self.p_comp(self.heiferIs)
self.heiferII_p_comp = self.p_comp(self.heiferIIs)
self.heiferIII_p_comp = self.p_comp(self.heiferIIIs)
self.cow_p_comp = self.p_comp(self.cows)

If this is correct, it is an easy fix to return to this.

## Steps to Reproduce
image of change from Animal Management Refactor #1 below:
![Screenshot 2022-12-13 at 2 23 27 PM](https://user-images.githubusercontent.com/70217952/207711970-2514400d-ab13-4903-9ef3-f2f83431e2de.png)

**Comment by JoeWaddell** [comment]
Fixed in  Phosphorus Concentration Naming Convention rework #251 , see comment: https://github.com/RuminantFarmSystems/MASM/pull/251#pullrequestreview-1229130061

@JoeWaddell also reviewed the changes. Only remaining instances of p_comp in the code is a TODO in animal_management.py (Which is undergoing refactor)
