### ISSUE TITLE
OutputManager Unexepected Key Collision Error on Windows OS

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#244]
Several PC Windows users are reporting duplicate keys when trying to add data to the OutputManager. There are specific safeguards in place to specifically prevent this from happening so it is unexpected and causes the simulation to crash.

## Expected Behavior
When running the simulation and entering a piece of data into one of the OutputManager (OM) pools, the <_get_time_based_suffix()> method in that class is supposed to get a current time stamp down to the nano-second and append it as a suffix to the key for the value of each piece of data entered. This should allow the OM to generate unique keys and not run into key collision errors where the same key is entered for a different value thereby overwriting the previous data in the pool.

## Current Behavior
When adding variables to the OutputManager, user running the simulation on a Windows OS encountered a Key Collision Error where the OutputManager <_get_time_based_suffix()> method is generating the same time suffix for multiple calls to that same method at sequential moments in the simulation. This has not been able to be replicated on a Mac by 2 separate Mac users.

## Possible Solution
One potential solution is eliminating the unique time stamp suffix and adding values from the same caller class and caller function to a list.

## Steps to Reproduce
Adding print(om._get_time_based_suffix()) above the om.add_variable() call on line 468 of life_cycle.py (in the daily_update() method adding the variable "daily_milk_production") results in two equivalent time stamps printing right before the crash.

## Context (Environment)
This unexpected key collision is crashing the program for Windows users and doesn't allow the user to run a full simulation. The variables added are important to the output needed by the SMEs for reporting so figuring out a way to add these data is important.

**Comment by PooyaHekmati** [comment]
mitigated in https://github.com/RuminantFarmSystems/MASM/pull/242/commits/f67e8b214dd0a466027f9465735b4f67b06b99d8#diff-1a008a88322cbc3305694d46ae513b26b3c9c2afdd9882abc2fde3dfe12aa37a
