### ISSUE TITLE
Refactor/Implement transpiration

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#303]
Implement transpiration and water uptake into the crop `water_dynamics.py` file. This will need to work in concert with Soil, so it may wait until the Soil class is further along.

**Comment by Isgotkowitz** [comment]
I think we should try and knock this out with #307

**Comment by morrowcj** [comment]
OK, I'm alright with that. Just make not of it in #307, if you have not done so yet. 

You'll also need to re-request reviews for the new file you add to that PR.

You can close this PR whenever you'd like, given that info.

**Comment by morrowcj** [comment]
This also should have closed with merge of #307. Something is not right here. I'm closing manually.
