### ISSUE TITLE
Combine all water operations into a single Field-level module

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#326]
# Problem
Currently there are many different submodules within `Soil` and `Crop` (`Evapotranspiration` in `Soil`, `WaterDynamics` in `Crop`) that handle water operations for the `Field`. This is problematic because the processes in these submodules are interdependent, and having them in separate modules makes them difficult to coordinate and maintain. 

# Solution
Create a single, unified submodule within `Field` that coordinates and executes all water operation.

# Steps
- [x] Create a simplified way to irrigate a field. It will have the following input characteristics
    - `irrigation_amount` - an amount to irrigate the field with when irrigation happens.
    - `irrigation_interval` - the number of days to wait to irrigate again.
    - `rainfall_irrigation_threshold` - an amount of rainfall that will reset the days since irrigation counter.
  There will also be the following attributes to support irrigation
   - `days_since_irrigation` - counter for the number of days since irrigation occurred. When this counter reaches `irrigation_interval` or the rainfall on a day is >= `rainfall_irrigation_threshold`, this counter is reset. Also when the `irrigation_interval` is reached, the field will be irrigated.
   - `annual_irrigation_water_use_total` - total amount of water used for field irrigation in a year. Will be reset on a yearly basis.
- [ ] Finalize the daily update operations for `Crop` and `Soil` objects.
- [ ] Put irrigation methods, daily `Crop` update calls, and daily `Soil` water update calls into single `Field` level method (`cycle_water()`) 

Related Issues: #316, #450

**Comment by Isgotkowitz** [comment]
@morrowcj could you please take a quick look at this and let me know if you think it needs to be changed?

**Comment by morrowcj** [comment]
* Maybe `days_since_watered` and `watering_interval` are more accurate than `days_since_irrigation`, and `irrigation_interval`. 
* Otherwise, I think the game plan looks good.

**Comment by Isgotkowitz** [comment]
## Sequence of water operations

1. Precipitation enters the system.
  1.1. Some amount of rain is trapped in the crop canopy (section 2:2.1)
  1.2. The rest of the rain reaches the surface, where it immediately enters the soil profile (via `Infiltration` and `Percolation` methods).
  1.3. Snowfall is accumulated and stored at the `Field` level.
2. Evapotranspiration happens.
  2.1. Potential evapotranspiration (a.k.a. evapotranspirative demand) for the current day is calculated with Hargreaves method (section 2:2.2.3).
  2.2. Remove water from crop canopy until there is none left **or** evapotranspirative demand is met (section 2:2.3.1).
  2.3. Remove water from snow on field surface until there is none left **or** evapotranspirative demand is met (section 2:2.3.3.1).
  2.4. Remove water from soil profile until there is none left **or** evapotranspirative demand is met (section 2:2.3.3.2).

## Open questions
1. Where should crop water uptake be placed?
   - Complicating factor: potential transpiration from crop is calculated in section 2:2.3.2, but this is not the actual amount of transpiration - that is calculated in section 5:2.2.2, and is dependent upon potential transpiration and actual water uptake. The actual transpiration is equal to actual water uptake.
   - Is transpiration from crops totally independent of evapotranspirative demand? This will greatly influence how evaporative demand is met and where transpiration is calculated.
2. Snow
   -  Should the time be taken to implement the full snow sections (1:2.4, 5)? If sublimation (snow being removed as part of evapotranspirative demand) occurs, it seems important to also make sure snow gets melted and infiltrates the soil that way.

**Comment by Isgotkowitz** [comment]
Another open question/issue: SWAT uses the maximum canopy storage (see eqn. 2:2.1.1, CANMX in .hru) to determine how much water a crop canopy can store on a given day, but this value is supposed to be provided by the user for crops, and SWAT provides no values for it in the database with crop parameters.

**Comment by morrowcj** [comment]
@Isgotkowitz, I think the above procedure looks very good. I appreciate how well-thought out and clearly described everything is. 

Regarding your open questions:

1. Water uptake (using SWAT references and symbols):   

    * First we calculate the daily *transpiration rate* ($E_t$, S 2:2.3.2). This is a plant attribute. Note that this is not exactly the same as an actual amount of water that gets transpired (though SWAT's wording is confusing)
    * Then, $E_t$ is used to calculate layer-specific water uptake on ($w_{up,z}$, eq. 5:2.2.1)
    * which in-turn us used to calculate total water uptake ($w_{actualup}$, eq. 5:2.2.8)
    * which is equivalent to the true amount of water that is lost via transpiration ($E_{t,act}$, eq. 5:2.2.8)
    * Does this make sense?

2. No, transpiration does depend on evapotranspirative demand ($E_o$) (see eq. 2:2.3.5 noting that $E_o'=E_o-E_{can}$) 

3. No, I don't think snow is necessary for v1. Unless you think it is simple and could be knocked out in a few hours - then go for it.

**Comment by morrowcj** [comment]
> Another open question/issue: SWAT uses the maximum canopy storage (see eqn. 2:2.1.1, CANMX in .hru) to determine how much water a crop canopy can store on a given day, but this value is supposed to be provided by the user for crops, and SWAT provides no values for it in the database with crop parameters.

That does appear to be the case... How incredibly unfortunate. I have no idea how one would even determine that sort of thing. This is a question we need to ask of Xuesong and Eric, I think. Give it an arbitrary default and we'll go from there.

**Comment by Isgotkowitz** [comment]
@morrowcj Thank you for your answer.

>    * First we calculate the daily *transpiration rate* ($E_t$, S 2:2.3.2). This is a plant attribute. Note that this is not exactly the same as an actual amount of water that gets transpired (though SWAT's wording is confusing)
>    * Then, $E_t$ is used to calculate layer-specific water uptake on ($w_{up,z}$, eq. 5:2.2.1)
>    * which in-turn us used to calculate total water uptake ($w_{actualup}$, eq. 5:2.2.8)
>    * which is equivalent to the true amount of water that is lost via transpiration ($E_{t,act}$, eq. 5:2.2.8)
>    * Does this make sense?

Yes, it does make sense. But I am still not sure what the final sequence of operations should be.
After reading your explanation though I think it would be (sans snow)

1. Precipitation enters the system.
  1.1. Some amount of rain is trapped in the crop canopy (section 2:2.1)
  1.2. The rest of the rain reaches the surface, where it immediately enters the soil profile (via Infiltration and Percolation methods).
2. Evapotranspiration happens.
  2.1. Potential evapotranspiration (a.k.a. evapotranspirative demand) for the current day is calculated with Hargreaves method (section 2:2.2.3).
  2.2. Remove water from crop canopy until there is none left or evapotranspirative demand is met (section 2:2.3.1).
  2.3. Crops uptake water from the soil profile (section 5:2.2.2). All of the actual transpiration that occurs at this step is used to meet the evapotranspirative demand. If there is still unmet evapotranspirative demand, 2.4 is executed.
  2.4. Remove water from soil profile until there is none left or evapotranspirative demand is met (section 2:2.3.3.2).

**Comment by morrowcj** [comment]
It is unclear to me from SWAT whether 2.3 or 2.4 should occur first. But, it does seem clear that 2.3 (Section 5:2.2.2) is a part of the crop "Growth Cycle", so I think it is OK to group that method with crop growth and execute crop growth after 1) and 2) above.

In short, it would mean that 2.4 and 2.3 would be swapped in the order they occur in. Everything else seems like the way to go.
