### ISSUE TITLE
Update Feed Library

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#332]
The feed library needs to be updated to reflect the new composition values in the NASEM 2021 feed library

**Comment by Ed731551** [comment]
All right. 
I am checking if it is possible to retrieve the complete NASEM feed library from the website: https://nap.nationalacademies.org/catalog/25806/nutrient-requirements-of-dairy-cattle-eighth-revised-edition

**Comment by Ed731551** [comment]
I was able to retrieve the NASEM 2021 Feed Library from their official website. Data was collated in an Excel spreadsheet in Basecamp. See: https://3.basecamp.com/3486446/buckets/5296287/uploads/5808737694 
Thanks, Edward

**Comment by KFosterReed** [comment]
This is awesome! Thank you for finding this Edward and so fast!! Let's keep this as 'in progress' though until the library is actually being used in RuFaS. We will need to add some 'meta-data' so that we have all the variable definitions and documentation needed to use/interpret the library values as well :)

**Comment by Ed731551** [comment]
Thanks Kristan. Yes, you are right. ‘In progress’ is a better category for this. I still have to get more use to coding language :). 
I will further discuss with you and colleagues about ‘metadata’.

**Comment by KFosterReed** [comment]
Before the Annual Meeting I worked with Edward to create a combined feed library that can be used to inform both the NASEM and NRC nutrition models in  [This google sheet](https://docs.google.com/spreadsheets/d/1vOzuEawcU8oFWB2DVWOUNjFuLUDKOuF1/edit?usp=sharing&ouid=106545401981506568145&rtpof=true&sd=true)

In [PR #578](https://github.com/RuminantFarmSystems/MASM/pull/578), Pooya is working towards removing the database as the entry point for the feed library so that people can just provide a CSV. Once that is done, I would like to replace the existing CSV with the updated one so that each nutrition model is referencing the 

In order to do this, we will need to do two things: 
1. Deprecate the calls to the feed quality table as all feeds in the revised library have a unique feed ID
2. Add a function that will access the correct nutrient composition table depending on the ration model used (NRC or NASEM). 

I will add this to the Animal Module's Project board since we don't really have a feed team :)

**Comment by KFosterReed** [comment]
@PooyaHekmati this is the feed library issue we talked about today. You can see above I thought it made sense to wait until your PR #578 was complete but after reviewing this, let us know if you think that is not a good order to work in. Thanks!

**Comment by PooyaHekmati** [comment]
As discussed in our meeting with @JoeWaddell and @allisterakun on 9/20/2023, Allister is working on this. This will replace PR 578 (578 was written before the inception of Input Manager, now that we have the Input Manager we can use that instead). NASEM and NRC are already added to IM's metadata. Allister is adding an entry in the config which allows choosing between these two. Then, in the feed module, he is going to use that config field and the corresponding feed standard. This effort is also part of DB deprecation which is listed under MS 3.

**Comment by tomhuhh** [comment]
Confirmed with @allisterakun ! Closing this issue...
