### ISSUE TITLE
Develop methods to represent methane mitigation supplements

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#344]

**Comment by Ed731551** [comment]
February 14. The next two feed additives to be tackled are: monensin and Agolin (essential oils blend). Equations from the recent paper by Kebreab et al. (2023) in J. Dairy Sci. 106:927–93, have been already considered for assessing the mitigation potential of 3-NOP on predicted CH4 emissions from a number diets (n= 144) formulated for lactating cows.
