### ISSUE TITLE
RUFAS tracks irrigation in the weather class???

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#347]
# Problem

Currently, RUFAS tracks irrigation in the weather class. This doesn't really make sense and should probably be a component of the Soil and Crop module (after v1). Similarly, the irrigation attribute is only used to compute "rainfall" by adding the irrigation values to actual rainfall. This needs to be handled better.

# Suggested solution

At the very least, the amount of water provided via irrigation should be provided as input to the model (Soil and Crop Module). More complex handling of irrigation might need its own subject matter expert in order to be sophisticated and maximally useful.

**Comment by Isgotkowitz** [comment]
Closing this issue as stale. The issue of redesigning and reimplementing irrigation in RuFaS is captured in #1372, and removing irrigation from Weather is mentioned in the Weather implementation issue #836.
