### ISSUE TITLE
refactor and test soil_water.py (soil) into SC_redesign directory

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#352]

**Comment by Isgotkowitz** [comment]
`soil_water.py` mainly functions to update all water-related attributes in a `Soil` object. Refactoring this code would not make sense because we are planning to have all water operations in the `Crop_and_Soil` module be conducted in a dedicated, coordinated manner inside the `Field` module (Issue #326). 
@morrowcj what do you think?

**Comment by morrowcj** [comment]
I need some clarification: Does the `soil_water.py` module not do anything? Is it just a wrapper class that calls the other water modules (i.e., `Erosion`, etc.)? If it is just a wrapper for the other modules, then I agree. But if it has its own functionality, it needs to get refactored.  Whether or not the new code ends up in `soil_water.py` or a component class of `Field` can be up to what you think is best. If it updates `SoilData` objects, it should probably remain a soil module. Even if its main methods are only ever called by the `Field` class.

**Comment by Isgotkowitz** [comment]
The only logic it actually implements is the percolation between soil layers, which is already implemented in the refactor of `Percolation`. Everything else that it does is just updating fields inside the `Soil` object, which is already done by all the main routines inside their respective files.

**Comment by morrowcj** [comment]
Perfect. If all the functionality is included elsewhere, then there's no need to keep this file. You can close this issue (maybe as "not planned"?) when ready.
