### ISSUE TITLE
Combine fields with common management practice

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#359]
## Problem summary
Currently, RuFaS assumes that each agricultural field should be simulated independently. In many cases, this may be an overly complex way to model a farm. The source model SWAT, for example, groups all land that experiences the same land cover and management practices into a single HRU (Hydrological response unit). This allows simulations to be greatly simplified.

## Suggested solution 
I recommend that RuFaS should have similar functionality. Functionally, I don't believe that any new code would be needed. 
For example, rather than specifying 3 `Field` classes that each contain the same crop and management practices (and reasonably similar soil properties), users could specify a single mega "HRU `Field`" whose area is the sum of the 3 individual fields. Then all operations would occur as usual. 

This could drastically simplify user input and computational complexity. 

----
See section 1.1.2 of SWAT's [input/output file documentation](https://swat.tamu.edu/media/19754/swat-io-2009.pdf)

**Comment by Isgotkowitz** [comment]
This is already the case in RuFaS, but it is the responsibility of the users to write their inputs in a way that reduces redundancy.
