### ISSUE TITLE
Update Soil and Crop Input

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#361]
## Problem Summary
The redesign of the soil and crop module has/will have led to a substantially different set of expected input variables from the user. That means that the input system (i.e., the input json files, code to convert them into objects, and the resulting data/config objects themselves) will need to be re-written. 

This should be one of the final steps in the soil redesign process.

## Details: 
Each of the inputs required by the crop and soil module should be contained within model configuration classes. The attributes of these classes would specify the starting conditions of the model and the way the simulations progress. 
For each field (or management unit) simulated, we'll need the following information at the least:
* Field specification:
    - Field size: how large is the field (or management unit) in terms of area?
    - Topography: how much of a slope exists (on average)?
    - Location: approximately where is the field (or management unit) located on the globe? This will allow us to acquire 
    weather (predictions?) and soil type/composition data.
    - subdivisions: an optional number of fields or other subdivisions that a single management unit is divided into.
* Crop management:
    - planting schedules: which crop species are planted on which years? are there repeated rotation patterns?
    - harvest schedules: should crops be cut on a schedule or should harvest dates be based on optimal growth conditions? 
    If a schedule is used, harvest dates are needed for each unique component of the rotation (i.e., one per year)
    - harvest index override: an optional fraction that manually specifies what proportion of plant is targeted for harvest, if 
    provided this value is used in place of the internally calculated harvest index.
    - harvest efficiency: an optional fraction that manually specifies how efficient the harvest operation actually is at removing 
    the targeted amount.
* Soil management:
    - Soil type: the general type of soil to be used (from a list of supported options) this specification will pull a 
    pre-made soil configuration (with relevant composition attributes) from our database to use in the field. 
    - Soil composition: as an alternative to soil type, advanced options should allow user-defined soil configuration. 
    - Tillage: what type of tillage method will be used on the field? How much mixing will occur? On what date(s) should 
    tillage occur?
    - Amendment: what type of amendments (manure, fertilizer) will be added to the soil? by what method will they be 
    applied? How much? What is the nutrient composition?

**Comment by morrowcj** [comment]
#466 was the first step towards addressing this issue.

**Comment by Isgotkowitz** [comment]
This issue is being closed as the inputs have all been refined to allow them to be used in full RuFaS simulation runs (with the exception of `LT.json`, but I decided 6 out of 7 were good enough for now). Work on the inputs is not finished however; as the implementation of the `InputManager` wraps up, it will be necessary to write input files to be compatible with it.
