### ISSUE TITLE
X-axis for ration_report graphics reporting incorrect values

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#363]
Ration report graphics inside `pen_report` are using x-axis labels for years outside the simulation time. 

![image](https://user-images.githubusercontent.com/109082924/220436447-db758b8d-8557-4f22-8e9e-6c7a0d90e888.png)

Note that the last x-axis tick is well outside the end date. It seems that the intent was to add a tick at each ration interval.

## Expected Behavior
Ration report graphics should use the values found in the ration_report.csv for each pen. 

## Possible Solution
Changes to `ration_graphics` inside `graphics.py` to correctly assign x-axis values, with a tick for each ration interval date.

**Comment by KFosterReed** [comment]
So weird!

**Comment by JoeWaddell** [comment]
output handler was deprecated, new graphics functionality is being implemented
