### ISSUE TITLE
Move validation/error raising from `layer_thickness` to `post_init` in `LayerData`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#370]
# Problem
The validity of the boundaries of a soil layer are checked in the `@property` method `layer_thickness` in `LayerData`. This is a bad way of checking for errors because it complicates an `@property` method and does not do it immediately after the `LayerData` object is initialized.
# Solution
Move the checking into the `post_init` method of `LayerData`.

**Comment by morrowcj** [comment]
Note that the `OutputManager` (in its final form) will need to be considered. I believe the intent was to have the output manager handle all errors, but perhaps that's different from input validation.
