### ISSUE TITLE
`field/` module is full of files with misformatted docstrings

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#371]
# Problem
Most (if not all) files that have been created do not adhere to the style guides as linked in the README (https://realpython.com/documenting-python-code/ and https://numpydoc.readthedocs.io/en/latest/format.html). This is a pretty significant problem that could really bog the process of merging `SC_redesign` into `master` when the soil and crop redesign has been completed.
# Solution
This issue should be addressed with a series of PR's that reformat the comments of groups of files at a time. The size of these sets and the best way to group them should be discussed. I think reformatting 1 - 2 files at a time would make this process drag on for too long, and reviewing entire sub-modules at a time (`soil`, `crop`, `field`, `tests_SC`) would result in PRs that are too large and broad.
# Strategy
- Start executing these PRs as soon as possible, in tandem with starting new refactors of old code. The reason for this is that someone who has just corrected the comments in an older file will know exactly what the comments and docstrings should look like and will be much less likely to make the same mistakes while working on a new file.
- Regularly have people from outside the Soil and Crop team participate in the review process, so that we know the reformatted files are meeting the style standards of the entire RuFaS team.

**Comment by morrowcj** [comment]
@Isgotkowitz, I don't agree that this is a priority at the moment. We are trying to finish the redesign of this module soon and our docstring format fully complies with the instructions we were given when we started this redesign. 

We were originally told to follow the [google style guide](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html), which allows for exactly the kind of dosctrings we are using *consistently* throughout the module. We recently switched to using [numpy style](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard). When I asked, I was told this was the same as google style - I now know that not to be correct. 

Changes to the numpy format can occur **after** the redesign is complete.

**Comment by PooyaHekmati** [comment]
>When I asked, I was told this was the same as google style - I now know that not to be correct.

Sphinx engine is capable of handling both styles, so they are the same from that perspective. If by being "the same" you mean they are equal char for char; then it means the same thing has two different names which in turn means Google and NumPy are both claiming to own it. I don't think that makes much sense.

Anyways, we know that this is not a technical issue, it's just for the sake of consistency and readability. So it doesn't sound like a priority. I don't think much effort is needed to convert the style. ChatGPT can do this. Also this tool can do it: https://github.com/dadadel/pyment/blob/master/doc/sphinx/source/pyment.rst

**Comment by Isgotkowitz** [comment]
@matthew7838 what is the status of this issue?
