### ISSUE TITLE
Animal number change dramatically at the beginning of the simulation

### ISSUE THREAD

**Issue by YijingGong** [RuminantFarmSystems/RuFaS#378]
This issue was found when refactoring the animal life cycle. It currently exists in both the mater branch and refactored branch.  

## Expected Behavior

It is expected to have animals of diverse ages initialized at the beginning of the simulation, specifically calves of different ages, heifers of different ages, and cows of different ages (and thus be in different parity). 

## Current Behavior

- A dramatic decrease in heiferI number and a corresponding increase in heiferII number was seen (see below). 
![animal_population](https://user-images.githubusercontent.com/51036031/223875377-1f5e6da3-5e64-4c47-b9c6-ddd55b2395ff.png)

- In addition, it seems no cows in parity 2 were initialized. After ~1yr of growing, some cows in parity 1 moved to parity 2, etc (see below). The same pattern was seen in avg_age_for_calving_1, avg_age_for_calving_2, and avg_age_for_calving_3.
![avg_age_for_parity_1](https://user-images.githubusercontent.com/51036031/223876728-c1c05519-20eb-4ef3-b7f6-2156dd381140.png)
![avg_age_for_parity_2](https://user-images.githubusercontent.com/51036031/223876746-0b7643e9-fa1d-4d70-b233-7c8dedf77fd0.png)
![avg_age_for_parity_3](https://user-images.githubusercontent.com/51036031/223876754-b74bc502-7e04-43a5-ae42-ddc365b6cca9.png)

## Possible Solution

Check the herd initialization functions. 

## Steps to Reproduce

1. run the current version of mater (as of March 8, 2023)
2. check the output graphs under life_cycle_report

## Context (Environment)

This currently does not affect the main function of our model, because the animal numbers will settle down after ~2 yrs. But it would be good to find out the reason causing this unexpected behavior.

**Comment by YijingGong** [comment]
Loi made some great figures to help see this issue clearer: 
![cow_calving_avg_age_scatter_plot](https://user-images.githubusercontent.com/51036031/224115735-c018b18c-8644-4302-bcd5-d8fc5a7924d5.png)
![cow_parity_scatter_plot](https://user-images.githubusercontent.com/51036031/224115767-1c0a4463-781a-4d25-8f9b-1d9abeabdf7a.png)

We can see clearly that the simulation does not initialize the herd with a reasonable structure: it starts with a lot of parity 4+ cows, some parity 3 cows, zero parity 2 cows, and a very small number of parity 1 cows. As a result, it takes the program more time (>1000 d) to stabilize.

**Comment by tomhuhh** [comment]
Hi @YijingGong! Could you please verify if this issue has been fixed? Thanks!
