### ISSUE TITLE
Add subsurface option when applying Phosphorus via manure or fertilizer

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#411]
Currently, the `phosphorus_cycling/` module only allows for users to apply manure or fertilizer to the field surface. This does not reflect the full spectrum of how farmers may apply manure or fertilizer to their fields though, they may apply them below the soil surface with the knife, sweep or disk techniques. SurPhos supports application with these practices and they should be implemented eventually.

Because of the amount of work still required to finish the Soil and Crop redesign for v1, this feature should be left for v2.

**Comment by morrowcj** [comment]
I believe this is already implemented for manure somewhere (I may be wrong though). Let's follow up on this.
