### ISSUE TITLE
Unmatched Feed IDs between Input and Output

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#419]
While running the example scenario in the master, the list of feeds in the output ration report file is different from what is in the input animal_management.json/purchased_feed.json file.

## Expected Behavior

Specially, the expected feed IDs for each animal group is 
    "calf_feeds": [155, 157],
    "growing_feeds": [52, 81, 136],
    "close_up_feeds": [2, 26, 57,  118, 136, 139],
    "lac_cow_feeds": [26, 34, 81, 103, 118, 136, 139],
according to the purchased_feed.json file. 

## Current Behavior

The actual list of feed IDs for each animal group is as follows. 
     "calf_feeds": [155, 157] 
     "growing_feeds": [136, 83, 54]
     "close_up_feeds": [2, 136, 139, 118, 26, 59] 
     "lac_cow_feeds": [36, 103, 136, 139, 83, 118, 26] 

## Possible Solution

Not sure what the solution is yet, but here is the current debugging progress.
![Screenshot 2023-04-03 at 4 57 35 PM](https://user-images.githubusercontent.com/52800053/229625953-9be4d143-3de8-48c5-b8d8-959872922568.png)
I am suspecting that something went wrong during the database query process. 

## Steps to Reproduce

1. Run the master code with the "animal_management.json" file. 

## Context (Environment)

We encountered this issue while looking at the ration report output with @JoeWaddell.

**Comment by tomhuhh** [comment]
@KFosterReed Have you ever run into this issue? Your feedback is appreciated! Thanks!

**Comment by KFosterReed** [comment]
This is actually an intentional feature for feeds that have different types of quality. Forages are the most common example so there may be a high, medium or low quality of a corn silage but when you start growing it, you only know that you are growing corn silage. You can find a more detailed explanation in the documentation of the feed library: [https://docs.google.com/document/d/1f3nWrn5fMy8NSIuZlrgZY5SXwmKcIF3t93O70qdSBVc/edit?usp=sharing]

**Comment by KFosterReed** [comment]
[https://docs.google.com/document/d/1f3nWrn5fMy8NSIuZlrgZY5SXwmKcIF3t93O70qdSBVc/edit?usp=sharing](url)

**Comment by tomhuhh** [comment]
> This is actually an intentional feature for feeds that have different types of quality. Forages are the most common example so there may be a high, medium or low quality of a corn silage but when you start growing it, you only know that you are growing corn silage. You can find a more detailed explanation in the documentation of the feed library: [https://docs.google.com/document/d/1f3nWrn5fMy8NSIuZlrgZY5SXwmKcIF3t93O70qdSBVc/edit?usp=sharing]

This makes sense. I am closing the issue.
