### ISSUE TITLE
Unit not found for soil biomass in pseudocode_soil S.6.B.II.2

### ISSUE THREAD

**Issue by matthew7838** [RuminantFarmSystems/RuFaS#432]
### Summary
In pseudocode_soil S.6.B.II.2 and `residue_partition.py`, the referenced soil(below ground) biomass calculation was not found in the pseudocode_crop section C.3.A.5, nor is any mention of biomass unit. In fact, C.3.A.5 does not exist.

### Solution
Check directly with the subject expert and maybe fill out the missing section

**Comment by morrowcj** [comment]
My guess, if it matches the other modules, would be kg. But it is good to triple-check.
