### ISSUE TITLE
Implement `ManurePool` class to make operations in `soil/phosphorus_cycling/` better

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#433]
# Problem
The behavior of manure, as defined in SurPhos, is dependent on two attributes: method of application (applied by machine or grazing animals) and type (source of manure can be cows, or non-cows). In order to fully implement SurPhos, we need to track these different manure types separately (issue #420).

Also, at the time of this writing the interface for applying manure in a field is located in `Crop_and_Soil/soil/phosphorus_cycling/manure_application.py` which does not reflect how this module will actually be used (at the `Soil` or `Field` levels of the Crop and Soil module).

# Current solution
Two separate manure pools are tracked, one for machine-applied cow manure, and one for directly applied cow manure. Each pool is composed of an identical set of attributes (save that they are prefixed with either `machine_` or `grazing_`), and are entirely contained in the `SoilData` module. This has resulted in a lot of duplicate code building up throughout the `phosphorus_cycling` submodule.

# Possible Solutions
1. Implement a base `ManurePool` class that defines all the common attributes and behavior of the manure pools, and then implement 4 different pool classes that inherit from `ManurePool` with the correct constants and behaviors for that pool's type. 
  - Also, move the `ManureApplication` module up from the `phosphorus_cycling` submodule, likely into the `field` or `manager` sub-modules

# Other Concerns
- Manure is also a major source of nitrogen, so any solution to this issue should consider compatibility with `nitrogen_cycling/`. `nitrogen_cycling/` has not been refactored yet as part of the Soil and Crop module redesign; how easily/simply it can be integrated with `phosphorus_cycling` is currently a big x-factor.
- It is possible that this feature will become fairly complex/involved and require a design doc & design review process before implementing. In this case a better course of action may be to make this a "Future issue" and complete V1 without it.

**Comment by Isgotkowitz** [comment]
After working through the nitrogen cycling module and examining the old code, it is clear that the nitrogen (and potassium) are handled in a much simpler fashion than phosphorus. Only phosphorus has pools on the soil surface, nitrogen and potassium, when added via manure (and fertilizer) are assumed to go straight into the top 10 mm of soil (in SWAT; in RuFaS it would be the top 20 mm of soil, but after numerous meetings with SMEs I think that is an ok way to model nutrients)

**Comment by Isgotkowitz** [comment]
Update: @ltp23 raised a good point about `_apply_solid_machine_manure()` and `_apply_liquid_machine_manure()` methods containing a lot of duplicate functionality in #540. To mitigate this, I believe that behavior should be implemented in the `ManurePool`s that adds manure to fields, and that would be a prime opportunity to refactor how manure gets added.

**Comment by Isgotkowitz** [comment]
Look at where this falls in the requirements for the Crop and Soil module.

**Comment by ew3361zh** [comment]
In soil_data.py:
- Machine and Grazing attributes under Manure (phosphorous cycling) should be encapsulated within a new ManurePool class.

In Manure.py in phosphorus cycling:
- In daily_manure_update() - there is duplicated code that does the same processes on grazing and machine manure pools - these should be combined.
- Keep in phosphorus cycling? Look at effects of both.

ManureApplication has since been moved from phosphorus cycling to field level so this part no longer needs to be addressed..

**Comment by Isgotkowitz** [comment]
Nitrogen should not be included in the `ManurePool` class at this point in time. Modeling of manure N is still fundamentally different from manure P, and IMO it would be wrong to try and handle them in the same manner if they do not take a fundamentally similar approach.
