### ISSUE TITLE
Equation not found for BGbiomass

### ISSUE THREAD

**Issue by matthew7838** [RuminantFarmSystems/RuFaS#436]
### Summary
In line 141 of the original` residue_partitioning.py` code, `layer.ADJ_crop_type_bio_BG = ADJ_crop_type_bio_BG_fun(layer.thickness, soil.profile_depth, crop_type.bio_BG)` is something that does not exist in pseudocode_soil S.6.B.II.7. My it's usage in later code it can be determined as BGbio mass in. 
However, the calculation of BGbiomass was not found as mentioned in issue #432. 

### Solution
By following the pseudocode_soil reference, it can be assumed that it's calculated in the pseudocode_crop, yet that reference does not exist in the pseudocode_crop. Therefore the calculation will be neglected for now.

**Comment by morrowcj** [comment]
@matthew7838, I believe this variable is tracked BGbiomass is "below ground biomass" which is the same as "root biomass", which can be found in `crop_data.py` the variable is `CropData.root_biomass`.
