### ISSUE TITLE
Track organic Phosphorus within the `phosphorus_cycling` submodule

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#444]
# Problem
Currently, the `phosphorus_cycling` submodule tracks only inorganic phosphorus in the soil through the use of two pools (in each layer): `labile_phosphorus_content` and `active_phosphorus_content` (in `LayerData`). This corresponds more closely to how SurPhos models phosphorus (see below diagram). This was a conscious design choice that simplified SurPhos and made it more focused only on the processes that it was trying to model. However, this leaks information that is important for maintaining an accurate state of phosphorus in the soil profile.

![SurPhos_diagram](https://user-images.githubusercontent.com/43901812/232101540-a7660575-3cd0-41b7-a2db-47a3f05d407d.png)

# Solution
Add between 2 - 4 additional phosphorus pools in the `LayerData` module, so that for each layer of soil in the profile, we can maintain a more detailed state that is similar to the one SWAT maintains (see below diagram). The mapping for phosphorus pools on the surface to phosphorus pools in the soil should be:
- water-extractable inorganic phosphorus -> labile inorganic phosphorus
- water-extractable organic phosphorus -> labile organic phosphorus 
- stable organic phosphorus -> active organic phosphorus
- stable inorganic phosphorus -> stable organic phosphorus
- phosphorus from plant residue -> fresh phosphorus

- [ ] Double check these mappings w/ Pete and SWAT
- [ ] Implement the mineralization equations from SWAT sections 3:2.2.1, 2

![SWAT_phosphorus_diagram](https://user-images.githubusercontent.com/43901812/232103627-900977e9-64d7-464b-b4fb-446970477179.png)

**Comment by Isgotkowitz** [comment]
For RuFaS V1, organic phosphorus can be ignored.

I am pretty sure that the only change that needs to be made currently to make sure organic phosphorus is abstracted correctly is to directly add phosphorus from the crop residue into the labile inorganic phosphorus pool.

**Comment by Isgotkowitz** [comment]
If Ed works on this, is a large, for anyone else this would be an XL. Anyone who works on this should coordinate with Pete to make sure they understand how organic phosphorus should be incorporated into Crop and Soil and how changes should be evaluated.

**Comment by matthew7838** [comment]
An issue with some updates and details is now in issue #1871 .
