### ISSUE TITLE
Milking Parameters are Not Assigned Correctly

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#463]
## Expected Behavior

The parameters that define an animals lactation curve (l, m, and n) are randomly selected from a distribution. These parameters should be assigned to the animal once at the beginning of the lactation to establish their pre-determined expected milk production that varies between cows. Then, each day, a new random value should be added (or subtracted from their expected milk production) to represent daily variability 
## Current Behavior

Currently the random parameters are re-selected each day and there is no additional daily variation added to the milk production
## Possible Solution

Update the parameters only on the first day of lactation

## Steps to Reproduce

1. Review the milking_update() function in cow.py
2.
3.
4.

## Context (Environment)

The current implementation of the Monte Carlo methods for the lactation curve does not reflect our understanding of biology or how the lactation curve parameters were estimated. Each cow has a set of lactation curve parameters that defines her expected lactation. If those change every day, then each cow has too much randomness in their individual lactation curve. This was a big discussion point in Manfei's PhD dissertation and defense and it was my understanding that it was updated but we must have either lost the update or it has not been merged in yet.

**Comment by YijingGong** [comment]
I think what you said makes perfect sense to me. My attention was never drawn to this issue previously and I also did not discover it by myself when reviewing the code. I also had no idea whether we had an update related to this. But I am glad that you bring this issue up. I think we should fix it.

A fix might be in life_cycle.py, every time a cow has a newborn, set the parameters (i.e. cow.l, cow.m, cow.n). 

I can draft a design doc for this. This should be a relatively easy fix. I think Loi would be a perfect person to code it since he refactored the life cycle. But I am not sure if he has the bandwidth at this moment. Let me know what you think.

**Comment by KFosterReed** [comment]
Ok, great! Thanks Yijing. 

Setting the parameters at calving might be a good option - but how would that work for multiple parities? Also, I wonder if Niko might have more bandwidth to help with this and if you and he can work together to get it accomplished?

**Comment by YijingGong** [comment]
Works for me! Could you please let Niko know about that? Or maybe we can talk as a team in next week's Animal meeting. I will write a design doc for this task (you already covered most of it in the issue, I will just copy and paste and add some details). 

For different parities, I think it should work the same as in cow.py. We can fetch the cow's parity in life_cycle.py, and assign the parameters based on the parity number. Of course, the details need further discussion, the above solution is based on my quick look at the code.

**Comment by YijingGong** [comment]
A design doc is drafted accordingly. Here is the link: https://docs.google.com/document/d/1w_ncSsFPXQjdaxOxwobVPl5BCy2qKwBU4LPprMnAGMI/edit#

Two questions that I want to confirm (also mentioned in the design doc open question), but I think you are the one who knows the best @KFosterReed 
1. Do we want to also include the Milkbot model in our MVP, or focus on Wood’s model first?
2. What would be the daily variance of milk production? I assume it will be a normal distribution with a mean of 0 and a relatively small variance. But I am not sure about the exact number for the variance. Is there any literature related? Or we can just assume maybe the variance of the normal distribution to be 1% of the estimated milk production value, or something similar.

**Comment by ew3361zh** [comment]
Addressed by PR #534
