### ISSUE TITLE
Track residue content in `LayerData`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#481]
## Problem
Currently, there is no attribute in `LayerData` to track the residue content of a soil layer.

But equations in SWAT (namely in section 3:1.2.5) expect to know how much residue there is in a soil layer, and use this value to estimate the amount of carbon in the soil layer. Also in the named section, it calculates a decay rate of the residue in the soil layer and reduces the residue content based on that amount. 

## Temporary Solution
Currently, `MineralizationDecomp` (in the `NitrogenCycling` module, implements section 3:1.2.5) uses the `LayerData` attribute `total_soil_carbon_amount`. There are two potential problems with this:
1. There may be some carbon in the soil that is not from residue, and we don't want that to be included.
2. It is fair game for `MineralizationDecomp` to reduce residue in the soil, but having it reduce carbon would be bad practice (because carbon additions and reductions should be limited to the `CarbonCycling` module)

## Solution
Implement and maintain a residue tracker in `LayerData`

**Comment by Isgotkowitz** [comment]
`LayerData` maintains two pools that track residue: `structural_litter_amount` and `metabolic_litter_amount`. A residue tracker could (and probably should) be as simple as an `@property` that sums these two pools.

Note that there are a lot of extra/unused attributes related to litter/residue in LayerData. If reasonably easy to accomplish, these attributes should be removed.

**Comment by Isgotkowitz** [comment]
If someone besides Ed does this, it should be Medium T-shirt size

**Comment by Isgotkowitz** [comment]
The way that crop residue is being transferred from the Crop module to the Carbon Cycling module is being changed in #1854. However this change does not effect how the metabolic and structural litter pools are actually managed in the carbon cycling module, so I think the suggested solution above should still be valid.

**Comment by PooyaHekmati** [comment]
@KFosterReed we think some help from an SME is needed for this issue, can you please let us know who is the right person for it?>

**Comment by KFosterReed** [comment]
> @KFosterReed we think some help from an SME is needed for this issue, can you please let us know who is the right person for it?>

I think @adhikaripradip75 would be the best person to weigh in on this with support from @rawalashmita and Xuesong Zhang. I can also support as Pradip is still learning all things RuFaS :) I am meeitng with Pradip later today and will discuss with him then

**Comment by matthew7838** [comment]
> > @KFosterReed we think some help from an SME is needed for this issue, can you please let us know who is the right person for it?>
> 
> I think @adhikaripradip75 would be the best person to weigh in on this with support from @rawalashmita and Xuesong Zhang. I can also support as Pradip is still learning all things RuFaS :) I am meeitng with Pradip later today and will discuss with him then

@KFosterReed Thanks for the help, during work together we were able to clarify some naming confusions. What we need now is just any suitable SMEs to check on the implementation and the solution when the PR is ready.

**Comment by matthew7838** [comment]
Update: Ashmita will help with the review.

**Comment by KFosterReed** [comment]
> Update: Ashmita will help with the review.

Thanks for volunteering to jump in on this @rawalashmita! @adhikaripradip75 and I had a conversation about this yesterday. When the PR is ready, please tag Pradip, Ashmita, and myself :)
