### ISSUE TITLE
Revisit Carbon Cycling submodule of Soil and Crop

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#512]
# Problem
The v1 version of Crop and Soil uses a carbon cycling sub-module that is based upon the old code (prior to SC_redesign). The module is documented in the old soil pseudocode, but the primary sources are unclear. I believe that it is a novel model developed by Hector M. based upon DAYCENT. It is unclear to me if the current carbon module is the best approach for RuFaS. Along with the other subject-matter experts (Xuesong, Pete Vadas), I believe that a revision is warranted. 

# Solution
The Soil and Crop team believes that the carbon functionality of SWAT-C (developed by Xuesong) should replace the current carbon submodule. The implementation should conform to the standards set by the other SC modules.

**Comment by Isgotkowitz** [comment]
Update 11/13/2023:

The Carbon Cycling module being delivered for RuFaS v1 is based on DAYCENT. It has been mostly integrated into the model by PR #830, and will be fully integrated with the completion of issues #944 and #945. This issue should be closed after the completion of 944 and 945, and a new one should be written for replacing the current Carbon and Nitrogen cycling modules with SWAT-C.
