### ISSUE TITLE
Question about OM behavior

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#518]
## Problem / Questions
It appears that, even though the caller "class" and "function" are required components of the info maps, they are only recorded in the key names of the pool. This is fine, and makes sense. Except that when a "prefix" element is specified in the info map, it entirely replaces the [class].[function] portion of the key name, meaning that the information about the caller is lost entirely. *And*, even though the prefix is preserved in key name, it is also repeated in the info maps. Here's a reproducible example:

```python
from RUFAS.output_manager import OutputManager

spam_values = [5, 10, 15]
egg_values = [2, 4, 6]

om = OutputManager()
om.flush_pools()  # for repeated use / testing

info_map = {"class": "foo", "function": "bar"}
[om.add_variable("spam", val, info_map) for val in spam_values]
# add prefix and custom info map field:
info_map["prefix"] = "holy_hand_grenade"
[om.add_variable("eggs", val, info_map) for val in egg_values]

print(om.variables_pool)
# {'foo.bar.spam': {'info_maps': [{}, {}, {}], 'values': [5, 10, 15]}, 'holy_hand_grenade.eggs': {'info_maps': [{'prefix': 'holy_hand_grenade'}, {'prefix': 'holy_hand_grenade'}, {'prefix': 'holy_hand_grenade'}], 'values': [2, 4, 6]}}
```
@ew3361zh, are these behaviors intentional?

---
Note, this is the issue I was referring to in #516

**Comment by ew3361zh** [comment]
This is working as intended. Spoke with @Isgotkowitz about this since the C&S team has used the OM prefix feature most extensively and Ed said it was meeting their needs and no adjustments to the process were needed.
