### ISSUE TITLE
Rename save functions to dump functions

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#521]
### What
Rename all functions with names matching the pattern save_xyz to dump_xyz. Find references to these functions and fix them.

### How
It depends on the IDE. In VScode, you can right-click on the RUFAS folder in Explorer and click on find in folder. Alternatively, you can temporarily rename the functions back to save_xyz and right click on their names, and click on find all references. 

### Why
What these functions really do is dump and not save. We need to free up the save so we can use it more appropriately. In computer science, "dumping" typically refers to the process of generating a comprehensive report or output that contains detailed information about the state of a system or a specific component. It is commonly used for debugging purposes or when troubleshooting issues. The generated dump file may include data such as memory contents, register values, stack traces, or log information, which can be analyzed to diagnose and fix problems.

**Comment by ew3361zh** [comment]
Addressed by PR #537
