### ISSUE TITLE
Implement save_variables function

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#522]
Implement save_variables function. This function shares code with dump_variables function. So, create a function with _ prefix and make both save and dump variables call this function. dump_variables only call this function; however, save_variables first filters the pool and then passes the filtered pool to this function. For filtering, first, take a look at https://learnpython.com/blog/filter-dictionary-in-python/ . You will need a function to pass to filter(). Let's start simple: we want save_variables to do this:
1. reads a txt file (the path to this txt is given as an arg to the function). The txt file contains the keys that we want to save. Each line in the txt file contains the exact key (no pattern matching, just use == operator) (one key per line). 
2. Uses filter () to filter the keys to figure out which entries in variables_pool need to be saved.
3. Calls the newly developed private function to handle exclude_info_map and the saves the results.

**Comment by ew3361zh** [comment]
A couple questions:
1. Do we want the _exclude_info_maps() function to be dependent on the setting of the exclude_info_maps flag? So if the user has set exclude_info_maps to False, should this function effectively do nothing?
2. Into what format should the new save_variables function save the results from step 3 above?

**Comment by PooyaHekmati** [comment]
I'd say the caller should make decision to either call _exclude_info_maps or not based on that flag.
The rest if the same as the existing code, so no change in formatting.

**Comment by ew3361zh** [comment]
Handled in PR #541
