### ISSUE TITLE
Running simulation without info_maps crashes program

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#530]
The simulation crashes when trying to collect and save the variable names in the Output Manager after the simulation runs when the user opts not to collect info_maps data in the variable names list.

## Expected Behavior
if the user sets the `exclude_info_maps` to True, the variable names should still be able to be collected in the `save_variable_names_and_contexts` method without the program crashing.

## Current Behavior
When running a simulation with the `exclude_info_maps` option set =True, the simulation crashes when trying to collect and save the variable names in the Output Manager `save_variable_names_and_contexts` method.

## Possible Solution
It looks like there's a key-error in line 396 of the OM module. With info_maps excluded, the method should not be looking for info_maps data to add at this point. However, just putting logic to only execute this section of code if info_maps are excluded seems to lead to a lot of variable names not being added. Likely need to rework the logic to add the values keys only given the status of exclude_info_maps is what I'm initially thinking of.

## Steps to Reproduce
Run the following script to exclude info_maps:
`python -c "from main import run_rufas; run_rufas(input_path='input/animal_management.json', exclude_info_maps=True)"`

Should result in an error message like this:
<img width="1226" alt="Screenshot 2023-05-23 at 3 23 11 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/83310a9e-7b4a-4f0b-b0d9-54c68740a43c">

## Context (Environment)
This came out of running the simulation testing a separate unrelated feature in another part of the model.

**Comment by ew3361zh** [comment]
@PooyaHekmati fyi, trying to debug briefly but couldn't solve it quickly so made an issue to return to.

**Comment by PooyaHekmati** [comment]
> @PooyaHekmati fyi, trying to debug briefly but couldn't solve it quickly so made an issue to return to.

Thanks Niko, please let me know if another pair of eyes is needed.

**Comment by PooyaHekmati** [comment]
Fixed in [this pull request](https://github.com/RuminantFarmSystems/MASM/pull/532).
