### ISSUE TITLE
[Crop Soil] Re-evaluate `Schedule` and subclasses for redundancy and cleanliness

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#561]
### Currently
As of 7 June, 2023, the `manager/` directory in the crop and soil module contains a base `Schedule` class, and descendants `CropSchedule`, `TillageSchedule`, `ManureSchedule`, and `FertilizerSchedule`. Many of these child classes contain nearly duplicate logic, which could possibly be eliminated through careful analysis and design.

Also, each child class is responsible for validating input and raising errors when invalid input is passed. This responsibility will be taken on by the `InputManager` when it is completed, and should be eliminated from these child classes at that point.

Note: although it would be ideal to just work at this inheritance structure now, before anything has been merged into `SC_redesign` or `master`, I (Ed) have deemed it better to get it to an acceptable state, and leave this issue as a reminder to revisit after the completion of the v1 Crop and Soil module.

**Comment by Isgotkowitz** [comment]
All of these classes have similar methods for validating input, those methods all check for multiple different error conditions and raise errors as soon as they find them. As pointed out by @matthew7838 in #558, it would be better to collect all errors from input and raise them together.

**Comment by Isgotkowitz** [comment]
Tests for all `Schedule` subclasses include tests that check for error raising on invalid input, but should also have tests that check valid input correctly creates `Schedule` instances. Pointed out by Joe in #560

**Comment by Isgotkowitz** [comment]
The methods for event generation currently zip together lists of different attributes, then access the tuples generated through direct indexing. A simpler approach would be to access elements directly in each list through indexing. Pointed out by Loi in #560

**Comment by Isgotkowitz** [comment]
This issue should not be started until pilot testing on the Crop and Soil module has finished and SMEs have given the go-ahead to start working on the Crop and Soil module.

**Comment by ew3361zh** [comment]
Covered in issue #1820.
