### ISSUE TITLE
Move output filters to output dir

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#580]
## Expected Behavior
Output filter files should be in the output directory.

## Current Behavior
These files are in the input directory.

## Possible Solution
Move the files and make the needed adjustments in the code.

## Steps to Reproduce
N/A

## Context (Environment)
There are 2 reasons for this:

1. The input directory is responsible to contain the inputs that are needed to run the simulation and the required data for the EEE module. The output description is not an input to the model.
2. Down the road, when users want to share their results, it would be beneficial to share the filters as well. If they are in the same dir, all the user needs to do is share just the output folder and which contains everything.

**Comment by PooyaHekmati** [comment]
This is a p1.

**Comment by ew3361zh** [comment]
Addressed with PR #586
