### ISSUE TITLE
Implement a reasonable default diet 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#619]
## Expected Behavior
The crude protein (CP) composition is within reasonable range for a lactating diet cow. 

## Current Behavior
Low CP% (~10%) in the current diet. Also, a low DM% at 37% is observed. 

## Possible Solution
Add some limits to the feed ingredients to mimic a diet that Edward formulated. 

## Steps to Reproduce

1. Formulate a diet using the default setting and calculate the nutrient composition. 
2.
3.
4.

## Context (Environment)

When testing MONENSIN at a dose of 24 mg/kg DMI, we expected decrease in enteric methane emissions. However, methane emission increased due to low CP% (~10%).

**Comment by Ed731551** [comment]
Equation for estimating reduction of CH4 yield emissions should work within the range of 15 to 19% CP. In case of diets outside this, I would suggest using the basal equation with only monensin addition as a predictor (recommended doses).

Equation as follows (Abstract - Modelers conference, 2023): 
% Reduction in CH4 yield emissions = 0.03223 - 0.00410 × Monensin

NOTE = Monensin equations (% of reduction) were developed from data of lactating cows only. Caution should be exercised when aiming to implement these to other animal groups. 

Nevertheless, a diet with 10% CP for a production level of 44 kg of milk per day (as far as I remember) does not make any sense to me. Worth checking details on how that diet was formulated.

**Comment by tomhuhh** [comment]
Closing it as the issue is resolved by PR#1112.
