### ISSUE TITLE
Save keys as column headers and 'values' fields as column values (OM CSV #1)

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#641]
In this step, we want to process each key-value pair in the aggregate json file generated by the output manager. For each pair, we should save the key as a column header and the 'values' field of its value dictionary as the column values in a separate CSV file. 

The 'values' field can be a list of simple types (int, float, str, bool) or a list of more complex types. For the latter, let's use `str()` method to handle them for now.

We can keep the keys as-is without any string processing. We'll save each key to a separate CSV file. Each of these CSV files will be stored in the `output/CSVs/om/variables/` directory. 

This CSV output handling process should occur at the end of the simulation to make sure all data is captured.

For example:

```json
{
    "simple_key": {
        "values": ["Hi", "How", "Are", "You"]
    },
    "list_key": {
        "values": [
            [1, 2, 3],
            [4, 5, 6]
        ]
    }
}
```

The CSV output for the simple_key.csv would be:

```json
simple_key
"Hi"
"How"
"Are"
"You"
```

And the CSV output for the `list_key.csv` would be:

```json
list_key
"[1, 2, 3]"
"[4, 5, 6]"
```

Checklist:

- [x] For each key-value pair in the aggregate json, create a new CSV file using the key as the file name.
- [x] Save the key as a column header in its respective CSV file.
- [x] For each key-value pair, save the 'values' field of its value dictionary as the column values.
- [x] If the 'values' field consists of simple types (int, float, str, bool), save them as they are.
- [x] If the 'values' field consists of more complex types, convert them into string using `str()` method.
- [x] Save each CSV output file into the `output/CSVs/om/variables/` directory.
- [x] Check the correctness of the output, i.e., each CSV file is correctly formatted (e.g., headers and values align correctly), and the files contain the correct data.
- [x] Write unit tests:
     - [x] Check if the JSON to CSV conversion is performed correctly.
     - [x] Check that complex data types are correctly stringified.
     - [x] Check that the CSV file is saved at the correct location.

**Comment by michaelRichards99** [comment]
Merged.
