### ISSUE TITLE
Raise errors for data in IM pool that is not found in metadata

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#648]
## Problem
Similar to issue #647, this issue considers the case where there is data found in the IM's `__pool` (loaded from input_data files), that does not have a counterpart for a check in the metadata. A possible scenario is when a user/dev adds a new variable into the code, they update the appropriate input file but don't update the metadata properties.

## Proposed solution:
Add a specific error nothings this to the OM at the point where this pool element is sent for validation in `_validate_element()` and additionally in the `_fix_data()` method but otherwise continue as normal through the `_validate_data()` method. This would get treated as critical data by the `_fix_data()` function and would therefore act in accordance with the user's setting on eager_termination.

**Comment by Isgotkowitz** [comment]
Niko will create issue for checking that nothing is being added to pool which is not specified in the metadata.
