### ISSUE TITLE
Integrate a static type checker into the Github workflow

### ISSUE THREAD

**Issue by michaelRichards99** [RuminantFarmSystems/RuFaS#651]
**Is your feature request related to a problem? Please describe.**
Type annotations are used extensively throughout our code base, as described by [PEP 484](https://peps.python.org/pep-0484/). According to the PEP 484 proposal, type annotations exist at runtime but there _is no type checking at runtime_. Instead, the proposal relies on external tools to provide type analysis to the Python source code. 

We have type annotations but are currently not checking them with a static type analysis tool.

Using a static type analyzer will be beneficial because it makes identifying certain classes of bugs much easier to track down.

**Describe the solution you'd like**
We should:
- [x] Investigate which static analyzer works best for RuFaS
- [ ] Add a Github workflow that runs the type analyzer as part of the CI pipeline

**Describe alternatives you've considered**
We can continue without a type analyzer, which is part of the benefit of using a dynamic language such as Python.

**Additional context**
The type analysis tool [mypy](https://mypy-lang.org/) indicates 222 existing type errors in the code base. Fixing these could be nontrivial.

**Comment by michaelRichards99** [comment]
# Investigation of static type checkers for python:
## Pros and Cons
1. Mypy
	- Pros:
		- Most popular and most featureful.
		- Recommended by [RealPython](https://realpython.com/python-type-checking/), we use many of their resources.
		- Integrates well with both VScode and Pycharm
	- Cons:
		- see below
2. Pytype
	- Pros:
		- easy to integrate into existing code base because of how lenient it is 
	- Cons:
		- Not as customizable as the others
		- Doesn't integrate with Pycharm
3. Pyright
	- Pros:
		- Good overall option. similar in features to mypy.
	- Cons:
		- poor Pycharm integration
4. Pyre
	- Pros:
		- Comes with Pyre and Pysa. Pyre is the type checker and Pysa is a static analysis tool that can identify security vulnerabilities
	- Cons:
		- Poor Pycharm integration

### Drawbacks that all tools share
- Must migrate code base to be correctly typed.
	- depending on how strict the type checker tool is configured, the current MASM code base contains between 200-950 type errors.
- Takes developer time and effort

**Comment by PooyaHekmati** [comment]
So, what is the conclusion? Which option is the winner?

**Comment by michaelRichards99** [comment]
Mypy is the best option in my opinion. It has the best support across different IDEs, which will be beneficial for members on our team. It also comes with extensive documentation and plenty of external resources and support from the community.

**Comment by Isgotkowitz** [comment]
- [ ] Reinvestigate different type checker options

**Comment by Isgotkowitz** [comment]
An issue needs to be created for fixing legacy type errors in the codebase

**Comment by ltp23** [comment]
Resolved in PR #1278
