### ISSUE TITLE
Rename the default branch from master to main

### ISSUE THREAD

**Issue by michaelRichards99** [RuminantFarmSystems/RuFaS#659]
**Is your feature request related to a problem? Please describe.**
The default branch name `master` was changed to `main` on both Github and Git a few years ago in order to promote inclusivity and address the concerns with the historical association with the term `master`.

**Describe the solution you'd like**
We should adopt `main` as our default branch name.

**Describe alternatives you've considered**
There should be no alternative here.

**Comment by PooyaHekmati** [comment]
Why is this change needed urgently?

**Comment by michaelRichards99** [comment]
This promotes diversity, equity, and inclusion and I think it should be migrated sooner rather than later.

**Comment by PooyaHekmati** [comment]
I understand the benefits and the necessity of this change but I don't think this is urgent. Given the inherent risk that this action has, it is probably better to postpone it to after v1.
