### ISSUE TITLE
Identify discrepancies between Crop and Soil Meta data and DCA inputs

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#682]
Last week Ed submitted a PR with the Crop and Soil meta data (PR#665). He mentioned that there are some discrepancies in the input names and the description/units between the meta data and the DCA inputs. 

I am creating this issue to highlight the need to resolve those issues. The meta data should be taken as the correct values and updates made to the DCA. If questions arise, please make note of them and hold them for when Ed is from vacation this Wednesday (7/26).

**Comment by Isgotkowitz** [comment]
Closed by #1022
