### ISSUE TITLE
Expand array input data validation capabilities in IM

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#683]
When an array is detected in the data loaded from an input file, the first thing to do is to run the validation on itself (min len, max len, etc). 

Once the array is validated, loop through its elements and run validation for them as well. 

We probably need to call validate_element for them. 

This was requested by SMEs

**Comment by ltp23** [comment]
- [X] Validate object type
- [X] Validate array type
- [X] Validate the default metadata json files
- [x] Keep track of the counters

**Comment by Isgotkowitz** [comment]
This has been attempted once but was not completed. Needs to be groomed again.

**Comment by Isgotkowitz** [comment]
Closed by #1345
