### ISSUE TITLE
Create user option for running simulation without data validation

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#738]
There should be an option for the user to skip data validation and run the simulation.

**Describe the solution you'd like**
A separate issue #737 was created for the option for the user to validate data without running the simulation after which could be paired with the solution to this issue. Via Pooya, "there is conversation going on about adding new features to IM/adding a new module upstream to it. If we decide to do that, both of these validation things can be done there."

**Describe alternatives you've considered**
My first though is another flag to indicate whether the user wants to validate the data after loading it which could, in the `_populate_pool()` function, tell IM to skip over the validation process and just add each blob-source's data to the pool.

**Comment by PooyaHekmati** [comment]
>>There should be an option for the user to skip data validation and run the simulation.

I don't think so.
