### ISSUE TITLE
Pen change Frequency

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#74]
Cows change pens very frequently. Is this what we want? What is causing them to change so frequently?

**Comment by JoeWaddell** [comment]
Related to ongoing changes in animal_management.py by @Fjordrunner and @ancheypeng 
This issue and related issues #96, #188, and #189 will likely be resolved with forthcoming refactor.

See branches: https://github.com/RuminantFarmSystems/MASM/tree/animal_management_comments 
and associated
https://github.com/RuminantFarmSystems/MASM/tree/animal_management_refactor_fa22

Functions associated with this issue include: daily_update_id_pen, and also allocate_all_pens inside function daily_updates (which happens at the end of the ration interval).
