### ISSUE TITLE
Weather Data Reformat

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#753]
Currently, all the weather data are stored in separate 2D arrays of the following format:
```variable_name: [year_num][day]```
Where variable_name is the variable of interest (e.g., T_max => maximum temperature of the day), year_num is the difference between the year of interest and the starting year (e.g., for a simulation starting in 2019, the year 2020 would be index 1), and finally the Julian date.

I believe that the current weather data structure introduces unnecessary complexity, and it should be flattened or completely reformatted at one point.

**Comment by Isgotkowitz** [comment]
I propose the following steps for addressing this issue:
- [x] Create method(s) that get all the information about the weather on the current day. #860 
  - Possibly with a `CurrentWeather` object?
- [x] Eliminate all instances of weather access via array indexing in the codebase. #864 
- [ ] Implement better internal structure for weather data.
  - This one is a biggie, most likely will require some designing before implementing.

At the current moment I think these tasks will require between 2-3 PRs to complete.

**Comment by Isgotkowitz** [comment]
The priority of changing how `Weather` maintains data internally is low, so the final task should wait until sometime after the delivery of v1 in 2024.

**Comment by ltp23** [comment]
This issue is blocked by #1383.

**Comment by ew3361zh** [comment]
Handled in #1507.
