### ISSUE TITLE
Output filters are not correctly used when extra blank lines are present

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#761]
When an output filter is written, the corresponding output file only has the correct outputs when there are either no blank lines in the filter file, or 1 blank line is at the end of the filter file.

## Expected Behavior

The OutputManager should write *exactly* the variables listed in the filter file to the corresponding output file, regardless of any blank lines included in the file.

## Current Behavior

If there are any blank lines included in a filter file, besides one at the end, it writes all variables collected to the output file. 

## Possible Solution

When a filter file is opened to be read, immediately strip all blank lines from it.

## Steps to Reproduce

1. Write filter for desired variables with no blank lines in the file.
2. Run RuFaS and verify that only the desired variables were written to corresponding output file.
3. Add a blank line in the middle of the filter file, or two at the very end.
4. Run RuFaS again and check the corresponding output file.

**Comment by ew3361zh** [comment]
Closed with PR #930
