### ISSUE TITLE
Consistency in saving JSON and CSV files in OM

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#778]
In `output_manager.py` from lines 558-565:
```
            if filter_file.startswith("json_"):
                file_path = os.path.join(save_path, self._generate_file_name(f"saved_variables_{filter_file}", "json"))
                self._dict_to_file_json(filtered_pool, file_path)
            elif filter_file.startswith("csv_"):
                csv_directory = os.path.join(save_path, "CSVs", "om")
                self._save_variables_to_csv_files(filtered_pool, filter_file, csv_directory)
            else:
                self.add_warning("invalid filter file", f"{filter_file} must be prefixed with csv_ or json_", info_map)
```

Why is `self._generate_file_name()` called for the JSON output files to generate a file name (line 559), but not for the CSV output files?

**Comment by allisterakun** [comment]
After some investigation, I figured that for saving CSV files, the `self._generate_file_name()` is called in the `self._save_variables_to_csv_files()` method (line 586), rather than in the parent `save_variables()` function as the JSON files.
So, should we move them into the same place for consistency?

**Comment by allisterakun** [comment]
As @PooyaHekmati suggested, we can move the file name generation (calling `self._generate_file_name()`) outside the if structure to avoid redundant calls.

Also, we can use a dictionary instead of if-elif to route the logic to the right function.

**Comment by allisterakun** [comment]
Right now, the save path is hard coded. We would like to add an option for users to add a custom save path.

**Comment by PooyaHekmati** [comment]
The logic has been moved to `_route_save_functions` in PR #926
The problem still exists.

**Comment by allisterakun** [comment]
This issue has already been taken care of.
Current behavior:
```python
        if filter_file.starts with(self.__supported_filter_types_prefixes["json"]):
            file_path = os.path.join(
                save_path,
                self._generate_file_name(f"saved_variables_{filter_file}", "json"),
            )
            self._dict_to_file_json(filtered_pool, file_path)
        elif filter_file.startswith(self.__supported_filter_types_prefixes["csv"]):
            self.create_directory(csv_dir)
            variable_csv_file_path = os.path.join(
                csv_dir, self._generate_file_name(f"saved_variables_{filter_file}", "csv")
            )
            self._dict_to_file_csv(filtered_pool, variable_csv_file_path)
```
1. For CSV files, `self.create_directory(csv_dir)` is first called to create the `CSV/` folder if it does not already exist. This is unnecessary for JSON files, as they are saved to the output directory, which should already exist.
2. The full output file path (`file_path` for JSON and `variable_csv_file_path` for CSV) is created by calling `os.path.join()`.
3. The full output file path is then passed to the respective save functions along with the filtered pool (`self._dict_to_file_json(filtered_pool, file_path)` and ` self._dict_to_file_csv(filtered_pool, variable_csv_file_path)`)
