### ISSUE TITLE
LifeCycleManager.daily_update.life_cycle_daily_herd_update reports daily milk as 0.0

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#780]
**Quick fix**
The following was added in a previous PR, but this should be checked to ensure that it's ideal: 
`self.daily_milk_production = sum(cow.estimated_daily_milk_produced for cow in cows)`

**Problem**
`LifeCycleManager.daily_update.life_cycle_daily_herd_update` reported `daily_milk_production` as 0.0

**Proposed solution**
In `animal_manager.py` we update the `daily_milk_production` value correctly, but in `LifeCycleManager` we call `_reset_daily_stats` and never update milk production.

Could be as easy as retaining that value specifically, but recalculating that value after all the culling/selling in `LifeCycleManager.daily_update` may be prudent.

**Comment by tomhuhh** [comment]
Hello @JoeWaddell! Can we close this issue?
