### ISSUE TITLE
TODOs in Manure Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#787]
There are 18 TODOs in the Manure module. TODOs are bad and should be avoided as much as possible. Please work on getting these TODOs done and reasonably remove them from the code.

> 18 results - 11 files
> 
> RUFAS\routines\manure\manure_manager.py:
>   263          """
>   264:         # TODO: With the introduction of different manure types, we should rename attributes in ManureTreatmentDailyOutput
>   265          # to make it more generic and not specific to any manure type.
> 
> RUFAS\routines\manure\beddings\bedding_classes.py:
>   352  
>   353:     # TODO: Use correct values for straw bedding.
>   354      # Predefined configuration for Straw Bedding
> 
> RUFAS\routines\manure\gas_emissions\gas_emissions.py:
>   198  
>   199:     # TODO: to be removed in the next PR while refactoring slurry storage treatments
>   200      @classmethod
> 
>   213              temperature_celsius: temperature in Celsius, C.
>   214:             manure_volatile_solids_fraction: Fraction (0-1) volatile solids. # TODO: review this
>   215:             efficiency_fraction: efficiency of process, unitless. # TODO: review this
>   216  
> 
>   830                                        manure_total_ammoniacal_nitrogen: float,
>   831:                                       manure_mass: float,  # TODO: Decide to use volume or mass
>   832                                        temperature_celsius: float,
> 
> RUFAS\routines\manure\input_handler\manure_manager_config_handler.py:
>   36  
>   37:     # TODO: For the following getters, pass in an enum member instead of a string
>   38  
> 
> RUFAS\routines\manure\manure_handlers\manure_handler_daily_output.py:
>   24          liquid_manure_potassium: Amount of potassium in manure, kg.
>   25:         housing_methane: Methane emissions from ..., kg.  # TODO: Fill in.
>   26:         housing_carbon_dioxide: Carbon dioxide emissions from ..., kg.  # TODO: Fill in.
>   27:         housing_ammonia: Ammonia emissions from ..., kg.  # TODO: Fill in.
>   28          manure_volume: Amount of raw manure, m^3.
> 
> RUFAS\routines\manure\manure_treatments\anaerobic_digestion.py:
>    38                  manure_treatment_daily_input.liquid_manure_total_volatile_solids *
>    39:                 0.03 / ManureConstants.MANURE_DENSITY)  # TODO: Use constants instead
>    40          return new_daily_output
> 
>   139          """
>   140:         return max(average_temperature_celsius, 4.0)  # TODO: Use constants instead
>   141  
> 
>   153          """
>   154:         # TODO: Name the constants if you can
>   155          return 0.68298 + 0.025662 * average_temperature_celsius + 0.01306 * moisture_content * 100
> 
> RUFAS\routines\manure\manure_treatments\anaerobic_lagoon.py:
>   45                  manure_treatment_daily_input.liquid_manure_total_volatile_solids *
>   46:                 0.03 / ManureConstants.MANURE_DENSITY)  # TODO: Use constants instead
>   47          return new_daily_output
> 
> RUFAS\routines\manure\manure_treatments\base_manure_treatment.py:
>   144                                 (manure_treatment_daily_input.liquid_manure_total_solids *
>   145:                                 self.config.total_solids_removal_efficiency_for_treatment) / 1000.0)  # TODO: Make 1000.0 a constant
>   146  
> 
> RUFAS\routines\manure\manure_treatments\manure_treatment_cbpb.py:
>   85          manure_nitrogen = daily_input.liquid_manure_nitrogen - total_nitrogen_loss
>   86:         # TODO: To be implemented further later.
>   87          daily_output = ManureTreatmentDailyOutput(
> 
> RUFAS\routines\manure\manure_treatments\manure_treatment_daily_output.py:
>   23  
>   24:         # TODO: Document remaining attributes.
>   25  
> 
> RUFAS\routines\manure\pen_manure\pen_manure.py:
>   88          # Zero out any negative field
>   89:         # TODO: This is a temporary fix. Need to find out why negative values are being generated
>   90          # from the animal module. Later, we should raise an exception if a negative value is found.
>

**Comment by ltp23** [comment]
Thanks Pooya for creating the issue. I will work on those. Whatever TODOs I can't resolve, I will create a git issue for each.

**Comment by PooyaHekmati** [comment]
Things might have changed since I made this issue. Please recheck and address current TODOs.

**Comment by PooyaHekmati** [comment]
@ew3361zh Assigning the issue to you since you have already made issues for the TODOs. Please mention the issue number in their corresponding TODOs in the code.
