### ISSUE TITLE
TODOs in Animal Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#788]
There are 53 TODOs in the Animal module. TODOs are bad and should be avoided as much as possible. Please work on getting these TODOs done and reasonably remove them from the code. 

> 53 results - 15 files
> 
> RUFAS\routines\animal\animal_combinations.py:
>   1: # TODO: In a separate PR, move the AnimalCombinations inside Pen class
>   2  #  here to avoid circular imports.
> 
> RUFAS\routines\animal\animal_grouping_scenarios.py:
>   19      """
>   20:     # TODO: Probably change the names of these scenarios to be more concise/descriptive. Add other scenarios as needed.
>   21  
> 
> RUFAS\routines\animal\animal_manager.py:
>    783              A list of animal to be allocated to pens.
>    784:             # TODO: Add type hint for animals later
>    785          pens : List[Pen]
> 
>    825              A list of animals to be allocated among the pens.
>    826:             # TODO: Add type hint for animals later
>    827  
> 
>   1326  
>   1327:                     # TODO: Remove this check before merging to master
>   1328                      counter += 1
> 
> RUFAS\routines\animal\pen.py:
>   229  
>   230:         # TODO: We should use a dictionary to map animal id to animal object.
>   231          self.animals_in_pen = []
>   232:         # TODO: To be removed. Use the property 'is_populated' instead.
>   233          self.populated = False
> 
>   235          self.classes_in_pen = set()
>   236:         # TODO: To be removed. Use the property 'current_stocking_density' instead.
>   237          self.stocking_density = 0.0
> 
>   298  
>   299:     # TODO: (Not used yet) Use this property instead of self.stocking_density because it is dynamically calculated
>   300      @property
> 
>   391  
>   392:     # TODO: Remove this functionality once pen has been fully switched to AnimalCombination enum
>   393      def update_classes_in_pen(self) -> None:
> 
>   454          # total manure in pen and total manure by animal type
>   455:         # TODO: Write an accumulator function
>   456          for animal in self.animals_in_pen:
> 
>   511  
>   512:     # TODO: Fix this to use AnimalType enum
>   513      def calc_daily_walking_dist(self):
> 
>   545                  total_p_animal += animal.p_animal
>   546:             # TODO: Add warning if total_p_animal < 0
>   547              total_p_animal = max(total_p_animal, 0)
> 
>   568              # Avoids a division by 0 error in below calculations
>   569:             # TODO is there a better way?
>   570              num_animals_before_additions = 1
>   571  
>   572:         # TODO: Question - is this necessary or can we assume that any newly
>   573          #   added animals will match the existing animal combination?
> 
> RUFAS\routines\animal\life_cycle\cow.py:
>    13              lactation curve model (Wood's and Milkbot) parameters.
>    14:             Health culling including 4 components: #TODO death, repro, production, and health,
>    15                  health culling for 6 reasons: Lameness, Injury, Mastitis,
> 
>   194  
>   195:     # TODO: Not used yet & check for correctness
>   196      @property
> 
>   210  
>   211:     # TODO: Not used yet & check for correctness
>   212      @property
> 
> RUFAS\routines\animal\life_cycle\heiferIII.py:
>   24  class HeiferIII(HeiferII):
>   25:     # TODO: Rank heifers to enter the herd or sold
>   26  
> 
> RUFAS\routines\animal\life_cycle\life_cycle.py:
>    45      # The following class variables are used in HerdReport.
>    46:     # TODO: Make these variables instance variables when HerdReport is refactored.
>    47      num_cow_for_parity = {
> 
>   177  
>   178:     # TODO: Annotate config after removing all the imports in all the __init__.py files
>   179      def initialize_herd(self, config, herd_data: HerdInfoTypedDict) \
> 
>   276          total_animal_num = 0
>   277:         preg_heifer_num = 0  # TODO: Seems unused after calculation
>   278  
> 
>   332          """Resets daily-based attributes."""
>   333:         # TODO: Maybe break this list down into smaller lists
>   334          self.calf_num = 0
> 
>   351  
>   352:         # TODO: Check if all the following variables need to reset daily
>   353          self.CIDR_count = 0
> 
>   594          """
>   595:         # self.CIDR_count += heiferII.CIDR_count  # TODO: add CIDR count to heiferII
>   596          self.GnRH_injection_num_h += heiferII.GnRH_injections
> 
> RUFAS\routines\animal\life_cycle\pen_history.py:
>   24  
>   25:     # TODO: Annotate pen later when circular dependency is resolved
>   26      def __init__(self, start: int, end: int, pen, classes_in_pen: list[str]):
> 
> RUFAS\routines\animal\manure\calf_manure_excretion.py:
>    98      manure_excretion_values = AnimalManureExcretions(
>    99:         urea=9.52,  # 0.340 mol/L TODO: Implement with correct equation
>   100          urine=2,
>   101:         # TODO: Implement with correct equation
>   102          total_ammoniacal_nitrogen_concentration=0.14,
> 
> RUFAS\routines\animal\manure\dry_cow_manure_excretion.py:
>    57      """
>    58:     # TODO: Add TypedDicts for ration_formulation and available feeds
>    59:     # TODO: Pass in available feeds directly instead of a Feed object
>    60:     # TODO: Rename abbreviated key names to full names
>    61      nutrient_amounts, nutrient_concentrations = ration_report(
> 
>    66      potassium_concentration = nutrient_concentrations['potassium']
>    67:     ASH_concentration = nutrient_concentrations["ash"]  # TODO: Unused
>    68      NDF_concentration = nutrient_concentrations['NDF']
>    69:     EE_concentration = nutrient_concentrations["EE"]  # TODO: Unused
>    70      ADF_concentration = nutrient_concentrations['ADF']
> 
>    75          NDF_concentration - CP_concentration - EE_concentration
>    76:     # TODO: Further calculations to account for entire diet:
>    77      # DMI: dry matter intake, kg
> 
>   129      # Nitrogen excretion in feces, kg [A.3B.B.3]
>   130:     fecal_nitrogen = manure_nitrogen - urine_nitrogen  # TODO: Unused
>   131  
> 
> RUFAS\routines\animal\manure\general_manure.py:
>   172      # compromised of organic water extractable P [A.3.A.3]
>   173:     # TODO: Is it 0.05 or 0.50?
>   174      organic_phosphorus_fraction = 0.05 * manure_phosphorus_fraction
> 
> RUFAS\routines\animal\manure\growing_heifer_manure_excretion.py:
>   50      """
>   51:     # TODO: Same TODOs as in dry_cow_manure_excretion.py
>   52      nutrient_amounts, nutrient_concentrations = ration_report(
> 
>   97      # Nitrogen excretion in feces, kg [A.3B.B.3]
>   98:     fecal_nitrogen = manure_nitrogen - urine_nitrogen  # TODO: Unused
>   99  
> 
> RUFAS\routines\animal\ration\animal_requirements.py:
>    655      # communication with Dr. Edward Garcia
>    656:     # TODO: Calculate TDN from the previous rations, when formulated. Using this constant as a placeholder value for the first formulation. See Issue #531
>    657      MP_bactria_estimate = dry_matter_intake_estimate * \
> 
>    756  
>    757:     # TODO Consider inclusion of equations for estimating requirement for Non-Essential Aminoacids (NEAA)
>    758  
> 
>    766      NDF_conc = 0.3
>    767:     # TODO get the current NDF_conc See Issue #531
>    768      # hardcoded '0.3' is a general value that works for initial simulation purposes
> 
>   1092      if animal_type in [AnimalType.LAC_COW, AnimalType.DRY_COW]:
>   1093:         # TODO: Refactor this so lactating is not needed
>   1094          if lactating:
> 
>   1102      else:
>   1103:         net_energy_maintenance_diet = 1 # TODO update this method to retrieve values from nutrient composition of 
>   1104                                          # ration from previous formulation.
> 
>   1172          """
>   1173:         # TODO: implement this by getting NDF_concentration_percentage See Issue #531
>   1174              (neutral detergent fiber) from the feeds
> 
>   1236          elif housing == 'Grazing':
>   1237:             # TODO This will be the DMI supplemented after grazing - requires grazing module implementation: See Issue #590
>   1238              nonpasturekgDMI = 1
> 
> RUFAS\routines\animal\ration\ration_driver.py:
>    20  from RUFAS.routines.animal.ration import ration_NLP as NLP
>    21: # TODO can't import Pen for typing hint because it causes circular import
>    22      # so how should we import for type hints?
> 
>    54      dRUP = NLP.list_reconfig(available_feeds['dRUP'])
>    55:     # TODO: Put AnimalCombination enum in a separate file and use it here instead of hardcoding the names
>    56      if str(animal_combination) in ['AnimalCombination.LAC_COW']:
> 
>   232              constraints_failed_list.append(constr["fun"].__name__)
>   233:         # TODO: is there a better way to get the simulation day?
>   234          fail_summary = {'simulation day' : pen.animals_in_pen[0].body_weight_history[-1].simulation_day,
> 
>   273                      constraints_failed_list.append(constr["fun"].__name__)
>   274:                 # TODO: is there a better way to get the simulation day?
>   275                  fail_summary = {'simulation day' : pen.animals_in_pen[0].body_weight_history[-1].simulation_day,
> 
>   357      
>   358:     # TODO: Put AnimalCombination enum in a separate file and use it here instead of hardcoding the names
>   359      if pen.animal_combination.name in ['LAC_COW']:
> 
>   366                      constraints_failed_list.append(constr["fun"].__name__)
>   367:             # TODO: continue testing for more efficient reductions: see Issues #569, 577, 589
>   368  
> 
> RUFAS\routines\animal\ration\ration_NLP.py:
>   670          return usermod
>   671:     # TODO: Put AnimalCombination enum in a separate file and import it here to avoid circular import
>   672      elif str(animal_combination) in ['AnimalCombination.LAC_COW']:
>

**Comment by JoeWaddell** [comment]
Thank you for collating these: many are being handled in the Ration refactor, and I'll ensure all others are handled in the Life Cycle and forthcoming Animal Manager refactors.

**Comment by PooyaHekmati** [comment]
Things might have changed since I made this issue. Please recheck and address current TODOs.

**Comment by JoeWaddell** [comment]
This issue was accidentally closed.
