### ISSUE TITLE
TODOs in Crop and Soil Module

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#789]
There are 86 TODOs in the Crop and Soil module. TODOs are bad and should be avoided as much as possible. Please work on getting these TODOs done and reasonably remove them from the code. 

> 86 results - 31 files
> 
> RUFAS\routines\field\crop\crop_data.py:
>   347      """optimal proportion of the plant's biomass comprised of nitrogen for the current growth stage (unitless)"""
>   348:     user_harvest_index: Optional[float] = None  # TODO: handle user input for this. - GitHub Issue #246
>   349      """a user-specified harvest index (unitless). If given, 'harvest-index-override' is triggered"""
> 
> RUFAS\routines\field\crop\crop_management.py:
>    63  
>    64:     # TODO: implement grazing feature - issue #590
>    65  
>    66      # ---- Sub Methods ----
>    67:     # TODO: implement management practice for dry-down and collecting cut yields that have been left in the field - #353
>    68  
> 
>   106          """
>   107:         # TODO: stand in for more sophisticated dry down method - GitHub Issue #162
>   108          #   The dry down method is not currently used
> 
>   178  
>   179:         # TODO: are above- and below-ground lignin residue (percent) needed?
>   180          #   in the old version, they were both hard-coded to 17 - GitHub Issue #163
> 
>   222          soil_data.soil_layers[0].fresh_organic_nitrogen_content += self.data.yield_nitrogen
>   223:         # TODO: Add organic phosphorus to correct pool in soil - GitHub issue #444
>   224  
> 
> RUFAS\routines\field\crop\crop.py:
>   44          """Process component controlling plant phosphorus uptake and incorporation"""
>   45:         self.heat_units = HeatUnits(self.data)  # TODO: rename module and component (e.g., "HeatAccumulation")?
>   46          """Process component controlling plant heat accumulation"""
>   47:         self.leaf_area_index = LeafAreaIndex(self.data)  # TODO: rename module and component (e.g., "CanopyGrowth")?
>   48          """Process component controlling canopy growth, including leaf area index"""
> 
> RUFAS\routines\field\crop\growth_constraints.py:
>   23          self.data.water_stress = GrowthConstraints._determine_water_stress(self.data.water_uptake, max_transpiration)
>   24:         #  TODO: plant transpiration should be an attribute of the crop (in addition to the soil?)
>   25  
> 
> RUFAS\routines\field\crop\heat_units.py:
>    86  
>    87:     # TODO: add these warnings to output manager at a later date.
>    88      def _check_absorb_heat_for_input_errors(self, mean_air_temperature: float = None,
> 
>   137  
>   138:     # TODO: Heat scheduling? SWAT 5:1.1.1 - GitHub Issue #368
> 
> RUFAS\routines\field\crop\leaf_area_index.py:
>   93          if first_heat_fraction == second_heat_fraction:
>   94:             # TODO: perhaps a way to handle this instead of throwing an error would be better
>   95              #   something like: second_heat_fraction += 1e-9
> 
>   97  
>   98:         # TODO: need to add any of these errors that get thrown when RuFaS runs to the  `OutputManager`.
>   99          #    This should probably be done in the `grow_canopy()` function
> 
> RUFAS\routines\field\crop\nitrogen_incorporation.py:
>    29          soil_water_factor = soil_data.soil_water_factor
>    30:         # TODO: soil_water_factor should be vectorized (methods need updating) instead of just using the average.
>    31          #   That will require refactoring the subroutines. - GitHub Issue #450
> 
>    53          soil_data.set_vectorized_layer_attribute("nitrate_content", layer_nitrates)
>    54:         # TODO: the above line is a temporary solution - should be changed with GitHub Issue #450
>    55          total_accessible_nitrates = sum(self.access_layers(layer_nitrates))
>    56          self.try_fixation(total_accessible_nitrates, soil_water_factor)
>    57:         # TODO: fixing nitrogen does not increase biomass. Why not?
>    58          self.data.nitrogen = self.determine_stored_nutrient(
> 
>   250              raise ValueError(frac_error_msg)
>   251:         # raise other errors  # TODO: perhaps rather than throwing errors, we should set values to sensible edge case?
>   252          if emergence_nitrogen_fraction == mature_nitrogen_fraction:  # leads to divide by zero
> 
>   492  
>   493:     # TODO: method signature
>   494      @staticmethod
> 
> RUFAS\routines\field\crop\phosphorus_incorporation.py:
>    5  
>    6: # TODO: Phosphorus has identical methods to NitrogenIncorporation, excluding nitrogen fixation. They
>    7  #  should be combined into one class (NutrientIncorporation) and simplified. Issue #450
> 
>   55          soil_data.set_vectorized_layer_attribute("labile_inorganic_phosphorus_content", layer_phosphates)
>   56:         # TODO: the above line is a temporary solution - should be changed with GitHub Issue #450
>   57          self.data.phosphorus = NitrogenIncorporation.determine_stored_nutrient(
> 
> RUFAS\routines\field\crop\water_dynamics.py:
>     4  
>     5: # TODO: This module needs to be updated to include water uptake by plants and evapotranspiration (implemented in Field?)
>     6  
> 
>    98      def _determine_evapotranspiration(evaporation: float, transpiration: float) -> float:
>    99:         # TODO: belongs in Soil class? - GitHub Issue #303
>   100          """
>   101:         Description: calculate the annual evapotranspiration #TODO: why is this 'annual' routine executed every day?
>   102  
> 
>   108  
>   109:         TODO: find where SWAT has this equation (if it does, if not make note of assumption)
>   110          """
> 
>   131  
>   132:     # TODO: Further functions water files need to be translated (into soil methods?) - GitHub Issue #303
>   133      #    RUFAS/routines/field/crop/transpiration.py
> 
> RUFAS\routines\field\crop\water_uptake.py:
>    10  
>    11: # TODO These functions belong in either water_dynamics.py or as soil process methods - GitHub Issue #450
>    12  
>    13: # TODO: these methods do not currently account for whether or not the roots can reach a layer. See Nitrogen module.
>    14  #   I'm not entirely sure if that should happen for this module, since the methods allow a crop to pull water up
> 
>   302          """
>   303:         # TODO: Note that this method is identical to NitrogenIncorporation._determine_nitrogen_uptake_to_depth()
>   304          if root_depth <= 0:
> 
> RUFAS\routines\field\field\fertilizer_application.py:
>   60          """
>   61:         # TODO: move application functionality from soil/phosphorus_cycling up to this module, and increase
>   62          #  functionality of this module - issue #492
> 
> RUFAS\routines\field\field\field_data.py:
>   22      """is today the day to plant new crops?"""
>   23:     absolute_latitude: float = 43.5  # TODO: set default to somewhere other than Wisconsin, or no default?
>   24      """The absolute latitude value (degrees above or below equator) where field is located (degrees)"""
>   25:     minimum_daylength: float = 6.33  # TODO: set default to somewhere other than Wisconsin, or no default?
>   26      """Shortest day of the year for this watershed (hours)"""
> 
>   41      """total amount of water lost to transpiration in the field on the current day (mm)"""
>   42:     max_transpiration: Optional[float] = None  # TODO: should probably not default to None
>   43      """maximum possible amount of water that could be lost to transpiration in the field for the current day (mm)"""
>   44:     max_evapotranspiration: Optional[float] = None  # TODO: should probably not default to None
>   45      """maximum possible amount of water that could be lost to evapotranspiration in the field for the current day
>   46      (mm)"""
>   47:     potential_evapotranspiration_adjusted: Optional[float] = None  # TODO, needed?
>   48      """adjusted max evapotranspiration (mm)"""
> 
> RUFAS\routines\field\field\field.py:
>    212  
>    213:         # TODO: specify these fractions in fertilizer mixes - issue #573
>    214          inorganic_nitrogen_fraction = nitrogen_applied / total_mass_applied
> 
>    886          """
>    887:         # TODO: implement snow addition, melting, and sublimation - issue #317
>    888          snow_cover = 0
> 
>    947  
>    948:         # TODO: figure out how to determine weighting coefficient when there are multiple crops in the field - issue
>    949          #  #519
> 
>    951          self.soil.percolation.percolate(self.field_data.seasonal_high_water_table)
>    952:         # TODO: find reasonable values/way to set minimum cover management factor - issue #520
>    953          self.soil.soil_erosion.erode(self.field_data.field_size, 0.02, self.field_data.current_residue,
> 
>    972  
>    973:         # TODO: Implement snow (melting and sublimation) - issue #317
>    974          snow_water_content = 0.0
> 
>    980  
>    981:         # TODO: sublimate and adjust soil_evaporation_and_sublimation_amount here - issue #317
>    982  
> 
>   1068          canopy of another.
>   1069:         TODO: distribute water evenly/proportionally/fairly between crop canopies - issue #513
>   1070          """
> 
>   1109          reaches 0, then no more water should be evaporated so the method stops running.
>   1110:         TODO: evaporate water evenly/proportionally/fairly from crop canopies - issue #513
>   1111          """
> 
>   1265  
>   1266:     # TODO: this method will not be used until sublimation is implemented - issue #317
>   1267      @staticmethod
> 
>   1275              Amount of water in the snow pack on a given day prior to accounting for sublimation (mm)
>   1276:         TODO: verify that "amount of water in the snow pack on a given day" (2:2.3.3.1) and "snow water content"
>   1277              (2:2.3.3) mean the same thing - address this with #317
> 
> RUFAS\routines\field\field\manure_application.py:
>   262          """
>   263:         # TODO: evaluate how to best apply subsurface liquid manure, it is likely more complicated than how this method
>   264          #   accomplishes it - issue #713
> 
>   284  
>   285:         # TODO: put infiltrated organic phosphorus into corresponding soil pools - issue #444
>   286          mass_to_add_to_labile_P = total_phosphorus_mass * water_extractable_inorganic_phosphorus_fraction * \
> 
>   423                                                    water_extractable_inorganic_phosphorus_fraction)
>   424:         # TODO: put subsurface organic phosphorus into corresponding soil pools - issue #444
>   425          water_extractable_organic_phosphorus = (total_phosphorus_mass * water_extractable_organic_phosphorus_fraction *
> 
> RUFAS\routines\field\field\tillage_application.py:
>   73          """
>   74:         # TODO: increase functionality and features - issue #538
>   75  
> 
> RUFAS\routines\field\manager\current_weather.py:
>   27      """average annual air temperature for the year (C)"""
>   28:     snow_fall: float = 0.0    # TODO: make this better integrated with Soil module
>   29      """amount of snow that falls on the day (mm)"""
> 
> RUFAS\routines\field\soil\evaporation.py:
>   61  
>   62:     # TODO - this method should be moved to field.py and used there when sublimation is implemented #317
>   63      @staticmethod
> 
>   72              Amount of water in the snow pack on a given day prior to accounting for sublimation (mm)
>   73:          TODO: verify that "amount of water in the snow pack on a given day" (2:2.3.3.1) and "snow water content"
>   74            (2:2.3.3) mean the same thing - issue #317
> 
> RUFAS\routines\field\soil\infiltration.py:
>   80          # --------------------------------------------------------------------------------------------------------------
>   81:         # TODO: bound runoff by the amount of rainfall that occurred before storing it - Issue #468
>   82          self.data.accumulated_runoff = self._determine_accumulated_runoff(rainfall, retention_parameter)
> 
> RUFAS\routines\field\soil\layer_data.py:
>   193      """Fresh organic phosphorus content of this soil layer (kg / ha)"""
>   194:     # TODO: organic phosphorus still needs to be implemented - issue #444
>   195  
> 
>   213      """Fraction of metabolic carbon incorporated into soil during tillage (unitless)"""
>   214:     # TODO: needs to create a method to update this, not sure where it would be
>   215      structural_carbon_transfer_amount: float = 0.0
> 
>   414          arbitrary assumption, but is somewhat reasonable.
>   415:         TODO - #512
>   416  
> 
> RUFAS\routines\field\soil\soil_config_factory.py:
>   13      GENERIC = "generic"
>   14:     # TODO: implement additional soil types
>   15  
> 
> RUFAS\routines\field\soil\soil_data.py:
>   191      total_residue: float = 0
>   192:     """total amount of soil residue ever added to the field"""  # TODO: needed?
>   193      @property
>   194:     def all_residue(self) -> float:  # TODO: not currently used.
>   195          """amount of total plant residue, above and below-ground, on the field (kg/ha)"""
> 
>   380  
>   381:     # TODO: implement method that validates all the values inside the SoilData object, including
>   382      #   - soil layers all have top depths above bottom depths, top depth of top layer is 0, none of the layers are
> 
> RUFAS\routines\field\soil\soil_erosion.py:
>    67  
>    68:         # TODO: does the soil profile needs to have mass removed from it as it gets eroded? - Issue #351
>    69  
> 
>   205      @staticmethod
>   206:     def _determine_support_practice_factor() -> float:  # TODO: implement this for version 2 (GitHub issue #348)
>   207          """SWAT Reference: section 4:1.1.3 (only applies to fields that are doing contour tillage/planting,
> 
>   306          used in the old code, and is used here until the data for subbasin areas can be found.
>   307:         TODO: find subbasin areas database and/or make it a parameter - issue #601
>   308  
> 
> RUFAS\routines\field\soil\soil.py:
>   41          """Process component that handles carbon cycling (through decomposition) in the soil."""
>   42:         # TODO: need to add phosphorus, manure, and carbon cycling main methods methods to the soil methods.
>   43          #   It is unclear to me how best to do that.
> 
>   69          """
>   70:         # TODO: if no other daily update methods are added here, this method should be removed and Field should call
>   71          #       this method directly
> 
> RUFAS\routines\field\soil\carbon_cycling\decomposition.py:
>   5  
>   6: # TODO: the equations for this model, referenced in the soil psuedocode, are derived from the excel file
>   7  #   located on basecamp: https://3.basecamp.com/3486446/buckets/5296287/vaults/2740532358
> 
> RUFAS\routines\field\soil\carbon_cycling\pool_gas_partition.py:
>   272  
>   273:     # TODO: Figure out where did 0.03 and 0.55 come from -- issue #398
>   274      @staticmethod
> 
> RUFAS\routines\field\soil\carbon_cycling\residue_partition.py:
>    60              if self.data.soil_layers.index(layer) == 0:
>    61:                 # TODO: rather than simply mixing the crop residue into the top layer, this module should consider
>    62                  #  tillage
> 
>    73                  layer.soil_dry_matter_residue_amount = 0
>    74:                 self.data.plant_surface_residue = 0  # TODO: why is this not also done for root residue?
>    75  
> 
>   184          return plant_residue_lignin_composition
>   185:         # TODO: check source, 0.1 or 0.01, ask Hector about the value
>   186  
> 
>   189                                                    nitrogen_fraction_plant_residue=0.4) -> float:
>   190:         # TODO nitrogen_fraction_plant_residue calculate in RuFaS [C.5.B.1] but not "accurate" for carbon use -
>   191          #  GitHub Issue #163
> 
>   498          """
>   499:         # TODO: Check where the 0.15 and 0.01 factors came from issue #445
>   500          return max(0.0, weighted_residue_dry_matter_lignin_fraction - 0.15 * rainfall * 0.01)
> 
> RUFAS\routines\field\soil\nitrogen_cycling\denitrification.py:
>   51  
>   52:             # TODO: check that soil_overall_carbon_fraction is being used correctly in this context - issue #475
>   53              nitrified_nitrates = self._calculate_denitrification_amount(layer.nitrate_content,
> 
> RUFAS\routines\field\soil\nitrogen_cycling\leaching_runoff_erosion.py:
>    58          pseudocode_soil [S.4.C.2] (determines what the runoff extraction coefficient will be for nitrates and ammonium)
>    59:         TODO: find literature source for these values, issue #495
>    60  
> 
>   107          pseudocode_soil [S.4.C.8] (determines what the leaching extraction coefficient will be for each pool/layer)
>   108:         TODO: find literature source for these values, issue #495
>   109  
> 
>   310          -----
>   311:         TODO These numbers are modified ans suspected of retrieved from other references instead of SWAT, kept here
>   312          issue #486
> 
>   384          be used to calculate the concentrations of nitrates, ammonium, and active organic nitrogen in the soil.
>   385:         TODO: find literature source for this equation, issue #495
>   386  
> 
>   411          results.
>   412:         TODO: find literature source for this equation, issue #495
>   413  
> 
>   445          This equation has been calibrated so that it best models experimental results.
>   446:         TODO: find literature source for this equation, issue #495
>   447  
> 
> RUFAS\routines\field\soil\nitrogen_cycling\mineralization_decomp.py:
>    40  
>    41:         # TODO: in SWAT, this nutrient ratios do not work directly with the carbon in the soil but with the content of
>    42          #   residue in the soil layer. Currently this not tracked - issue #481
> 
>    58  
>    59:         # TODO: reduce the amount of residue in the soil layer by the decay amount when a residue tracker gets added to
>    60          #   LayerData - issue #481
> 
>    99  
>   100:         TODO: In SWAT, this method takes the amount of residue in the soil (instead of carbon) and multiplies it by 0.58
>   101              to get the amount of carbon in the soil. This method should be refactored to do that when we get a tracker
> 
> RUFAS\routines\field\soil\phosphorus_cycling\manure.py:
>   124          # Calculate bounding ratio
>   125:         # TODO: bound decomposition plus assimilation changes so that their sum cannot be greater than the original, ask
>   126          #   Pete about best way to bound decomposition plus assimilation changes.
> 
>   264          deeper.
>   265:         TODO: implement distribution mechanism for the 20% of phosphorus that infiltrates deeper after talking with Pete
>   266              about how that mechanism works.
> 
>   698          """
>   699:         # TODO: combine this method with _determine_water_extractable_organic_phosphorus_leached() - GitHub issue #423
>   700          if is_from_cow:
> 
>   733          """
>   734:         # TODO: combine this method with _determine_water_extractable_organic_phosphorus_leached() - GitHub issue #423
>   735          result = Manure._determine_water_extractable_inorganic_phosphorus_leached(
> 
> RUFAS\routines\field\soil\phosphorus_cycling\soluble_phosphorus.py:
>   184          Theoretical documentation, in the paragraph below equations [16].
>   185:         TODO: this equation is in the code, both old RuFaS and SurPhos, but is not in the documentation. Also not clear
>   186              what the units are, amend this notes section after talking with Pete - issue #448
>

**Comment by PooyaHekmati** [comment]
Things might have changed since I made this issue. Please recheck and address current TODOs.

**Comment by Isgotkowitz** [comment]
Grooming session: @Isgotkowitz will search for TODOs still in Crop and Soil and update this issue accordingly.

**Comment by matthew7838** [comment]
Grooming session: @Isgotkowitz will search for TODOs still in Crop and Soil and update this issue accordingly.
