### ISSUE TITLE
Put AnimalCombination enum in a separate file and use it instead of hardcoding the names

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#793]
See examples in code like: 

`str(animal_combination) in ['AnimalCombination.LAC_COW']` or `pen.animal_combination.name in ['LAC_COW']`

Addressing this issue will also let us avoid circular imports when adding typing for `animal_combination` across the animal module.

Also: check if this solves the TODO "Annotate pen later when circular dependency is resolved" in `routines/animal/life_cycle/pen_history.py`

**Comment by PooyaHekmati** [comment]
TODO: Follow up with author to check if this is still the case.

**Comment by Isgotkowitz** [comment]
Blocked by #1680

**Comment by allisterakun** [comment]
Part of #1680
