### ISSUE TITLE
Feature request: Incorporate snowfall into `CurrentWeather`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#795]
The `CurrentWeather` module (located in `RUFAS/routines/field/manager/current_weather.py`) needs to better incorporate snowfall.

## Context
In RuFaS, fields take in a number of weather-related parameters, some of which are not actually included in `Weather`. To make it easier to pass all weather-related values to each field, the `CurrentWeather` class was implemented to easily package and deliver all weather values to each field on a daily basis.

## Current
When the `CurrentWeather` instance for the day is created, the amount of rainfall for the day is passed directly from `Weather` to `CurrentWeather` as rainfall. However, the rainfall in `Weather` is actually the precipitation that fell on that day and it is not determined whether it fell as rain or snowfall.

## Desired
When the average temperature for the day is equal to or below 0 degrees C, the precipitation should be counted as snowfall. When the temperature is above 0 degrees C, the precipitation should be treated as rain. ***These exact specifications may change, SMEs have not given final confirmation yet.
Edit: this has been confirmed with Pete Vadas, is good for version 1.***

## Possible Solution
- Create a field in `CurrentWeather` called precipitation.
- Pass the rainfall from `Weather` to `CurrentWeather` as precipitation.
- Write a post_init method that sets either rainfall or snowfall equal to precipitation depending on the average temperature for the day.

**Comment by ew3361zh** [comment]
Addressed with PR #798
