### ISSUE TITLE
Variable name change creates infinite loop in sunnydene_pilot_test

### ISSUE THREAD

**Issue by KatKoebelDVM** [RuminantFarmSystems/RuFaS#800]
I ran a herd with "ED" for both "heifer_repro_method" and "cow_repro_method." I also removed all instances of "estrus_conception_rate" and changed them to "ed_conception_rate" as this is more biologically appropriate.  

## Expected Behavior
Model should run without issue. 

## Current Behavior
Model never completed initialization. Did NOT throw any errors though. 

## Possible Solution
This is likely due to me changing the names "estrus_conception_rate" to "ed_conception_rate" but since no erroneous dependencies were noted I thought this would be okay. 

## Steps to Reproduce
1. Use the updated sunnydene_pilot_test branch. 
2. Model will be stuck initializing, and never begin to run a simulation.

**Comment by KFosterReed** [comment]
Hi Kat, I took a look at this simulation and it is isn't actually the variable name change that is causing the problem. The issue is during the Animal Initialization because the herd you are trying to simulate (i.e. the animal numbers in your initialization file) are larger than the animal database.  This is my fault because I should have made an issue about this when I found it earlier this year during pilot testing with the Ryzebol heard

**Comment by KatKoebelDVM** [comment]
@KFosterReed No worries at all! I can try and run the program again with a smaller herd than the pilot farm specified, or we can tackle this together tomorrow at our meeting. 

Should I keep or discard the variable name changes? I'm a little confused as to why there is an "estrus_conception_rate" in addition to an "ed_conception_rate."

**Comment by KFosterReed** [comment]
Was the estrus repro method working before? I.e. were heifers and cows successfully being bred? If so, then the variable name change probably wasn't necessary. But if it wasn't working then the change is necessary.

**Comment by KatKoebelDVM** [comment]
It wasn't working before the name change either, when I ran it on debugging mode it seemed to be stuck on the repro stuff during initialization so that's why I changed variable names. But it didn't work after either. But could this still be due to the herd size?
