### ISSUE TITLE
Make percolation out of soil layer occur before percolation into soil layer

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#805]
Water percolation downwards through the soil profile is not occurring as desired.

## Current
In the method `percolate()` of the `Percolation` module, the water that percolates out of a soil layer is *immediately* added to the next layer below it.

## Problem
The result of the above order of operations is that there is no opportunity for the water that percolates into a soil layer to stay there before it is available to percolate out of the layer.

## Solution
Adjust the percolation method so that water percolating into a layer on a certain day is not available to percolate out of it on the same day.

**Comment by ew3361zh** [comment]
Resolved in #818
