### ISSUE TITLE
Variables Not Output As Expected 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#812]
While working with the latest version of the Output manager, I noticed some variables are not output correctly. 

1) the number of animals in each parity remain static. 
2) No output of simulation day in the life cycle manager section. 
3) No methane emission output. 

## Expected Behavior

The number of animals and methane emissions should change over the simulation period. 

## Current Behavior

Number of animals for each parity 
![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/7a981213-c625-4f90-86a9-9d3051f089cf)

methane emission 
![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/7c12a17b-f61c-4e0f-83a3-b9b935320ea2)

## Possible Solution

1) Add output manager to the file where the output variable is generated. 
2) Update where the output variable is collected. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by KFosterReed** [comment]
Hey team, I opened and then closed an issue that is similar to this. We need to clean up these outputting bugs so that we can meet our pilot testing goals.

**Comment by ew3361zh** [comment]
@tomhuhh can you add a few specifics for this issue?

>1. the number of animals in each parity remain static.

What output variable are you using to track this?

>2. No output of simulation day in the life cycle manager section.

It looks like there are close to 40 values in the LifeCycleManager.daily_update.* group - can I assume this is the "life cycle manager section"? 

It's been a while since I worked in there but I think we'd originally talked about being able to use the index number of each value reported as interchangeable with the simulation day since it's a daily update. It shouldn't be hard if we just want to add day of simulation to this group though.

**Comment by ew3361zh** [comment]
I am seeing sim_day in the info_maps of the LifeCycleManager.daily_update.* section (right at the top):
<img width="686" alt="Screenshot 2023-10-13 at 11 04 08 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/cf2b106b-1178-4dd4-9acb-6e28da3b2cc1">

We could move that to values if that would be more helpful.

**Comment by ew3361zh** [comment]
This was what I got when I plotted LifeCycleManager.daily_update.[calf_num, heiferI_num, heiferII_num, etc] against sim day:
<img width="902" alt="Screenshot 2023-10-13 at 11 29 17 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/343d0eba-dbd3-41dc-a667-339f1b0668e8">

**Comment by tomhuhh** [comment]
Thanks Niko @ew3361zh  for looking into this! 

> > 1. the number of animals in each parity remain static.
> 
> What output variable are you using to track this?
> 
I used the `LifeCycleManager.daily_update.life_cycle_daily_herd_update.values: num_cow_for_parity` variable to generate the graph comparing the number of animals in each parity. 

> > 2. No output of simulation day in the life cycle manager section.
> 
> It looks like there are close to 40 values in the LifeCycleManager.daily_update.* group - can I assume this is the "life cycle manager section"?
> 
> It's been a while since I worked in there but I think we'd originally talked about being able to use the index number of each value reported as interchangeable with the simulation day since it's a daily update. It shouldn't be hard if we just want to add day of simulation to this group though.

Yes, I believe including the simulation day in each section (i.e. life cycle manager section) makes it easier to interpret the data even though we can assume each row represents one day and the rows are in chronological order.  

Thanks!

**Comment by ew3361zh** [comment]
I will continue looking into the pen methane issue it but it looks like the methane is being calculated for each animal group but not by pen for some reason:
<img width="429" alt="Screenshot 2023-10-13 at 12 51 28 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/91f5746c-50e1-46ff-8997-4bd6c95bd4c5">

**Comment by ew3361zh** [comment]
@tomhuhh does this look closer to what you would expect for the num_cow_for_parity results?
<img width="864" alt="Screenshot 2023-10-13 at 5 05 27 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/421f32cd-2a40-4419-a3f4-7646d0d79b83">

**Comment by tomhuhh** [comment]
> @tomhuhh does this look closer to what you would expect for the num_cow_for_parity results? 

This looks much closer to what I would expect. Thanks Niko @ew3361zh!

**Comment by tomhuhh** [comment]
A follow-up on the enteric methane emission behavior: the data seems to be able to be output with no difficulty. Please see below an example where I used the current main branch to run a simulation for a year and then plotted the enteric methane emissions from lactating cows. To me, this issue has been resolved. Thanks! 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/115201d5-08c0-4b4c-bf6d-a9c39c0cbedf)

**Comment by ew3361zh** [comment]
Addressed with PR #861.
