### ISSUE TITLE
Output files named by user in Scenario Manager.

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#817]
**Is your feature request related to a problem? Please describe.**
In the forthcoming/new method of running simulations, it's possible for users to run multiple simulations sequentially and we need a way to more-easily differentiate the output files from each sequential simulation.

**Describe the solution you'd like**
Converting the METADATA_PATHS variable in `scenario_manager.py` from a list of string paths to metadata files to a list of tuples that would hold the string path to the metadata file and the name the user would like to use and have incorporated at the front of the file names generated from the simulation by that particular metadata file.

e.g: METADATA_PATHS = [('large_farm_metadata_path.json', 'large_farm'), ('small_farm_metadata_path.json', 'small_farm')]

Which would generate variables output files (for example), that looked like:
"large_farm_saved_variables_json..."
"small_farm_saved_variables_json..."

**Describe alternatives you've considered**
@JoeWaddell and I briefly discussed using the metadata file names instead of custom names.

**Comment by PooyaHekmati** [comment]
Generally speaking, it is better to use named tuples or typed dictionaries rather than tuples or dicts. They provide cleaner and more informative code; containing more information withing the code itself which reduces the need for documentation.

**Comment by ew3361zh** [comment]
Addressed by PR #833.
