### ISSUE TITLE
Linting scripts should only check added or modified Python files.

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#831]
**Is your feature request related to a problem? Please describe.**
The `lint_branch_changes` scripts (both shell and batch) check all Python files that were touched in a PR, including ones that were deleted. This is unnecessary, because if a Python file is deleted it doesn't matter if there were any linting issues in it.

**Describe the solution you'd like**
Add the argument `--diff-filter=A,M,R` - this will result in only added, modified, or renamed files being linted.

**Describe alternatives you've considered**

**Additional context**

**Comment by allisterakun** [comment]
As we talked about in the grooming session, we should not include the renamed files.
