### ISSUE TITLE
Missing weather data on the 366th day for leap years in the barnyard_100yr.csv: 2016 and onward 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#835]
## Expected Behavior

The simulation runs successfully when using barnyard_100yr.csv as the input weather file and the start and end years covering at least one leap year after 2016. 

## Current Behavior

The missing data on the 366th day for leap years after 2015 (i.e. 2016, 2020, etc.) in the barnyard_100yr.csv weather file causes the error below in the field.py file. 
`ZeroDivisionError: 0.0 cannot be raised to a negative power`

## Possible Solution

The quick fix is to add arbitrary weather data for the interested leap years. 
`2016,366,0,28.8,21.1,24.9,17.5,0`

The more complete solution requires regeneration of the entire weather file.

## Steps to Reproduce

1. In masters branch, use the default start and end year settings, the simulation should run fine.  
2. Then update the weather file to barnyard_100yr.csv, run the simulation again. It should also work fine.  
3. Next, keep the barnyard_100yr.csv file as the weather input, and change the start and end years to 2016 and 2017 and run. The simulation should fail the gives the following error. 
`File "/Users/haowenhu/Documents/GitHub/MASM/RUFAS/routines/field/field/field.py", line 1214, in _determine_potential_evapotranspiration
    extra_terrestrial_radiation * ((max_air_temp - min_air_temp) ** (-0.5))
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: 0.0 cannot be raised to a negative power`
5.

## Context (Environment)
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

<!--- Provide a general summary of the issue in the Title above -->

## Detailed Description
<!--- Provide a detailed description of the change or addition you are proposing -->

## Possible Implementation
<!--- Not obligatory, but suggest an idea for implementing addition or change -->

**Comment by Isgotkowitz** [comment]
This is also an issue in `barnyard_weather.csv`

**Comment by tomhuhh** [comment]
Hello @allisterakun! Can we close this issue? Thanks!
