### ISSUE TITLE
Not Breeding Heifers

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#854]
The HeiferII repro programs never succeed in breeding this group so eventually the herd will reduce to zero animals

## Expected Behavior

Heifers should be able to get pregnant (we need baby cows to make milk and produce more cows!)

## Current Behavior

Somewhere along the line from the inputs to the heifer II attributes the variable names of these attributes became disconnected from the functions in the heifer repro functions. So far I have found the following: 

-  on L488 in heiferII.py: `if self.tai_method_h == "d5CG2P":` should be `if self.tai_method_h == "md5CG2P":` because that is what the self.tai_method_h will be assigned as. If it took you a minute to figure out what the difference between these two values are, that is part of the point. The repro protocol methods currently rely on complicated names that are very easy to introduce typos. The other problem this highlights is that the logic allows the animals to just pass through without any assigned breeding protocol. If it doesn't find 'md5CG2p' or any of the other options, it just moves on without providing any errors. 
- Another thing to note, is that previously this variable was called '5dCG2P'. When I run the main branch, for a little over a year the heifers have '5dCG2P' as their TAI method instead of 'md5CG2P'. Thus, I am inferring that the  animals that are selected from the Initialization database will likely have the old value instead of 'md5CG2P'. I am not sure why animals are not established with the breeding protocol used in the current simulation, but that would be the ideal outcome. 
- When I changed the if statement on L488 to  `if self.tai_method_h == "md5CG2P":` , animals will start the `d5CG2p_update()`, but when they get to the point of assigning the conception rate on L453, it does not find the conception rate: 
-
![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/a391dbce-264e-4415-a31f-fc2dbd10e220)

## Possible Solution

We have designed the refactor of this part of the model so that is the best solution. I am mostly sharing this information with the hopes that it is helpful so that we can squash this bug for good. 

## Steps to Reproduce

1. One way is to run the default json for a longer period, you will notice that the animals in all groups slowly decline to 0. 
2. Another, quicker way is to run the default json with a print statement on L637 nested under the if statement on L635, you will see that it never inseminates heifers 
3.
4.
5.

**Comment by YijingGong** [comment]
Hey Kristan, since you are running the master branch, it is likely that there are some bugs left over from before. Possible reasons 1) Manfei's fix was not merged in. 2) variable names or input structure was changed during development. At this point, I'll take the notes that during refactoring, we need to 1) make the input variable names and the inputted protocol names easy to understand - we can discuss the protocol name on Monday; 2) provide error messages or warning messages for incorrect protocol names.  @YijingGong @ltp23

**Comment by KFosterReed** [comment]
Thanks for taking a look at this Yijing. Although it is running from the current main branch it is definitely a new behavior because we had previously been able to breed heifers on this branch. However, it is a resurfacing / repeated bug. I think your two notes to keep in mind during the refactoring are perfect.
