### ISSUE TITLE
Invesitgate pool_element_type in output manager

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#855]
In output manager,  `pool_element_type = Dict[str, List[Dict[str, Any]]]` seems wrong. It probably should change to `    pool_element_type = Dict[str, List[Any]]`. Investigate and fix.

**Comment by ew3361zh** [comment]
After looking into it, several of values for the pool_element_type were lists of objects that were not dictionaries as the original pool_element_type defined. It makes sense to update it to pool_element_type = Dict[str, List[Any]].

**Comment by ew3361zh** [comment]
Addressed in PR #901.
