### ISSUE TITLE
Implement loading pool functionality to output manager

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#856]
We are developing Graphics Generation which works downstream to the output manager. We will also implement post-processing. To allow users to use these features without needing to re-run the simulation, it would be nice to have a function in the output manager to reload the pool.

**Comment by ew3361zh** [comment]
Would it work to have the option to forgo flushing the OM pools instead of flushing them and then reloading them?

**Comment by ew3361zh** [comment]
Closed with PR #896.
