### ISSUE TITLE
Ration patches branch

### ISSUE THREAD

**Issue by tlh96** [RuminantFarmSystems/RuFaS#87]
TODO: Create ration patches branch

- Update ration output handler: not all feeds included in the ration output

- Update feed library: minimum and maximums of feeds.

**Comment by JoeWaddell** [comment]
Per discussion in 11 Jan 2023 meeting, @Ed731551 will look into available repositories for current and consistently updated feed data.

**Comment by Ed731551** [comment]
Yes, I can help with this.
