### ISSUE TITLE
IM Element Counter Not Counting Correctly

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#873]
IM element counter is not correctly functioning when json input data is being validated due to the recursive nature of the json validation method.

## Expected Behavior
The IM counts totals of valid elements, invalid elements, elements fixed, and total elements and reports the numbers to OM. The counts are currently not working correctly.

## Current Behavior
The `_validate_json_element` method is recursive to allow for checking nested dictionary elements. The dictionary tracking the values for the different elements to report to OM is instantiated in this method but gets reset when there is a nested variable that is validated.

## Possible Solution
One solution I quickly tested before writing this up was making the element trackers attributes of the IM and then adding a responsibility to the IM's `flush_pool()` method to also reset these values and it seemed to work well.

## Steps to Reproduce
Outlined by @JoeWaddell in PR #828. He was testing the new CLI verbose messaging and saw that an element was fixed during the validation process but the end result of the validation showed a count 0 elements fixed.

**Comment by ltp23** [comment]
- [ ] Start with simply counting the elements without any validation.

**Comment by Isgotkowitz** [comment]
@ltp is this issue still valid? I tried changing some input files on the main branch and it seems like correct counts of elements and data validation messages are being displayed.
