### ISSUE TITLE
Temperature effect on decomposition is calculated with air and not soil temperature

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#875]
In the carbon cycling module, one of the factors that effects decomposition is the "temperature effect on decomposition factor".

## Expected Behavior

Temperature factor should be calculated for each individual soil layer based on that layer's temperature.

## Current Behavior

There is one temperature factor set for the entire soil profile, based on the air temperature.

## Reasoning
The expected behavior relies on some guesswork.

The [psuedocode](https://docs.google.com/document/d/1yrlYhPAmNDweJMQnEp8I1H3nje39390lymnmW_YlmfE/edit) defines the method of calculation of this factor in equation [S.6.A.1]. In the psuedocode, it writes the temperature as _T<sub>avg</sub>_. It is not explicitly stated in the parameters section of [S.6.A.1] that this is the average air temperature of the day, but it is defined as the "mean air temperature for a given day" in the parameters section of equation [S.2.B.1]. And the implementation of the temperature factor in the pre-Soil Crop Redesign Carbon Cycling module uses the average air temperature to calculate this factor.

The implementation of the temperature factor in the pre-Soil Crop Redesign Carbon Cycling module states the equations [S.6.A.1] and [S.6.A.2] come from the [defac](https://3.basecamp.com/3486446/buckets/5296287/vaults/2740532358) spreadsheet. That spreadsheet contains the graph:
![image](https://github.com/RuminantFarmSystems/MASM/assets/43901812/c0f9b7f1-e2d8-49cc-8b5b-01294c459abc)
Because the x-axis is labeled as "average soil temperature" it I think it is reasonable to assume that the temperature effect on decomposition should be calculated with the temperature of the soil, and should be specific to each soil layer.

**Comment by KFosterReed** [comment]
Great detective work Ed and Matthew! I think this logic is solid and although there is some guess work, I am confident that we can confirm this with soil Carbon experts. Kevin and Xuesong are very good candidates but I also have a backup person who has worked with the Daycent model that I am saving for emergency questions if we needed.

**Comment by Isgotkowitz** [comment]
Update: found a description of the calculation for temperature effect on decomposition in DAYCENT [here](https://www2.nrel.colostate.edu/projects/irc/public/Documents/Software/Century5/Reference/index.html) (see the "Effect of Soil Temperature" section). It looks like it is the same equation and it uses soil temp.
