### ISSUE TITLE
Update descriptions in metadata

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#890]
In the metadata files, we have some descriptions like:
`"NASEM_Comp": {
      "title": "NASEM Comp data",
      "description": "Nutrients!",
      "path": "input/data/feed/NASEM_Comp_with_TDN.csv",
      "type": "csv",
      "properties": "NASEM_Comp_properties"
    },`
The description is not informative. This is just one example, we have the same problem in other fields as well. A more meaningful and informative description is needed for these.

**Comment by PooyaHekmati** [comment]
PR #921 is not correct and should have not been approved. The PR adds a description of _The configuration file for the xyz_ for every single data entry. This implies that RUFAS only needs configuration and doesn't need any input data. Please populate the descriptions correctly and informatively before closing the issue. 
CC @JoeWaddell @elle-andreen

**Comment by JoeWaddell** [comment]
Closed by #1190
