### ISSUE TITLE
Graph generator features: handling dictionaries automatically

### ISSUE THREAD

**Issue by JoeWaddell** [RuminantFarmSystems/RuFaS#899]
Current (as of PR #779) dictionaries require information in `filters`, and also a separate list of inputs in the `variables` section of the graph filter.

## requested feature ##
If no `variables` are defined, graph generator will attempt to plot all information in the dictionary. This will be very useful for outputs that are dynamic, e.g. `ration_per_animal_for_pen_3`, as the keys in this dict will change with changes to the Feed input JSON, so this would be frustrating to juggle so many unique filters for Pilot Testers evaluating different farms.

A warning should be logged if the dict is ragged, or it's otherwise impossible to plot data in the dict (e.g. non-numeric data). Perhaps it should plot numeric data, and simply skip non-numeric data in the same dict. 

### related improvements ###
While these may be worth their own PR, I think it's relevant for automatic graph generation from dicts.

1) Have `legend` also generated automatically, from variable names in a dict. The reasoning is the same as the problem that arises from dynamic names (only in some dictionaries).

2) Adding functionality for a `variables_excluded` list. Simply to reduce the length of lists for dicts that are large, in cases where all but a handful of variables are needed.

**Comment by ltp23** [comment]
@PooyaHekmati will reach out to @JoeWaddell regarding the details of this git issue.

**Comment by PooyaHekmati** [comment]
I talked with Joe about this. This feature can be implemented by changing how GG handles keys in dictionaries. Right now it matches the keys by string comparison, in other words, the user has to know and provide the exact key in the dict, which is not always possible. To fix this, we can convert this to regex matching. Also, we can add filter by exclusion, similar to OM filtering mechanism.

**Comment by PooyaHekmati** [comment]
This applies to Report Generator filters as well. Consider making/extracting the function such that it can be used there as well (shouldn't be a problem).

**Comment by ew3361zh** [comment]
Closed by PR #1048
