### ISSUE TITLE
Incorrect number of rows in the aggregate heifer manure outputs 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#904]
## Expected Behavior

The same number of rows in the aggregate heifer manure outputs compared to other animal categories. 

## Current Behavior

The number of rows for heifers are twice of that of other animal categories. Those integers do not seem to belong there. 

<img width="415" alt="Screenshot 2023-11-03 at 10 48 00 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/52800053/e141b6ee-5230-4b4e-a311-bba94ad29dfb">

## Possible Solution

Start with investigating how aggregate heifer manure outputs are collected by the output manager.  

## Steps to Reproduce

1. Use the filter 'Pen.calc_total_manure'. 
2.
3.
4.

**Comment by jadamchick** [comment]
I don't know the mechanism, but it looks as though daily_aggregate_heifer has 2 values for every sim_day. 
The first value is the same as Pen_1 (though off by an order of 1000; different units I assume). 
The second value is equal to the difference between Pen_2 (x1000) and Daily_aggregate_dry_cow. 

The grouping scenario (for pens) in this case is the default: Pen1 = growing (heiferI + heiferII); Pen2 = close-up (heiferIII + dry cow). 

This screen shot is using the methane values to show the math. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/09e1f683-aab3-4cf9-9171-29bddcc2dbfa)
