### ISSUE TITLE
Unexpected spikes in Storage Ammonia 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#907]
## Expected Behavior

Storage ammonia follows seasonal and diurnal patterns based on temperature. 

## Current Behavior

Some unexpected high and low values are output, which seem like outliers. An example is shown below. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/fa3231b8-275c-4c30-b63f-38dbef870d1f)

## Possible Solution

Check how storage ammonia is calculated and check which value contributes to these outliers. 

## Steps to Reproduce

1. On the Pilot_testing branch, set up the configuration to run zirbel_metadata.json. 
2. Navigate to the gas emission outputs from manure management and plot the timeseries daily storage ammonia. 
3.
4.

**Comment by allisterakun** [comment]
This issue was closed according to Loi's conversation with Haowen over Slack. No further technical conversation is needed.
