### ISSUE TITLE
Extract soil profiles from SSURGO database

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#917]
**Is your feature request related to a problem? Please describe.**
In order to make simulation conditions as accurate as possible for pilot testing, it is important to have soil profile inputs that are tailored to the fields being simulated. The data that will be needed to create these soil profiles should be pulled from SSURGO/STATSGO.

**Describe the solution you'd like**
Pull a copy of the SSURGO data (in a SQLite database) should be pulled from [SWAT+ US SSURGO & STATSGO Soils Database](https://plus.swat.tamu.edu/downloads/swatplus_soils.zip). Set up some sort of script to grab the necessary/available data out of the database and write it into a soil input profile.

**Describe alternatives you've considered**
- Use the [soilDB](https://cran.r-project.org/web/packages/soilDB/index.html) R-CRAN package to pull data out of SSURGO/STATSGO.
- Use the interactive [soil properties](https://casoilresource.lawr.ucdavis.edu/soil-properties/) web app from UC-Davis to manually grab the available information.
 
**Additional context**
It may be the case that SSURGO does not contain all the data we need to create full soil profiles, so methods for estimating properties may need to be employed. For example, if the wilting point of a soil layer is not provided, then SWAT Theoretical documentation eqn. 2:3.1.5 should be used.

**Comment by ew3361zh** [comment]
Blocked because put together databases needed into a cohesive, usable form. Ed to meet with Pooya to discuss potential ways forward. Still actively working on it.
