### ISSUE TITLE
Improve error messaging when invalid graph filters passed

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#927]
**Is your feature request related to a problem? Please describe.**
When graph filter files are incorrect, errors are raised and recorded but are not always very clear or specific when saying why the error occurred.

**Describe the solution you'd like**
When there is an issue in a graph filter file found, the error message should be as clear as possible about what cause the error.

**Describe alternatives you've considered**
Leave the error/warning messages as they are.

**Additional context**
Example:
Below is the body of a misformatted filter file titled "graph_filter_example.json" (the first graph has the key `types` instead of `type`)
```json
{
  "multiple": [
    {
      "types": "plot",
      "filters": [
        "Pen\\.calc_total_manure\\.daily_aggregate_calf_(degradable|non_degradable)_volatile_solids"
      ],
      "title": "Daily Aggregate Calf Degradable Volatile Solids",
      "legend": ["Degradable Volatile Solids", "Non-degradable Volatile Solids"]
    },
    {
      "type": "stackplot",
      "filters": ["Cow\\.milking_update\\.milk_data_at_milk_update"],
      "variables": ["milk_lactose", "milk_protein", "milk_fat"],
      "title": "Daily Milk Nutritions",
      "legend": ["lactose", "fat", "protein"]
    }
  ]
}
```
The error message generated when parsing this file is 
```json
"OutputManager._route_save_functions.graph generation exception": {
    "info_maps": [
        {
            "timestamp": "09-Nov-2023_Thu_13-58-57.381800"
        }
    ],
    "values": [
        "'type'"
    ]
}
```
It would be more helpful if it had a message like the following:
```json
"OutputManager._route_save_functions.graph generation exception": {
    "info_maps": [
        {
            "timestamp": "09-Nov-2023_Thu_13-58-57.381800"
        }
    ],
    "values": [
        "Key 'type' missing for graph 'Daily Aggregate Calf Degradable Volatile Solids' in file graph_filter_example.json."
    ]
}
```

**Comment by ltp23** [comment]
@Isgotkowitz will take another look at this git issue.

**Comment by Isgotkowitz** [comment]
11/15 Update: still a relevant issue. The above example is still holds. IMO this is a low priority issue though.

**Comment by ew3361zh** [comment]
Am I correct in summing this up to be more about giving info about improperly formatting the filter file than about sending bad filters (i.e. this is about someone having good filters that are just not properly formatted but not about bad filters that are properly formatted)?
