### ISSUE TITLE
Enhance Soil Carbon Initialization routines

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#944]
**Is your feature request related to a problem? Please describe.**
The current routine for initializing soil carbon levels is overly simplistic. After discussing with SMEs, more detailed initialization routines have been developed.

Current behavior:
After the total amount of carbon in the soil layer is calculated, it is split equally between the three carbon pools in each layer:
1/3 goes to active carbon, 1/3 goes to slow carbon, and 1/3 goes to passive carbon.
Metabolic and structural litter pools are not initialized.

**Describe the solution you'd like**
For the surface soil layer:
- the total amount of soil carbon is partitioned between the active and slow carbon pools with a split of 2% and 98% respectively.
- the initial residue in the simulation is split equally between the surface metabolic and structural litter pools.
  - Note that this even split is a big assumption, but a more realistic assumption would require knowing field management activity that occurred prior to the simulation starting, so this is assumption is at least a good place to start.

For subsurface soil layers:
- the total amount of soil carbon is partitioned between the active, slow, and passive carbon pools with a split of 2%, 54%, and 44% respectively.

**Describe alternatives you've considered**

**Additional context**
Numbers for the splits between active, slow, and passive carbon come from Xuesong, a carbon cycling expert. They are not empirical, because the different carbon pools are just abstractions made up for the purposes of modeling carbon dynamics well. The numbers listed in this issue description are the same as or similar to ones used in more comprehensive carbon cycling models, including SWAT-C, DSSAT, DayCent, etc.

**Comment by ew3361zh** [comment]
Closed wwith PR #961
