### ISSUE TITLE
Review the reporting of nitrous oxide from the manure module

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#952]
Tasks:
- [x] Compost bedded pack barn N2O calculations
- [x] Open lots N2O calculations
- [x] Add those outputs to the OM at the pen level by default.

**Comment by jadamchick** [comment]
Thank you Loi! 
@KFosterReed had mentioned we might also expect N2O from uncovered lagoons? 
and I think @tomhuhh was also interested in learning more about this

**Comment by ltp23** [comment]
> Thank you Loi! @KFosterReed had mentioned we might also expect N2O from uncovered lagoons? and I think @tomhuhh was also interested in learning more about this

Thanks Julia! I chat with Varma (the previous manure module SME) yesterday and he confirmed that we don't have equations for N20 equations for uncovered lagoons, though I don't think we even have that treatment option other than anaerobic lagoons.

And yes, I will add you and Haowen when there is PR ready for review. I think I will make a PR that addresses this git issue and another one that Kristan made for rotary screen.

**Comment by jadamchick** [comment]
Got it, thank you Loi! Good to know about the lagoons, and thanks for working on this.

**Comment by tomhuhh** [comment]
Thanks for keeping me in the loop! @ltp23 @jadamchick
