### ISSUE TITLE
Inconsistency in crop and soil output data format

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#965]
Crop and soil uses a class called OutputGathere to report its variables to the OutputManager. To do so, it uses prefixes in the info_map. There are few issues here:
1. According to the `OutputManager.add_variable` docstring, if a prefix is present in the info_map, it suppresses the automatic prefix generation. This means that almost everywhere in the codebase, the output keys are: `class.function.variable`; but crop and soil outputs are `field=<field_name>.variable`. Not only this is inconsistent with the rest of the system, it also doesn't respect the semantics.
2. OutputGathere populates info_map as: `info_map = {"class": self.__class__.__name__, "function": self.send_daily_variables.__name__}`. This is not a good practice. The `class` and `function` are reported in the info_map to make it possible to backtrack and find the origin of an output variable. In the case of crop and soil, the OutputGatherer is the messenger, not the source. So the class and function names should not be set to `OutputGatherer` and `send_daily_variables`. This obfuscates the results and is the reason why I didn't develop OutputManager such that it automatically gets the caller's info. If field_name is needed, it can be reported as an additional field in the info_map or as a suffix.

**Comment by PooyaHekmati** [comment]
CC @Isgotkowitz

**Comment by Isgotkowitz** [comment]
## Proposed Solution
1. Change the prefixes to be the suffixes. This would change the formatting of the variable name to use Output Manager best practices the while keeping critical information like the field name, the soil layer index, etc in the name of the variable.
2. Breakup and remove `OutputGatherer` from the Crop and Soil module. It should be replaced with individual collection methods located within the modules where the recorded variables are modified. I think this would be a happy medium between having an entire module dedicated to recording variables that is located super far from where said variables are modified (i.e. having `OutputGatherer`), and recording them exactly where they get modified (when lots of variables are modified in the same place, collecting them in that same place could make the code really messy). This strategy would handle most variables in the Crop and Soil module well, but there are some that get modified in several different parts of the codebase on a daily basis that could make collection difficult. These should be handled on a case-by-case basis.
