### ISSUE TITLE
Input Manager wiki is missing info about the metadata

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#966]
We currently don't have any information about the metadata in our wiki. We are relying on our memories to work with the metadata, aka, tribal knowledge. We should fix this. There is a good amount of explanation about metadata in the input manager design doc: https://docs.google.com/document/d/1ezzHCWeqpQmKmJFM7s5wiCiwZV-EfztKhTF0vk2J4Hg/edit?usp=sharing
Although some aspects of the design have changed and this document is no longer accurate, the metadata part still seems relevant.

**Comment by ew3361zh** [comment]
Wiki is updated with metadata info here: https://github.com/RuminantFarmSystems/MASM/wiki/Input-Manager#metadata

Reviewed by @PooyaHekmati and @Isgotkowitz.
