### ISSUE TITLE
keeping metadata and DCA schema in sync

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#968]
Keeping metadata and DCA schema is a labor-intensive work. We need to figure out a way to make this easier, automating it as much as possible. @allisterakun has already written a script for this, which can be a good starting point.

**Comment by ew3361zh** [comment]
Possible solutions:
Either with a github action in DCA or RuFaS repo, or description in the Wiki. Or look further into Allister's script.

**Comment by Isgotkowitz** [comment]
Update as of 1/3: closing this issue is being put off until we do the Fixathon.
