### ISSUE TITLE
Investigate precipitation not being properly recorded when falling as snow

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#973]
When precipitation occurs it should always get recorded, regardless of what form it falls in.

## Expected Behavior

The amount recorded for a day's precipitation should be equal to either the rainfall or snowfall on that day.

## Current Behavior

When there is rainfall, precipitation is recorded as equal to rainfall. But when there is snow fall, precipitation is recorded as 0.

## Steps to Reproduce

1. Write a filter that includes `Weather.*`.
2. Run RuFaS.
3. Observe the behavior of the variables `Weather.precipitation`, `Weather.rainfall`, and `Weather.snowfall`.

**Comment by allisterakun** [comment]
After investigation, if the fix is easy, please go ahead and perform the fix. Otherwise, please make a separate issue with the details.
