### ISSUE TITLE
Make graphs from reports

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#996]
The report generator works by aggregating data. Visualizing the aggregated data is desired. Extend the list of possible keys in the report filter file such that it can accept keys that go into graph filter files as well. If graph-related keys are present, make a call to the graph generator and pass them along. Note that in this scenario, the report generator won't return the aggregated result to the output manager. If the user wants both visualization and numerical results, they would need to make a copy of the filter and remove the graph-related keys from the second copy.

**Comment by allisterakun** [comment]
Possible solutions:

1. Call ReportGenerator in GraphGenerator
2. Call GraphGenerator in ReportGenerator 
3. OutputManager handles them all
